version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
        - VITE_BASE_API_URL=${VITE_BASE_API_URL}
    container_name: genario-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - genario-network

networks:
  genario-network:
    driver: bridge
