/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  GetListSessions400,
  GetListSessions401,
  GetListSessions403,
  GetListSessions404,
  GetListSessions429,
  GetListSessions500,
  GetListSessionsQueryResponse,
} from "../models/get-list-sessions.ts";

function getGetListSessionsUrl() {
  const res = { method: "GET", url: `/api/auth/list-sessions` as const };
  return res;
}

/**
 * @description List all active sessions for the user
 * {@link /list-sessions}
 */
export async function getListSessions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetListSessionsQueryResponse,
    ResponseErrorConfig<
      | GetListSessions400
      | GetListSessions401
      | GetListSessions403
      | GetListSessions404
      | GetListSessions429
      | GetListSessions500
    >,
    unknown
  >({
    method: "GET",
    url: getGetListSessionsUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
