/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  GetError400,
  GetError401,
  GetError403,
  GetError404,
  GetError429,
  GetError500,
  GetErrorQueryResponse,
} from "../models/get-error.ts";
import { getErrorQueryResponseSchema } from "../zod/get-error-schema.ts";

function getGetErrorUrl() {
  const res = { method: "GET", url: `/api/auth/error` as const };
  return res;
}

/**
 * @description Displays an error page
 * {@link /error}
 */
export async function getError(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetErrorQueryResponse,
    ResponseErrorConfig<
      | GetError400
      | GetError401
      | GetError403
      | GetError404
      | GetError429
      | GetError500
    >,
    unknown
  >({ method: "GET", url: getGetErrorUrl().url.toString(), ...requestConfig });
  return getErrorQueryResponseSchema.parse(res.data);
}
