/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  GetUser400,
  GetUser401,
  GetUser403,
  GetUser404,
  GetUser429,
  GetUser500,
  GetUserQueryParams,
  GetUserQueryResponse,
} from "../models/get-user.ts";

function getGetUserUrl() {
  const res = { method: "GET", url: `/api/auth/admin/get-user` as const };
  return res;
}

/**
 * @description Get an existing user
 * {@link /admin/get-user}
 */
export async function getUser(
  { params }: { params?: GetUserQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetUserQueryResponse,
    ResponseErrorConfig<
      | GetUser400
      | GetUser401
      | GetUser403
      | GetUser404
      | GetUser429
      | GetUser500
    >,
    unknown
  >({
    method: "GET",
    url: getGetUserUrl().url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
