/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  PostRevokeSessions400,
  PostRevokeSessions401,
  PostRevokeSessions403,
  PostRevokeSessions404,
  PostRevokeSessions429,
  PostRevokeSessions500,
  PostRevokeSessionsMutationRequest,
  PostRevokeSessionsMutationResponse,
} from "../models/post-revoke-sessions.ts";

function getPostRevokeSessionsUrl() {
  const res = { method: "POST", url: `/api/auth/revoke-sessions` as const };
  return res;
}

/**
 * @description Revoke all sessions for the user
 * {@link /revoke-sessions}
 */
export async function postRevokeSessions(
  { data }: { data?: PostRevokeSessionsMutationRequest } = {},
  config: Partial<RequestConfig<PostRevokeSessionsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostRevokeSessionsMutationResponse,
    ResponseErrorConfig<
      | PostRevokeSessions400
      | PostRevokeSessions401
      | PostRevokeSessions403
      | PostRevokeSessions404
      | PostRevokeSessions429
      | PostRevokeSessions500
    >,
    PostRevokeSessionsMutationRequest
  >({
    method: "POST",
    url: getPostRevokeSessionsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
