/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  PostAccountInfo400,
  PostAccountInfo401,
  PostAccountInfo403,
  PostAccountInfo404,
  PostAccountInfo429,
  PostAccountInfo500,
  PostAccountInfoMutationRequest,
  PostAccountInfoMutationResponse,
} from "../models/post-account-info.ts";

function getPostAccountInfoUrl() {
  const res = { method: "POST", url: `/api/auth/account-info` as const };
  return res;
}

/**
 * @description Get the account info provided by the provider
 * {@link /account-info}
 */
export async function postAccountInfo(
  { data }: { data: PostAccountInfoMutationRequest },
  config: Partial<RequestConfig<PostAccountInfoMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostAccountInfoMutationResponse,
    ResponseErrorConfig<
      | PostAccountInfo400
      | PostAccountInfo401
      | PostAccountInfo403
      | PostAccountInfo404
      | PostAccountInfo429
      | PostAccountInfo500
    >,
    PostAccountInfoMutationRequest
  >({
    method: "POST",
    url: getPostAccountInfoUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
