/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  RevokeUserSessions400,
  RevokeUserSessions401,
  RevokeUserSessions403,
  RevokeUserSessions404,
  RevokeUserSessions429,
  RevokeUserSessions500,
  RevokeUserSessionsMutationRequest,
  RevokeUserSessionsMutationResponse,
} from "../models/revoke-user-sessions.ts";

function getRevokeUserSessionsUrl() {
  const res = {
    method: "POST",
    url: `/api/auth/admin/revoke-user-sessions` as const,
  };
  return res;
}

/**
 * @description Revoke all user sessions
 * {@link /admin/revoke-user-sessions}
 */
export async function revokeUserSessions(
  { data }: { data: RevokeUserSessionsMutationRequest },
  config: Partial<RequestConfig<RevokeUserSessionsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    RevokeUserSessionsMutationResponse,
    ResponseErrorConfig<
      | RevokeUserSessions400
      | RevokeUserSessions401
      | RevokeUserSessions403
      | RevokeUserSessions404
      | RevokeUserSessions429
      | RevokeUserSessions500
    >,
    RevokeUserSessionsMutationRequest
  >({
    method: "POST",
    url: getRevokeUserSessionsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
