/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import type {
  SetUserPassword400,
  SetUserPassword401,
  SetUserPassword403,
  SetUserPassword404,
  SetUserPassword429,
  SetUserPassword500,
  SetUserPasswordMutationRequest,
  SetUserPasswordMutationResponse,
} from "../models/set-user-password.ts";
import {
  setUserPasswordMutationRequestSchema,
  setUserPasswordMutationResponseSchema,
} from "../zod/set-user-password-schema.ts";

function getSetUserPasswordUrl() {
  const res = {
    method: "POST",
    url: `/api/auth/admin/set-user-password` as const,
  };
  return res;
}

/**
 * @description Set a user's password
 * {@link /admin/set-user-password}
 */
export async function setUserPassword(
  { data }: { data: SetUserPasswordMutationRequest },
  config: Partial<RequestConfig<SetUserPasswordMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = setUserPasswordMutationRequestSchema.parse(data);

  const res = await request<
    SetUserPasswordMutationResponse,
    ResponseErrorConfig<
      | SetUserPassword400
      | SetUserPassword401
      | SetUserPassword403
      | SetUserPassword404
      | SetUserPassword429
      | SetUserPassword500
    >,
    SetUserPasswordMutationRequest
  >({
    method: "POST",
    url: getSetUserPasswordUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return setUserPasswordMutationResponseSchema.parse(res.data);
}
