/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import type {
  UnbanUser400,
  UnbanUser401,
  UnbanUser403,
  UnbanUser404,
  UnbanUser429,
  UnbanUser500,
  UnbanUserMutationRequest,
  UnbanUserMutationResponse,
} from "../models/unban-user.ts";
import {
  unbanUserMutationRequestSchema,
  unbanUserMutationResponseSchema,
} from "../zod/unban-user-schema.ts";

function getUnbanUserUrl() {
  const res = { method: "POST", url: `/api/auth/admin/unban-user` as const };
  return res;
}

/**
 * @description Unban a user
 * {@link /admin/unban-user}
 */
export async function unbanUser(
  { data }: { data: UnbanUserMutationRequest },
  config: Partial<RequestConfig<UnbanUserMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = unbanUserMutationRequestSchema.parse(data);

  const res = await request<
    UnbanUserMutationResponse,
    ResponseErrorConfig<
      | UnbanUser400
      | UnbanUser401
      | UnbanUser403
      | UnbanUser404
      | UnbanUser429
      | UnbanUser500
    >,
    UnbanUserMutationRequest
  >({
    method: "POST",
    url: getUnbanUserUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return unbanUserMutationResponseSchema.parse(res.data);
}
