/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from "./user.ts";

export const postEmailOtpVerifyEmail200StatusEnum = {
  true: true,
} as const;

export type PostEmailOtpVerifyEmail200StatusEnumKey =
  (typeof postEmailOtpVerifyEmail200StatusEnum)[keyof typeof postEmailOtpVerifyEmail200StatusEnum];

/**
 * @description Success
 */
export type PostEmailOtpVerifyEmail200 = {
  /**
   * @description Indicates if the verification was successful
   * @type boolean | undefined
   */
  status?: PostEmailOtpVerifyEmail200StatusEnumKey;
  /**
   * @description Session token if autoSignInAfterVerification is enabled, otherwise null
   * @type string
   */
  token?: string | null;
  /**
   * @type object | undefined
   */
  user?: User;
  required?: any;
};

/**
 * @description Bad Request. Usually due to missing parameters, or invalid parameters.
 */
export type PostEmailOtpVerifyEmail400 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export type PostEmailOtpVerifyEmail401 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export type PostEmailOtpVerifyEmail403 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Not Found. The requested resource was not found.
 */
export type PostEmailOtpVerifyEmail404 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export type PostEmailOtpVerifyEmail429 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export type PostEmailOtpVerifyEmail500 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostEmailOtpVerifyEmailMutationRequest = {
  /**
   * @description Email address to verify
   * @type string
   */
  email: string;
  /**
   * @description OTP to verify
   * @type string
   */
  otp: string;
};

export type PostEmailOtpVerifyEmailMutationResponse =
  PostEmailOtpVerifyEmail200;

export type PostEmailOtpVerifyEmailMutation = {
  Response: PostEmailOtpVerifyEmail200;
  Request: PostEmailOtpVerifyEmailMutationRequest;
  Errors:
    | PostEmailOtpVerifyEmail400
    | PostEmailOtpVerifyEmail401
    | PostEmailOtpVerifyEmail403
    | PostEmailOtpVerifyEmail404
    | PostEmailOtpVerifyEmail429
    | PostEmailOtpVerifyEmail500;
};
