/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description A Valid access token
 */
export type PostGetAccessToken200 = {
  /**
   * @type string | undefined
   */
  tokenType?: string;
  /**
   * @type string | undefined
   */
  idToken?: string;
  /**
   * @type string | undefined
   */
  accessToken?: string;
  /**
   * @type string | undefined
   */
  refreshToken?: string;
  /**
   * @type string | undefined, date-time
   */
  accessTokenExpiresAt?: string;
  /**
   * @type string | undefined, date-time
   */
  refreshTokenExpiresAt?: string;
};

/**
 * @description Invalid refresh token or provider configuration
 */
export type PostGetAccessToken400 = any;

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export type PostGetAccessToken401 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export type PostGetAccessToken403 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Not Found. The requested resource was not found.
 */
export type PostGetAccessToken404 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export type PostGetAccessToken429 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export type PostGetAccessToken500 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostGetAccessTokenMutationRequest = {
  /**
   * @description The provider ID for the OAuth provider
   * @type string
   */
  providerId: string;
  /**
   * @description The account ID associated with the refresh token
   * @type string
   */
  accountId?: string | null;
  /**
   * @description The user ID associated with the account
   * @type string
   */
  userId?: string | null;
};

export type PostGetAccessTokenMutationResponse = PostGetAccessToken200;

export type PostGetAccessTokenMutation = {
  Response: PostGetAccessToken200;
  Request: PostGetAccessTokenMutationRequest;
  Errors:
    | PostGetAccessToken400
    | PostGetAccessToken401
    | PostGetAccessToken403
    | PostGetAccessToken404
    | PostGetAccessToken429
    | PostGetAccessToken500;
};
