/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Success
 */
export type PostEmailOtpSendVerificationOtp200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
};

/**
 * @description Bad Request. Usually due to missing parameters, or invalid parameters.
 */
export type PostEmailOtpSendVerificationOtp400 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export type PostEmailOtpSendVerificationOtp401 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export type PostEmailOtpSendVerificationOtp403 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Not Found. The requested resource was not found.
 */
export type PostEmailOtpSendVerificationOtp404 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export type PostEmailOtpSendVerificationOtp429 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export type PostEmailOtpSendVerificationOtp500 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostEmailOtpSendVerificationOtpMutationRequest = {
  /**
   * @description Email address to send the OTP
   * @type string
   */
  email: string;
  /**
   * @description Type of the OTP
   * @type string
   */
  type: string;
};

export type PostEmailOtpSendVerificationOtpMutationResponse =
  PostEmailOtpSendVerificationOtp200;

export type PostEmailOtpSendVerificationOtpMutation = {
  Response: PostEmailOtpSendVerificationOtp200;
  Request: PostEmailOtpSendVerificationOtpMutationRequest;
  Errors:
    | PostEmailOtpSendVerificationOtp400
    | PostEmailOtpSendVerificationOtp401
    | PostEmailOtpSendVerificationOtp403
    | PostEmailOtpSendVerificationOtp404
    | PostEmailOtpSendVerificationOtp429
    | PostEmailOtpSendVerificationOtp500;
};
