/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Success
 */
export type PostEmailOtpResetPassword200 = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
};

/**
 * @description Bad Request. Usually due to missing parameters, or invalid parameters.
 */
export type PostEmailOtpResetPassword400 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export type PostEmailOtpResetPassword401 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export type PostEmailOtpResetPassword403 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Not Found. The requested resource was not found.
 */
export type PostEmailOtpResetPassword404 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export type PostEmailOtpResetPassword429 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export type PostEmailOtpResetPassword500 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostEmailOtpResetPasswordMutationRequest = {
  /**
   * @description Email address to reset the password
   * @type string
   */
  email: string;
  /**
   * @description OTP sent to the email
   * @type string
   */
  otp: string;
  /**
   * @description New password
   * @type string
   */
  password: string;
};

export type PostEmailOtpResetPasswordMutationResponse =
  PostEmailOtpResetPassword200;

export type PostEmailOtpResetPasswordMutation = {
  Response: PostEmailOtpResetPassword200;
  Request: PostEmailOtpResetPasswordMutationRequest;
  Errors:
    | PostEmailOtpResetPassword400
    | PostEmailOtpResetPassword401
    | PostEmailOtpResetPassword403
    | PostEmailOtpResetPassword404
    | PostEmailOtpResetPassword429
    | PostEmailOtpResetPassword500;
};
