/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const postDeleteUser200MessageEnum = {
  "User deleted": "User deleted",
  "Verification email sent": "Verification email sent",
} as const;

export type PostDeleteUser200MessageEnumKey =
  (typeof postDeleteUser200MessageEnum)[keyof typeof postDeleteUser200MessageEnum];

/**
 * @description User deletion processed successfully
 */
export type PostDeleteUser200 = {
  /**
   * @description Indicates if the operation was successful
   * @type boolean
   */
  success: boolean;
  /**
   * @description Status message of the deletion process
   * @type string
   */
  message: PostDeleteUser200MessageEnumKey;
};

/**
 * @description Bad Request. Usually due to missing parameters, or invalid parameters.
 */
export type PostDeleteUser400 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export type PostDeleteUser401 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export type PostDeleteUser403 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Not Found. The requested resource was not found.
 */
export type PostDeleteUser404 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export type PostDeleteUser429 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export type PostDeleteUser500 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostDeleteUserMutationRequest = {
  /**
   * @description The callback URL to redirect to after the user is deleted
   * @type string
   */
  callbackURL?: string | null;
  /**
   * @description The password of the user is required to delete the user
   * @type string
   */
  password?: string | null;
  /**
   * @description The token to delete the user is required
   * @type string
   */
  token?: string | null;
};

export type PostDeleteUserMutationResponse = PostDeleteUser200;

export type PostDeleteUserMutation = {
  Response: PostDeleteUser200;
  Request: PostDeleteUserMutationRequest;
  Errors:
    | PostDeleteUser400
    | PostDeleteUser401
    | PostDeleteUser403
    | PostDeleteUser404
    | PostDeleteUser429
    | PostDeleteUser500;
};
