/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Success
 */
export type PostAdminHasPermission200 = {
  /**
   * @type string | undefined
   */
  error?: string;
  /**
   * @type boolean
   */
  success: boolean;
};

/**
 * @description Bad Request. Usually due to missing parameters, or invalid parameters.
 */
export type PostAdminHasPermission400 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export type PostAdminHasPermission401 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export type PostAdminHasPermission403 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Not Found. The requested resource was not found.
 */
export type PostAdminHasPermission404 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export type PostAdminHasPermission429 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export type PostAdminHasPermission500 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

export type PostAdminHasPermissionMutationRequest = {
  /**
   * @description The permission to check
   * @deprecated
   * @type object | undefined
   */
  permission?: object;
  /**
   * @description The permission to check
   * @type object
   */
  permissions: object;
};

export type PostAdminHasPermissionMutationResponse = PostAdminHasPermission200;

export type PostAdminHasPermissionMutation = {
  Response: PostAdminHasPermission200;
  Request: PostAdminHasPermissionMutationRequest;
  Errors:
    | PostAdminHasPermission400
    | PostAdminHasPermission401
    | PostAdminHasPermission403
    | PostAdminHasPermission404
    | PostAdminHasPermission429
    | PostAdminHasPermission500;
};
