/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from "./user.ts";

/**
 * @description User updated
 */
export type UpdateUser200 = {
  /**
   * @type object | undefined
   */
  user?: User;
};

/**
 * @description Bad Request. Usually due to missing parameters, or invalid parameters.
 */
export type UpdateUser400 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export type UpdateUser401 = {
  /**
   * @type string
   */
  message: string;
};

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export type UpdateUser403 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Not Found. The requested resource was not found.
 */
export type UpdateUser404 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export type UpdateUser429 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export type UpdateUser500 = {
  /**
   * @type string | undefined
   */
  message?: string;
};

export type UpdateUserMutationRequest = {
  /**
   * @description The user id
   * @type string
   */
  userId: string;
  /**
   * @description The user data to update
   * @type string
   */
  data: string;
};

export type UpdateUserMutationResponse = UpdateUser200;

export type UpdateUserMutation = {
  Response: UpdateUser200;
  Request: UpdateUserMutationRequest;
  Errors:
    | UpdateUser400
    | UpdateUser401
    | UpdateUser403
    | UpdateUser404
    | UpdateUser429
    | UpdateUser500;
};
