/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";

import { getResetPasswordToken } from "../clients/get-reset-password-token.ts";
import type {
  GetResetPasswordToken400,
  GetResetPasswordToken401,
  GetResetPasswordToken403,
  GetResetPasswordToken404,
  GetResetPasswordToken429,
  GetResetPasswordToken500,
  GetResetPasswordTokenPathParams,
  GetResetPasswordTokenQueryParams,
  GetResetPasswordTokenQueryResponse,
} from "../models/get-reset-password-token.ts";

export const getResetPasswordTokenQueryKey = (
  { token }: { token: GetResetPasswordTokenPathParams["token"] },
  params: GetResetPasswordTokenQueryParams = {},
) =>
  [
    { url: "/reset-password/:token", params: { token: token } },
    ...(params ? [params] : []),
  ] as const;

export type GetResetPasswordTokenQueryKey = ReturnType<
  typeof getResetPasswordTokenQueryKey
>;

export function getResetPasswordTokenQueryOptions(
  {
    token,
    params,
  }: {
    token: GetResetPasswordTokenPathParams["token"];
    params?: GetResetPasswordTokenQueryParams;
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getResetPasswordTokenQueryKey({ token }, params);
  return queryOptions<
    GetResetPasswordTokenQueryResponse,
    ResponseErrorConfig<
      | GetResetPasswordToken400
      | GetResetPasswordToken401
      | GetResetPasswordToken403
      | GetResetPasswordToken404
      | GetResetPasswordToken429
      | GetResetPasswordToken500
    >,
    GetResetPasswordTokenQueryResponse,
    typeof queryKey
  >({
    enabled: !!token,
    queryKey,
    queryFn: async ({ signal }) => {
      return getResetPasswordToken(
        { token: token, params: params },
        { ...config, signal: config.signal ?? signal },
      );
    },
  });
}

/**
 * @description Redirects the user to the callback URL with the token
 * {@link /reset-password/:token}
 */
export function useGetResetPasswordToken<
  TData = GetResetPasswordTokenQueryResponse,
  TQueryData = GetResetPasswordTokenQueryResponse,
  TQueryKey extends QueryKey = GetResetPasswordTokenQueryKey,
>(
  {
    token,
    params,
  }: {
    token: GetResetPasswordTokenPathParams["token"];
    params?: GetResetPasswordTokenQueryParams;
  },
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetResetPasswordTokenQueryResponse,
        ResponseErrorConfig<
          | GetResetPasswordToken400
          | GetResetPasswordToken401
          | GetResetPasswordToken403
          | GetResetPasswordToken404
          | GetResetPasswordToken429
          | GetResetPasswordToken500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getResetPasswordTokenQueryKey({ token }, params);

  const query = useQuery(
    {
      ...getResetPasswordTokenQueryOptions({ token, params }, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetResetPasswordToken400
      | GetResetPasswordToken401
      | GetResetPasswordToken403
      | GetResetPasswordToken404
      | GetResetPasswordToken429
      | GetResetPasswordToken500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
