/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { getUser } from "../clients/get-user.ts";
import type {
  GetUser400,
  GetUser401,
  GetUser403,
  GetUser404,
  GetUser429,
  GetUser500,
  GetUserQueryParams,
  GetUserQueryResponse,
} from "../models/get-user.ts";

export const getUserQueryKey = (params: GetUserQueryParams = {}) =>
  [{ url: "/admin/get-user" }, ...(params ? [params] : [])] as const;

export type GetUserQueryKey = ReturnType<typeof getUserQueryKey>;

export function getUserQueryOptions(
  { params }: { params?: GetUserQueryParams } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getUserQueryKey(params);
  return queryOptions<
    GetUserQueryResponse,
    ResponseErrorConfig<
      | GetUser400
      | GetUser401
      | GetUser403
      | GetUser404
      | GetUser429
      | GetUser500
    >,
    GetUserQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getUser(
        { params: params },
        { ...config, signal: config.signal ?? signal },
      );
    },
  });
}

/**
 * @description Get an existing user
 * {@link /admin/get-user}
 */
export function useGetUser<
  TData = GetUserQueryResponse,
  TQueryData = GetUserQueryResponse,
  TQueryKey extends QueryKey = GetUserQueryKey,
>(
  { params }: { params?: GetUserQueryParams } = {},
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetUserQueryResponse,
        ResponseErrorConfig<
          | GetUser400
          | GetUser401
          | GetUser403
          | GetUser404
          | GetUser429
          | GetUser500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getUserQueryKey(params);

  const query = useQuery(
    {
      ...getUserQueryOptions({ params }, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetUser400
      | GetUser401
      | GetUser403
      | GetUser404
      | GetUser429
      | GetUser500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
