/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { getListSessions } from "../clients/get-list-sessions.ts";
import type {
  GetListSessions400,
  GetListSessions401,
  GetListSessions403,
  GetListSessions404,
  GetListSessions429,
  GetListSessions500,
  GetListSessionsQueryResponse,
} from "../models/get-list-sessions.ts";

export const getListSessionsQueryKey = () =>
  [{ url: "/list-sessions" }] as const;

export type GetListSessionsQueryKey = ReturnType<
  typeof getListSessionsQueryKey
>;

export function getListSessionsQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getListSessionsQueryKey();
  return queryOptions<
    GetListSessionsQueryResponse,
    ResponseErrorConfig<
      | GetListSessions400
      | GetListSessions401
      | GetListSessions403
      | GetListSessions404
      | GetListSessions429
      | GetListSessions500
    >,
    GetListSessionsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getListSessions({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @description List all active sessions for the user
 * {@link /list-sessions}
 */
export function useGetListSessions<
  TData = GetListSessionsQueryResponse,
  TQueryData = GetListSessionsQueryResponse,
  TQueryKey extends QueryKey = GetListSessionsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetListSessionsQueryResponse,
        ResponseErrorConfig<
          | GetListSessions400
          | GetListSessions401
          | GetListSessions403
          | GetListSessions404
          | GetListSessions429
          | GetListSessions500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getListSessionsQueryKey();

  const query = useQuery(
    {
      ...getListSessionsQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetListSessions400
      | GetListSessions401
      | GetListSessions403
      | GetListSessions404
      | GetListSessions429
      | GetListSessions500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
