/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { impersonateUser } from "../clients/impersonate-user.ts";
import type {
  ImpersonateUser400,
  ImpersonateUser401,
  ImpersonateUser403,
  ImpersonateUser404,
  ImpersonateUser429,
  ImpersonateUser500,
  ImpersonateUserMutationRequest,
  ImpersonateUserMutationResponse,
} from "../models/impersonate-user.ts";

export const impersonateUserMutationKey = () =>
  [{ url: "/admin/impersonate-user" }] as const;

export type ImpersonateUserMutationKey = ReturnType<
  typeof impersonateUserMutationKey
>;

export function impersonateUserMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<ImpersonateUserMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = impersonateUserMutationKey();
  return mutationOptions<
    ImpersonateUserMutationResponse,
    ResponseErrorConfig<
      | ImpersonateUser400
      | ImpersonateUser401
      | ImpersonateUser403
      | ImpersonateUser404
      | ImpersonateUser429
      | ImpersonateUser500
    >,
    { data: ImpersonateUserMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return impersonateUser({ data }, config);
    },
  });
}

/**
 * @description Impersonate a user
 * {@link /admin/impersonate-user}
 */
export function useImpersonateUser<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ImpersonateUserMutationResponse,
      ResponseErrorConfig<
        | ImpersonateUser400
        | ImpersonateUser401
        | ImpersonateUser403
        | ImpersonateUser404
        | ImpersonateUser429
        | ImpersonateUser500
      >,
      { data: ImpersonateUserMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<ImpersonateUserMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? impersonateUserMutationKey();

  const baseOptions = impersonateUserMutationOptions(
    config,
  ) as UseMutationOptions<
    ImpersonateUserMutationResponse,
    ResponseErrorConfig<
      | ImpersonateUser400
      | ImpersonateUser401
      | ImpersonateUser403
      | ImpersonateUser404
      | ImpersonateUser429
      | ImpersonateUser500
    >,
    { data: ImpersonateUserMutationRequest },
    TContext
  >;

  return useMutation<
    ImpersonateUserMutationResponse,
    ResponseErrorConfig<
      | ImpersonateUser400
      | ImpersonateUser401
      | ImpersonateUser403
      | ImpersonateUser404
      | ImpersonateUser429
      | ImpersonateUser500
    >,
    { data: ImpersonateUserMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ImpersonateUserMutationResponse,
    ResponseErrorConfig<
      | ImpersonateUser400
      | ImpersonateUser401
      | ImpersonateUser403
      | ImpersonateUser404
      | ImpersonateUser429
      | ImpersonateUser500
    >,
    { data: ImpersonateUserMutationRequest },
    TContext
  >;
}
