/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import { listUserSessions } from "../clients/list-user-sessions.ts";
import type {
  ListUserSessions400,
  ListUserSessions401,
  ListUserSessions403,
  ListUserSessions404,
  ListUserSessions429,
  ListUserSessions500,
  ListUserSessionsMutationRequest,
  ListUserSessionsMutationResponse,
} from "../models/list-user-sessions.ts";

export const listUserSessionsMutationKey = () =>
  [{ url: "/admin/list-user-sessions" }] as const;

export type ListUserSessionsMutationKey = ReturnType<
  typeof listUserSessionsMutationKey
>;

export function listUserSessionsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<ListUserSessionsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = listUserSessionsMutationKey();
  return mutationOptions<
    ListUserSessionsMutationResponse,
    ResponseErrorConfig<
      | ListUserSessions400
      | ListUserSessions401
      | ListUserSessions403
      | ListUserSessions404
      | ListUserSessions429
      | ListUserSessions500
    >,
    { data: ListUserSessionsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return listUserSessions({ data }, config);
    },
  });
}

/**
 * @description List user sessions
 * {@link /admin/list-user-sessions}
 */
export function useListUserSessions<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ListUserSessionsMutationResponse,
      ResponseErrorConfig<
        | ListUserSessions400
        | ListUserSessions401
        | ListUserSessions403
        | ListUserSessions404
        | ListUserSessions429
        | ListUserSessions500
      >,
      { data: ListUserSessionsMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<ListUserSessionsMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? listUserSessionsMutationKey();

  const baseOptions = listUserSessionsMutationOptions(
    config,
  ) as UseMutationOptions<
    ListUserSessionsMutationResponse,
    ResponseErrorConfig<
      | ListUserSessions400
      | ListUserSessions401
      | ListUserSessions403
      | ListUserSessions404
      | ListUserSessions429
      | ListUserSessions500
    >,
    { data: ListUserSessionsMutationRequest },
    TContext
  >;

  return useMutation<
    ListUserSessionsMutationResponse,
    ResponseErrorConfig<
      | ListUserSessions400
      | ListUserSessions401
      | ListUserSessions403
      | ListUserSessions404
      | ListUserSessions429
      | ListUserSessions500
    >,
    { data: ListUserSessionsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    ListUserSessionsMutationResponse,
    ResponseErrorConfig<
      | ListUserSessions400
      | ListUserSessions401
      | ListUserSessions403
      | ListUserSessions404
      | ListUserSessions429
      | ListUserSessions500
    >,
    { data: ListUserSessionsMutationRequest },
    TContext
  >;
}
