/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { postEmailOtpSendVerificationOtp } from "../clients/post-email-otp-send-verification-otp.ts";
import type {
  PostEmailOtpSendVerificationOtp400,
  PostEmailOtpSendVerificationOtp401,
  PostEmailOtpSendVerificationOtp403,
  PostEmailOtpSendVerificationOtp404,
  PostEmailOtpSendVerificationOtp429,
  PostEmailOtpSendVerificationOtp500,
  PostEmailOtpSendVerificationOtpMutationRequest,
  PostEmailOtpSendVerificationOtpMutationResponse,
} from "../models/post-email-otp-send-verification-otp.ts";

export const postEmailOtpSendVerificationOtpMutationKey = () =>
  [{ url: "/email-otp/send-verification-otp" }] as const;

export type PostEmailOtpSendVerificationOtpMutationKey = ReturnType<
  typeof postEmailOtpSendVerificationOtpMutationKey
>;

export function postEmailOtpSendVerificationOtpMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PostEmailOtpSendVerificationOtpMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = postEmailOtpSendVerificationOtpMutationKey();
  return mutationOptions<
    PostEmailOtpSendVerificationOtpMutationResponse,
    ResponseErrorConfig<
      | PostEmailOtpSendVerificationOtp400
      | PostEmailOtpSendVerificationOtp401
      | PostEmailOtpSendVerificationOtp403
      | PostEmailOtpSendVerificationOtp404
      | PostEmailOtpSendVerificationOtp429
      | PostEmailOtpSendVerificationOtp500
    >,
    { data: PostEmailOtpSendVerificationOtpMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postEmailOtpSendVerificationOtp({ data }, config);
    },
  });
}

/**
 * @description Send verification OTP
 * {@link /email-otp/send-verification-otp}
 */
export function usePostEmailOtpSendVerificationOtp<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostEmailOtpSendVerificationOtpMutationResponse,
      ResponseErrorConfig<
        | PostEmailOtpSendVerificationOtp400
        | PostEmailOtpSendVerificationOtp401
        | PostEmailOtpSendVerificationOtp403
        | PostEmailOtpSendVerificationOtp404
        | PostEmailOtpSendVerificationOtp429
        | PostEmailOtpSendVerificationOtp500
      >,
      { data: PostEmailOtpSendVerificationOtpMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostEmailOtpSendVerificationOtpMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postEmailOtpSendVerificationOtpMutationKey();

  const baseOptions = postEmailOtpSendVerificationOtpMutationOptions(
    config,
  ) as UseMutationOptions<
    PostEmailOtpSendVerificationOtpMutationResponse,
    ResponseErrorConfig<
      | PostEmailOtpSendVerificationOtp400
      | PostEmailOtpSendVerificationOtp401
      | PostEmailOtpSendVerificationOtp403
      | PostEmailOtpSendVerificationOtp404
      | PostEmailOtpSendVerificationOtp429
      | PostEmailOtpSendVerificationOtp500
    >,
    { data: PostEmailOtpSendVerificationOtpMutationRequest },
    TContext
  >;

  return useMutation<
    PostEmailOtpSendVerificationOtpMutationResponse,
    ResponseErrorConfig<
      | PostEmailOtpSendVerificationOtp400
      | PostEmailOtpSendVerificationOtp401
      | PostEmailOtpSendVerificationOtp403
      | PostEmailOtpSendVerificationOtp404
      | PostEmailOtpSendVerificationOtp429
      | PostEmailOtpSendVerificationOtp500
    >,
    { data: PostEmailOtpSendVerificationOtpMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostEmailOtpSendVerificationOtpMutationResponse,
    ResponseErrorConfig<
      | PostEmailOtpSendVerificationOtp400
      | PostEmailOtpSendVerificationOtp401
      | PostEmailOtpSendVerificationOtp403
      | PostEmailOtpSendVerificationOtp404
      | PostEmailOtpSendVerificationOtp429
      | PostEmailOtpSendVerificationOtp500
    >,
    { data: PostEmailOtpSendVerificationOtpMutationRequest },
    TContext
  >;
}
