/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";

import { postRefreshToken } from "../clients/post-refresh-token.ts";
import type {
  PostRefreshToken400,
  PostRefreshToken401,
  PostRefreshToken403,
  PostRefreshToken404,
  PostRefreshToken429,
  PostRefreshToken500,
  PostRefreshTokenMutationRequest,
  PostRefreshTokenMutationResponse,
} from "../models/post-refresh-token.ts";

export const postRefreshTokenMutationKey = () =>
  [{ url: "/refresh-token" }] as const;

export type PostRefreshTokenMutationKey = ReturnType<
  typeof postRefreshTokenMutationKey
>;

export function postRefreshTokenMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostRefreshTokenMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = postRefreshTokenMutationKey();
  return mutationOptions<
    PostRefreshTokenMutationResponse,
    ResponseErrorConfig<
      | PostRefreshToken400
      | PostRefreshToken401
      | PostRefreshToken403
      | PostRefreshToken404
      | PostRefreshToken429
      | PostRefreshToken500
    >,
    { data: PostRefreshTokenMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postRefreshToken({ data }, config);
    },
  });
}

/**
 * @description Refresh the access token using a refresh token
 * {@link /refresh-token}
 */
export function usePostRefreshToken<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostRefreshTokenMutationResponse,
      ResponseErrorConfig<
        | PostRefreshToken400
        | PostRefreshToken401
        | PostRefreshToken403
        | PostRefreshToken404
        | PostRefreshToken429
        | PostRefreshToken500
      >,
      { data: PostRefreshTokenMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostRefreshTokenMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postRefreshTokenMutationKey();

  const baseOptions = postRefreshTokenMutationOptions(
    config,
  ) as UseMutationOptions<
    PostRefreshTokenMutationResponse,
    ResponseErrorConfig<
      | PostRefreshToken400
      | PostRefreshToken401
      | PostRefreshToken403
      | PostRefreshToken404
      | PostRefreshToken429
      | PostRefreshToken500
    >,
    { data: PostRefreshTokenMutationRequest },
    TContext
  >;

  return useMutation<
    PostRefreshTokenMutationResponse,
    ResponseErrorConfig<
      | PostRefreshToken400
      | PostRefreshToken401
      | PostRefreshToken403
      | PostRefreshToken404
      | PostRefreshToken429
      | PostRefreshToken500
    >,
    { data: PostRefreshTokenMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostRefreshTokenMutationResponse,
    ResponseErrorConfig<
      | PostRefreshToken400
      | PostRefreshToken401
      | PostRefreshToken403
      | PostRefreshToken404
      | PostRefreshToken429
      | PostRefreshToken500
    >,
    { data: PostRefreshTokenMutationRequest },
    TContext
  >;
}
