/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { setUserPassword } from "../clients/set-user-password.ts";
import type {
  SetUserPassword400,
  SetUserPassword401,
  SetUserPassword403,
  SetUserPassword404,
  SetUserPassword429,
  SetUserPassword500,
  SetUserPasswordMutationRequest,
  SetUserPasswordMutationResponse,
} from "../models/set-user-password.ts";

export const setUserPasswordMutationKey = () =>
  [{ url: "/admin/set-user-password" }] as const;

export type SetUserPasswordMutationKey = ReturnType<
  typeof setUserPasswordMutationKey
>;

export function setUserPasswordMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<SetUserPasswordMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = setUserPasswordMutationKey();
  return mutationOptions<
    SetUserPasswordMutationResponse,
    ResponseErrorConfig<
      | SetUserPassword400
      | SetUserPassword401
      | SetUserPassword403
      | SetUserPassword404
      | SetUserPassword429
      | SetUserPassword500
    >,
    { data: SetUserPasswordMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return setUserPassword({ data }, config);
    },
  });
}

/**
 * @description Set a user's password
 * {@link /admin/set-user-password}
 */
export function useSetUserPassword<TContext>(
  options: {
    mutation?: UseMutationOptions<
      SetUserPasswordMutationResponse,
      ResponseErrorConfig<
        | SetUserPassword400
        | SetUserPassword401
        | SetUserPassword403
        | SetUserPassword404
        | SetUserPassword429
        | SetUserPassword500
      >,
      { data: SetUserPasswordMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<SetUserPasswordMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? setUserPasswordMutationKey();

  const baseOptions = setUserPasswordMutationOptions(
    config,
  ) as UseMutationOptions<
    SetUserPasswordMutationResponse,
    ResponseErrorConfig<
      | SetUserPassword400
      | SetUserPassword401
      | SetUserPassword403
      | SetUserPassword404
      | SetUserPassword429
      | SetUserPassword500
    >,
    { data: SetUserPasswordMutationRequest },
    TContext
  >;

  return useMutation<
    SetUserPasswordMutationResponse,
    ResponseErrorConfig<
      | SetUserPassword400
      | SetUserPassword401
      | SetUserPassword403
      | SetUserPassword404
      | SetUserPassword429
      | SetUserPassword500
    >,
    { data: SetUserPasswordMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    SetUserPasswordMutationResponse,
    ResponseErrorConfig<
      | SetUserPassword400
      | SetUserPassword401
      | SetUserPassword403
      | SetUserPassword404
      | SetUserPassword429
      | SetUserPassword500
    >,
    { data: SetUserPasswordMutationRequest },
    TContext
  >;
}
