// This file is auto-generated by @hey-api/openapi-ts

import {
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  banUser,
  createUser,
  getDeleteUserCallback,
  getError,
  getGetSession,
  getListAccounts,
  getListSessions,
  getOk,
  getResetPasswordByToken,
  getUser,
  getVerifyEmail,
  impersonateUser,
  listUsers,
  listUserSessions,
  type Options,
  postAccountInfo,
  postAdminHasPermission,
  postAdminStopImpersonating,
  postChangeEmail,
  postChangePassword,
  postDeleteUser,
  postEmailOtpCheckVerificationOtp,
  postEmailOtpResetPassword,
  postEmailOtpSendVerificationOtp,
  postEmailOtpVerifyEmail,
  postForgetPassword,
  postForgetPasswordEmailOtp,
  postGetAccessToken,
  postLinkSocial,
  postRefreshToken,
  postRequestPasswordReset,
  postResetPassword,
  postRevokeOtherSessions,
  postRevokeSession,
  postRevokeSessions,
  postSendVerificationEmail,
  postSignInEmail,
  postSignInEmailOtp,
  postSignOut,
  postSignUpEmail,
  postUnlinkAccount,
  postUpdateUser,
  removeUser,
  revokeUserSession,
  revokeUserSessions,
  setRole,
  setUserPassword,
  socialSignIn,
  unbanUser,
  updateUser,
} from "../sdk.gen";
import type {
  BanUserData,
  BanUserError,
  BanUserResponse,
  CreateUserData,
  CreateUserError,
  CreateUserResponse,
  GetDeleteUserCallbackData,
  GetErrorData,
  GetGetSessionData,
  GetListAccountsData,
  GetListSessionsData,
  GetOkData,
  GetResetPasswordByTokenData,
  GetUserData,
  GetVerifyEmailData,
  ImpersonateUserData,
  ImpersonateUserError,
  ImpersonateUserResponse,
  ListUsersData,
  ListUsersError,
  ListUserSessionsData,
  ListUserSessionsError,
  ListUserSessionsResponse,
  ListUsersResponse,
  PostAccountInfoData,
  PostAccountInfoError,
  PostAccountInfoResponse,
  PostAdminHasPermissionData,
  PostAdminHasPermissionError,
  PostAdminHasPermissionResponse,
  PostAdminStopImpersonatingData,
  PostAdminStopImpersonatingError,
  PostChangeEmailData,
  PostChangeEmailError,
  PostChangeEmailResponse,
  PostChangePasswordData,
  PostChangePasswordError,
  PostChangePasswordResponse,
  PostDeleteUserData,
  PostDeleteUserError,
  PostDeleteUserResponse,
  PostEmailOtpCheckVerificationOtpData,
  PostEmailOtpCheckVerificationOtpError,
  PostEmailOtpCheckVerificationOtpResponse,
  PostEmailOtpResetPasswordData,
  PostEmailOtpResetPasswordError,
  PostEmailOtpSendVerificationOtpData,
  PostEmailOtpSendVerificationOtpError,
  PostEmailOtpSendVerificationOtpResponse,
  PostEmailOtpVerifyEmailData,
  PostEmailOtpVerifyEmailError,
  PostEmailOtpVerifyEmailResponse,
  PostForgetPasswordData,
  PostForgetPasswordEmailOtpData,
  PostForgetPasswordEmailOtpError,
  PostForgetPasswordEmailOtpResponse,
  PostForgetPasswordError,
  PostForgetPasswordResponse,
  PostGetAccessTokenData,
  PostGetAccessTokenError,
  PostGetAccessTokenResponse,
  PostLinkSocialData,
  PostLinkSocialError,
  PostLinkSocialResponse,
  PostRefreshTokenData,
  PostRefreshTokenError,
  PostRefreshTokenResponse,
  PostRequestPasswordResetData,
  PostRequestPasswordResetError,
  PostRequestPasswordResetResponse,
  PostResetPasswordData,
  PostResetPasswordError,
  PostResetPasswordResponse,
  PostRevokeOtherSessionsData,
  PostRevokeOtherSessionsError,
  PostRevokeOtherSessionsResponse,
  PostRevokeSessionData,
  PostRevokeSessionError,
  PostRevokeSessionResponse,
  PostRevokeSessionsData,
  PostRevokeSessionsError,
  PostRevokeSessionsResponse,
  PostSendVerificationEmailData,
  PostSendVerificationEmailError,
  PostSendVerificationEmailResponse,
  PostSignInEmailData,
  PostSignInEmailError,
  PostSignInEmailOtpData,
  PostSignInEmailOtpError,
  PostSignInEmailOtpResponse,
  PostSignInEmailResponse,
  PostSignOutData,
  PostSignOutError,
  PostSignOutResponse,
  PostSignUpEmailData,
  PostSignUpEmailError,
  PostSignUpEmailResponse,
  PostUnlinkAccountData,
  PostUnlinkAccountError,
  PostUnlinkAccountResponse,
  PostUpdateUserData,
  PostUpdateUserError,
  PostUpdateUserResponse,
  RemoveUserData,
  RemoveUserError,
  RemoveUserResponse,
  RevokeUserSessionData,
  RevokeUserSessionError,
  RevokeUserSessionResponse,
  RevokeUserSessionsData,
  RevokeUserSessionsError,
  RevokeUserSessionsResponse,
  SetRoleData,
  SetRoleError,
  SetRoleResponse,
  SetUserPasswordData,
  SetUserPasswordError,
  SetUserPasswordResponse,
  SocialSignInData,
  SocialSignInError,
  SocialSignInResponse,
  UnbanUserData,
  UnbanUserError,
  UnbanUserResponse,
  UpdateUserData,
  UpdateUserError,
  UpdateUserResponse,
} from "../types.gen";

/**
 * Sign in with a social provider
 */
export const socialSignInMutation = (
  options?: Partial<Options<SocialSignInData>>,
): UseMutationOptions<
  SocialSignInResponse,
  SocialSignInError,
  Options<SocialSignInData>
> => {
  const mutationOptions: UseMutationOptions<
    SocialSignInResponse,
    SocialSignInError,
    Options<SocialSignInData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await socialSignIn({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getGetSessionQueryKey = (options?: Options<GetGetSessionData>) =>
  createQueryKey("getGetSession", options, false, ["Default"]);

/**
 * Get the current session
 */
export const getGetSessionOptions = (options?: Options<GetGetSessionData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGetSession({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getGetSessionQueryKey(options),
  });
};

/**
 * Sign out the current user
 */
export const postSignOutMutation = (
  options?: Partial<Options<PostSignOutData>>,
): UseMutationOptions<
  PostSignOutResponse,
  PostSignOutError,
  Options<PostSignOutData>
> => {
  const mutationOptions: UseMutationOptions<
    PostSignOutResponse,
    PostSignOutError,
    Options<PostSignOutData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postSignOut({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Sign up a user using email and password
 */
export const postSignUpEmailMutation = (
  options?: Partial<Options<PostSignUpEmailData>>,
): UseMutationOptions<
  PostSignUpEmailResponse,
  PostSignUpEmailError,
  Options<PostSignUpEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    PostSignUpEmailResponse,
    PostSignUpEmailError,
    Options<PostSignUpEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postSignUpEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Sign in with email and password
 */
export const postSignInEmailMutation = (
  options?: Partial<Options<PostSignInEmailData>>,
): UseMutationOptions<
  PostSignInEmailResponse,
  PostSignInEmailError,
  Options<PostSignInEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    PostSignInEmailResponse,
    PostSignInEmailError,
    Options<PostSignInEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postSignInEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Send a password reset email to the user
 */
export const postForgetPasswordMutation = (
  options?: Partial<Options<PostForgetPasswordData>>,
): UseMutationOptions<
  PostForgetPasswordResponse,
  PostForgetPasswordError,
  Options<PostForgetPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    PostForgetPasswordResponse,
    PostForgetPasswordError,
    Options<PostForgetPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postForgetPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reset the password for a user
 */
export const postResetPasswordMutation = (
  options?: Partial<Options<PostResetPasswordData>>,
): UseMutationOptions<
  PostResetPasswordResponse,
  PostResetPasswordError,
  Options<PostResetPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    PostResetPasswordResponse,
    PostResetPasswordError,
    Options<PostResetPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postResetPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getVerifyEmailQueryKey = (options: Options<GetVerifyEmailData>) =>
  createQueryKey("getVerifyEmail", options, false, ["Default"]);

/**
 * Verify the email of the user
 */
export const getVerifyEmailOptions = (options: Options<GetVerifyEmailData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getVerifyEmail({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getVerifyEmailQueryKey(options),
  });
};

/**
 * Send a verification email to the user
 */
export const postSendVerificationEmailMutation = (
  options?: Partial<Options<PostSendVerificationEmailData>>,
): UseMutationOptions<
  PostSendVerificationEmailResponse,
  PostSendVerificationEmailError,
  Options<PostSendVerificationEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    PostSendVerificationEmailResponse,
    PostSendVerificationEmailError,
    Options<PostSendVerificationEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postSendVerificationEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postChangeEmailMutation = (
  options?: Partial<Options<PostChangeEmailData>>,
): UseMutationOptions<
  PostChangeEmailResponse,
  PostChangeEmailError,
  Options<PostChangeEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    PostChangeEmailResponse,
    PostChangeEmailError,
    Options<PostChangeEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postChangeEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Change the password of the user
 */
export const postChangePasswordMutation = (
  options?: Partial<Options<PostChangePasswordData>>,
): UseMutationOptions<
  PostChangePasswordResponse,
  PostChangePasswordError,
  Options<PostChangePasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    PostChangePasswordResponse,
    PostChangePasswordError,
    Options<PostChangePasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postChangePassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update the current user
 */
export const postUpdateUserMutation = (
  options?: Partial<Options<PostUpdateUserData>>,
): UseMutationOptions<
  PostUpdateUserResponse,
  PostUpdateUserError,
  Options<PostUpdateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    PostUpdateUserResponse,
    PostUpdateUserError,
    Options<PostUpdateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postUpdateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete the user
 */
export const postDeleteUserMutation = (
  options?: Partial<Options<PostDeleteUserData>>,
): UseMutationOptions<
  PostDeleteUserResponse,
  PostDeleteUserError,
  Options<PostDeleteUserData>
> => {
  const mutationOptions: UseMutationOptions<
    PostDeleteUserResponse,
    PostDeleteUserError,
    Options<PostDeleteUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postDeleteUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getResetPasswordByTokenQueryKey = (
  options?: Options<GetResetPasswordByTokenData>,
) => createQueryKey("getResetPasswordByToken", options, false, ["Default"]);

/**
 * Redirects the user to the callback URL with the token
 */
export const getResetPasswordByTokenOptions = (
  options?: Options<GetResetPasswordByTokenData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getResetPasswordByToken({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getResetPasswordByTokenQueryKey(options),
  });
};

/**
 * Send a password reset email to the user
 */
export const postRequestPasswordResetMutation = (
  options?: Partial<Options<PostRequestPasswordResetData>>,
): UseMutationOptions<
  PostRequestPasswordResetResponse,
  PostRequestPasswordResetError,
  Options<PostRequestPasswordResetData>
> => {
  const mutationOptions: UseMutationOptions<
    PostRequestPasswordResetResponse,
    PostRequestPasswordResetError,
    Options<PostRequestPasswordResetData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postRequestPasswordReset({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getListSessionsQueryKey = (
  options?: Options<GetListSessionsData>,
) => createQueryKey("getListSessions", options, false, ["Default"]);

/**
 * List all active sessions for the user
 */
export const getListSessionsOptions = (
  options?: Options<GetListSessionsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getListSessions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getListSessionsQueryKey(options),
  });
};

/**
 * Revoke a single session
 */
export const postRevokeSessionMutation = (
  options?: Partial<Options<PostRevokeSessionData>>,
): UseMutationOptions<
  PostRevokeSessionResponse,
  PostRevokeSessionError,
  Options<PostRevokeSessionData>
> => {
  const mutationOptions: UseMutationOptions<
    PostRevokeSessionResponse,
    PostRevokeSessionError,
    Options<PostRevokeSessionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postRevokeSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Revoke all sessions for the user
 */
export const postRevokeSessionsMutation = (
  options?: Partial<Options<PostRevokeSessionsData>>,
): UseMutationOptions<
  PostRevokeSessionsResponse,
  PostRevokeSessionsError,
  Options<PostRevokeSessionsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostRevokeSessionsResponse,
    PostRevokeSessionsError,
    Options<PostRevokeSessionsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postRevokeSessions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Revoke all other sessions for the user except the current one
 */
export const postRevokeOtherSessionsMutation = (
  options?: Partial<Options<PostRevokeOtherSessionsData>>,
): UseMutationOptions<
  PostRevokeOtherSessionsResponse,
  PostRevokeOtherSessionsError,
  Options<PostRevokeOtherSessionsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostRevokeOtherSessionsResponse,
    PostRevokeOtherSessionsError,
    Options<PostRevokeOtherSessionsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postRevokeOtherSessions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Link a social account to the user
 */
export const postLinkSocialMutation = (
  options?: Partial<Options<PostLinkSocialData>>,
): UseMutationOptions<
  PostLinkSocialResponse,
  PostLinkSocialError,
  Options<PostLinkSocialData>
> => {
  const mutationOptions: UseMutationOptions<
    PostLinkSocialResponse,
    PostLinkSocialError,
    Options<PostLinkSocialData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postLinkSocial({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getListAccountsQueryKey = (
  options?: Options<GetListAccountsData>,
) => createQueryKey("getListAccounts", options, false, ["Default"]);

/**
 * List all accounts linked to the user
 */
export const getListAccountsOptions = (
  options?: Options<GetListAccountsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getListAccounts({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getListAccountsQueryKey(options),
  });
};

export const getDeleteUserCallbackQueryKey = (
  options?: Options<GetDeleteUserCallbackData>,
) => createQueryKey("getDeleteUserCallback", options, false, ["Default"]);

/**
 * Callback to complete user deletion with verification token
 */
export const getDeleteUserCallbackOptions = (
  options?: Options<GetDeleteUserCallbackData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDeleteUserCallback({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDeleteUserCallbackQueryKey(options),
  });
};

/**
 * Unlink an account
 */
export const postUnlinkAccountMutation = (
  options?: Partial<Options<PostUnlinkAccountData>>,
): UseMutationOptions<
  PostUnlinkAccountResponse,
  PostUnlinkAccountError,
  Options<PostUnlinkAccountData>
> => {
  const mutationOptions: UseMutationOptions<
    PostUnlinkAccountResponse,
    PostUnlinkAccountError,
    Options<PostUnlinkAccountData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postUnlinkAccount({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Refresh the access token using a refresh token
 */
export const postRefreshTokenMutation = (
  options?: Partial<Options<PostRefreshTokenData>>,
): UseMutationOptions<
  PostRefreshTokenResponse,
  PostRefreshTokenError,
  Options<PostRefreshTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    PostRefreshTokenResponse,
    PostRefreshTokenError,
    Options<PostRefreshTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postRefreshToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Get a valid access token, doing a refresh if needed
 */
export const postGetAccessTokenMutation = (
  options?: Partial<Options<PostGetAccessTokenData>>,
): UseMutationOptions<
  PostGetAccessTokenResponse,
  PostGetAccessTokenError,
  Options<PostGetAccessTokenData>
> => {
  const mutationOptions: UseMutationOptions<
    PostGetAccessTokenResponse,
    PostGetAccessTokenError,
    Options<PostGetAccessTokenData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postGetAccessToken({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Get the account info provided by the provider
 */
export const postAccountInfoMutation = (
  options?: Partial<Options<PostAccountInfoData>>,
): UseMutationOptions<
  PostAccountInfoResponse,
  PostAccountInfoError,
  Options<PostAccountInfoData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAccountInfoResponse,
    PostAccountInfoError,
    Options<PostAccountInfoData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAccountInfo({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getOkQueryKey = (options?: Options<GetOkData>) =>
  createQueryKey("getOk", options, false, ["Default"]);

/**
 * Check if the API is working
 */
export const getOkOptions = (options?: Options<GetOkData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getOk({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getOkQueryKey(options),
  });
};

export const getErrorQueryKey = (options?: Options<GetErrorData>) =>
  createQueryKey("getError", options, false, ["Default"]);

/**
 * Displays an error page
 */
export const getErrorOptions = (options?: Options<GetErrorData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getError({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getErrorQueryKey(options),
  });
};

/**
 * Send verification OTP
 */
export const postEmailOtpSendVerificationOtpMutation = (
  options?: Partial<Options<PostEmailOtpSendVerificationOtpData>>,
): UseMutationOptions<
  PostEmailOtpSendVerificationOtpResponse,
  PostEmailOtpSendVerificationOtpError,
  Options<PostEmailOtpSendVerificationOtpData>
> => {
  const mutationOptions: UseMutationOptions<
    PostEmailOtpSendVerificationOtpResponse,
    PostEmailOtpSendVerificationOtpError,
    Options<PostEmailOtpSendVerificationOtpData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postEmailOtpSendVerificationOtp({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Check if a verification OTP is valid
 */
export const postEmailOtpCheckVerificationOtpMutation = (
  options?: Partial<Options<PostEmailOtpCheckVerificationOtpData>>,
): UseMutationOptions<
  PostEmailOtpCheckVerificationOtpResponse,
  PostEmailOtpCheckVerificationOtpError,
  Options<PostEmailOtpCheckVerificationOtpData>
> => {
  const mutationOptions: UseMutationOptions<
    PostEmailOtpCheckVerificationOtpResponse,
    PostEmailOtpCheckVerificationOtpError,
    Options<PostEmailOtpCheckVerificationOtpData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postEmailOtpCheckVerificationOtp({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Verify email with OTP
 */
export const postEmailOtpVerifyEmailMutation = (
  options?: Partial<Options<PostEmailOtpVerifyEmailData>>,
): UseMutationOptions<
  PostEmailOtpVerifyEmailResponse,
  PostEmailOtpVerifyEmailError,
  Options<PostEmailOtpVerifyEmailData>
> => {
  const mutationOptions: UseMutationOptions<
    PostEmailOtpVerifyEmailResponse,
    PostEmailOtpVerifyEmailError,
    Options<PostEmailOtpVerifyEmailData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postEmailOtpVerifyEmail({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Sign in with OTP
 */
export const postSignInEmailOtpMutation = (
  options?: Partial<Options<PostSignInEmailOtpData>>,
): UseMutationOptions<
  PostSignInEmailOtpResponse,
  PostSignInEmailOtpError,
  Options<PostSignInEmailOtpData>
> => {
  const mutationOptions: UseMutationOptions<
    PostSignInEmailOtpResponse,
    PostSignInEmailOtpError,
    Options<PostSignInEmailOtpData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postSignInEmailOtp({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Send a password reset OTP to the user
 */
export const postForgetPasswordEmailOtpMutation = (
  options?: Partial<Options<PostForgetPasswordEmailOtpData>>,
): UseMutationOptions<
  PostForgetPasswordEmailOtpResponse,
  PostForgetPasswordEmailOtpError,
  Options<PostForgetPasswordEmailOtpData>
> => {
  const mutationOptions: UseMutationOptions<
    PostForgetPasswordEmailOtpResponse,
    PostForgetPasswordEmailOtpError,
    Options<PostForgetPasswordEmailOtpData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postForgetPasswordEmailOtp({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Reset user password with OTP
 */
export const postEmailOtpResetPasswordMutation = (
  options?: Partial<Options<PostEmailOtpResetPasswordData>>,
): UseMutationOptions<
  unknown,
  PostEmailOtpResetPasswordError,
  Options<PostEmailOtpResetPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PostEmailOtpResetPasswordError,
    Options<PostEmailOtpResetPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postEmailOtpResetPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Set the role of a user
 */
export const setRoleMutation = (
  options?: Partial<Options<SetRoleData>>,
): UseMutationOptions<SetRoleResponse, SetRoleError, Options<SetRoleData>> => {
  const mutationOptions: UseMutationOptions<
    SetRoleResponse,
    SetRoleError,
    Options<SetRoleData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setRole({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getUserQueryKey = (options?: Options<GetUserData>) =>
  createQueryKey("getUser", options, false, ["Admin"]);

/**
 * Get an existing user
 */
export const getUserOptions = (options?: Options<GetUserData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getUserQueryKey(options),
  });
};

/**
 * Create a new user
 */
export const createUserMutation = (
  options?: Partial<Options<CreateUserData>>,
): UseMutationOptions<
  CreateUserResponse,
  CreateUserError,
  Options<CreateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateUserResponse,
    CreateUserError,
    Options<CreateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update a user's details
 */
export const updateUserMutation = (
  options?: Partial<Options<UpdateUserData>>,
): UseMutationOptions<
  UpdateUserResponse,
  UpdateUserError,
  Options<UpdateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateUserResponse,
    UpdateUserError,
    Options<UpdateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listUsersQueryKey = (options?: Options<ListUsersData>) =>
  createQueryKey("listUsers", options, false, ["Admin"]);

/**
 * List users
 */
export const listUsersOptions = (options?: Options<ListUsersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listUsersQueryKey(options),
  });
};

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = {
    ...queryKey[0],
  };
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    };
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    };
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    };
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    };
  }
  return params as unknown as typeof page;
};

export const listUsersInfiniteQueryKey = (
  options?: Options<ListUsersData>,
): QueryKey<Options<ListUsersData>> =>
  createQueryKey("listUsers", options, true, ["Admin"]);

/**
 * List users
 */
export const listUsersInfiniteOptions = (options?: Options<ListUsersData>) => {
  return infiniteQueryOptions<
    ListUsersResponse,
    ListUsersError,
    InfiniteData<ListUsersResponse>,
    QueryKey<Options<ListUsersData>>,
    | string
    | Pick<
        QueryKey<Options<ListUsersData>>[0],
        "body" | "headers" | "path" | "query"
      >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListUsersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  offset: pageParam,
                },
              };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        });
        return data;
      },
      queryKey: listUsersInfiniteQueryKey(options),
    },
  );
};

/**
 * List user sessions
 */
export const listUserSessionsMutation = (
  options?: Partial<Options<ListUserSessionsData>>,
): UseMutationOptions<
  ListUserSessionsResponse,
  ListUserSessionsError,
  Options<ListUserSessionsData>
> => {
  const mutationOptions: UseMutationOptions<
    ListUserSessionsResponse,
    ListUserSessionsError,
    Options<ListUserSessionsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await listUserSessions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Unban a user
 */
export const unbanUserMutation = (
  options?: Partial<Options<UnbanUserData>>,
): UseMutationOptions<
  UnbanUserResponse,
  UnbanUserError,
  Options<UnbanUserData>
> => {
  const mutationOptions: UseMutationOptions<
    UnbanUserResponse,
    UnbanUserError,
    Options<UnbanUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await unbanUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Ban a user
 */
export const banUserMutation = (
  options?: Partial<Options<BanUserData>>,
): UseMutationOptions<BanUserResponse, BanUserError, Options<BanUserData>> => {
  const mutationOptions: UseMutationOptions<
    BanUserResponse,
    BanUserError,
    Options<BanUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await banUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Impersonate a user
 */
export const impersonateUserMutation = (
  options?: Partial<Options<ImpersonateUserData>>,
): UseMutationOptions<
  ImpersonateUserResponse,
  ImpersonateUserError,
  Options<ImpersonateUserData>
> => {
  const mutationOptions: UseMutationOptions<
    ImpersonateUserResponse,
    ImpersonateUserError,
    Options<ImpersonateUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await impersonateUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postAdminStopImpersonatingMutation = (
  options?: Partial<Options<PostAdminStopImpersonatingData>>,
): UseMutationOptions<
  unknown,
  PostAdminStopImpersonatingError,
  Options<PostAdminStopImpersonatingData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    PostAdminStopImpersonatingError,
    Options<PostAdminStopImpersonatingData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAdminStopImpersonating({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Revoke a user session
 */
export const revokeUserSessionMutation = (
  options?: Partial<Options<RevokeUserSessionData>>,
): UseMutationOptions<
  RevokeUserSessionResponse,
  RevokeUserSessionError,
  Options<RevokeUserSessionData>
> => {
  const mutationOptions: UseMutationOptions<
    RevokeUserSessionResponse,
    RevokeUserSessionError,
    Options<RevokeUserSessionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await revokeUserSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Revoke all user sessions
 */
export const revokeUserSessionsMutation = (
  options?: Partial<Options<RevokeUserSessionsData>>,
): UseMutationOptions<
  RevokeUserSessionsResponse,
  RevokeUserSessionsError,
  Options<RevokeUserSessionsData>
> => {
  const mutationOptions: UseMutationOptions<
    RevokeUserSessionsResponse,
    RevokeUserSessionsError,
    Options<RevokeUserSessionsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await revokeUserSessions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete a user and all their sessions and accounts. Cannot be undone.
 */
export const removeUserMutation = (
  options?: Partial<Options<RemoveUserData>>,
): UseMutationOptions<
  RemoveUserResponse,
  RemoveUserError,
  Options<RemoveUserData>
> => {
  const mutationOptions: UseMutationOptions<
    RemoveUserResponse,
    RemoveUserError,
    Options<RemoveUserData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await removeUser({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Set a user's password
 */
export const setUserPasswordMutation = (
  options?: Partial<Options<SetUserPasswordData>>,
): UseMutationOptions<
  SetUserPasswordResponse,
  SetUserPasswordError,
  Options<SetUserPasswordData>
> => {
  const mutationOptions: UseMutationOptions<
    SetUserPasswordResponse,
    SetUserPasswordError,
    Options<SetUserPasswordData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await setUserPassword({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Check if the user has permission
 */
export const postAdminHasPermissionMutation = (
  options?: Partial<Options<PostAdminHasPermissionData>>,
): UseMutationOptions<
  PostAdminHasPermissionResponse,
  PostAdminHasPermissionError,
  Options<PostAdminHasPermissionData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAdminHasPermissionResponse,
    PostAdminHasPermissionError,
    Options<PostAdminHasPermissionData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAdminHasPermission({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
