export const envs = {
  VITE_BASE_URL: import.meta.env.VITE_BASE_URL,
  VITE_BASE_API_URL: import.meta.env.VITE_BASE_API_URL,
  VITE_GLITCHTIP_DSN: import.meta.env.VITE_GLITCHTIP_DSN,
  VITE_GLITCHTIP_ENVIRONMENT: import.meta.env.VITE_GLITCHTIP_ENVIRONMENT,
  VITE_GLITCHTIP_RELEASE: import.meta.env.VITE_GLITCHTIP_RELEASE,
  VITE_YANDEX_METRIKA_ID: import.meta.env.VITE_YANDEX_METRIKA_ID,
  MODE: import.meta.env.MODE,
};
