/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./../../routes/__root";
import { Route as AuthRouteRouteImport } from "./../../routes/_auth/route";
import { Route as AppRouteRouteImport } from "./../../routes/_app/route";
import { Route as AppIndexRouteImport } from "./../../routes/_app/index";
import { Route as AuthVerifyOtpRouteImport } from "./../../routes/_auth/verify-otp";
import { Route as AuthSignInRouteImport } from "./../../routes/_auth/sign-in";
import { Route as AppProfilesRouteImport } from "./../../routes/_app/profiles";
import { Route as AppArchiveRouteImport } from "./../../routes/_app/archive";
import { Route as AppSettingsBillingRouteImport } from "./../../routes/_app/settings/billing";
import { Route as AppSettingsAccountRouteImport } from "./../../routes/_app/settings/account";
import { Route as AppScenariosSettingsRouteImport } from "./../../routes/_app/scenarios/settings";
import { Route as AppScenariosScenarioIdRouteImport } from "./../../routes/_app/scenarios/$scenarioId";
import { Route as AppIdeasListsSettingsRouteImport } from "./../../routes/_app/ideas-lists/settings";
import { Route as AppIdeasListsIdeasListIdRouteImport } from "./../../routes/_app/ideas-lists/$ideasListId";

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRouteRoute = AppRouteRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRouteRoute,
} as any);
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: "/verify-otp",
  path: "/verify-otp",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AppProfilesRoute = AppProfilesRouteImport.update({
  id: "/profiles",
  path: "/profiles",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: "/archive",
  path: "/archive",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: "/settings/billing",
  path: "/settings/billing",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: "/settings/account",
  path: "/settings/account",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppScenariosSettingsRoute = AppScenariosSettingsRouteImport.update({
  id: "/scenarios/settings",
  path: "/scenarios/settings",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppScenariosScenarioIdRoute = AppScenariosScenarioIdRouteImport.update({
  id: "/scenarios/$scenarioId",
  path: "/scenarios/$scenarioId",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppIdeasListsSettingsRoute = AppIdeasListsSettingsRouteImport.update({
  id: "/ideas-lists/settings",
  path: "/ideas-lists/settings",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppIdeasListsIdeasListIdRoute =
  AppIdeasListsIdeasListIdRouteImport.update({
    id: "/ideas-lists/$ideasListId",
    path: "/ideas-lists/$ideasListId",
    getParentRoute: () => AppRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/archive": typeof AppArchiveRoute;
  "/profiles": typeof AppProfilesRoute;
  "/sign-in": typeof AuthSignInRoute;
  "/verify-otp": typeof AuthVerifyOtpRoute;
  "/": typeof AppIndexRoute;
  "/ideas-lists/$ideasListId": typeof AppIdeasListsIdeasListIdRoute;
  "/ideas-lists/settings": typeof AppIdeasListsSettingsRoute;
  "/scenarios/$scenarioId": typeof AppScenariosScenarioIdRoute;
  "/scenarios/settings": typeof AppScenariosSettingsRoute;
  "/settings/account": typeof AppSettingsAccountRoute;
  "/settings/billing": typeof AppSettingsBillingRoute;
}
export interface FileRoutesByTo {
  "/archive": typeof AppArchiveRoute;
  "/profiles": typeof AppProfilesRoute;
  "/sign-in": typeof AuthSignInRoute;
  "/verify-otp": typeof AuthVerifyOtpRoute;
  "/": typeof AppIndexRoute;
  "/ideas-lists/$ideasListId": typeof AppIdeasListsIdeasListIdRoute;
  "/ideas-lists/settings": typeof AppIdeasListsSettingsRoute;
  "/scenarios/$scenarioId": typeof AppScenariosScenarioIdRoute;
  "/scenarios/settings": typeof AppScenariosSettingsRoute;
  "/settings/account": typeof AppSettingsAccountRoute;
  "/settings/billing": typeof AppSettingsBillingRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_app": typeof AppRouteRouteWithChildren;
  "/_auth": typeof AuthRouteRouteWithChildren;
  "/_app/archive": typeof AppArchiveRoute;
  "/_app/profiles": typeof AppProfilesRoute;
  "/_auth/sign-in": typeof AuthSignInRoute;
  "/_auth/verify-otp": typeof AuthVerifyOtpRoute;
  "/_app/": typeof AppIndexRoute;
  "/_app/ideas-lists/$ideasListId": typeof AppIdeasListsIdeasListIdRoute;
  "/_app/ideas-lists/settings": typeof AppIdeasListsSettingsRoute;
  "/_app/scenarios/$scenarioId": typeof AppScenariosScenarioIdRoute;
  "/_app/scenarios/settings": typeof AppScenariosSettingsRoute;
  "/_app/settings/account": typeof AppSettingsAccountRoute;
  "/_app/settings/billing": typeof AppSettingsBillingRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/archive"
    | "/profiles"
    | "/sign-in"
    | "/verify-otp"
    | "/"
    | "/ideas-lists/$ideasListId"
    | "/ideas-lists/settings"
    | "/scenarios/$scenarioId"
    | "/scenarios/settings"
    | "/settings/account"
    | "/settings/billing";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/archive"
    | "/profiles"
    | "/sign-in"
    | "/verify-otp"
    | "/"
    | "/ideas-lists/$ideasListId"
    | "/ideas-lists/settings"
    | "/scenarios/$scenarioId"
    | "/scenarios/settings"
    | "/settings/account"
    | "/settings/billing";
  id:
    | "__root__"
    | "/_app"
    | "/_auth"
    | "/_app/archive"
    | "/_app/profiles"
    | "/_auth/sign-in"
    | "/_auth/verify-otp"
    | "/_app/"
    | "/_app/ideas-lists/$ideasListId"
    | "/_app/ideas-lists/settings"
    | "/_app/scenarios/$scenarioId"
    | "/_app/scenarios/settings"
    | "/_app/settings/account"
    | "/_app/settings/billing";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AppRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_auth/verify-otp": {
      id: "/_auth/verify-otp";
      path: "/verify-otp";
      fullPath: "/verify-otp";
      preLoaderRoute: typeof AuthVerifyOtpRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/sign-in": {
      id: "/_auth/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof AuthSignInRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_app/profiles": {
      id: "/_app/profiles";
      path: "/profiles";
      fullPath: "/profiles";
      preLoaderRoute: typeof AppProfilesRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/archive": {
      id: "/_app/archive";
      path: "/archive";
      fullPath: "/archive";
      preLoaderRoute: typeof AppArchiveRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/settings/billing": {
      id: "/_app/settings/billing";
      path: "/settings/billing";
      fullPath: "/settings/billing";
      preLoaderRoute: typeof AppSettingsBillingRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/settings/account": {
      id: "/_app/settings/account";
      path: "/settings/account";
      fullPath: "/settings/account";
      preLoaderRoute: typeof AppSettingsAccountRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/scenarios/settings": {
      id: "/_app/scenarios/settings";
      path: "/scenarios/settings";
      fullPath: "/scenarios/settings";
      preLoaderRoute: typeof AppScenariosSettingsRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/scenarios/$scenarioId": {
      id: "/_app/scenarios/$scenarioId";
      path: "/scenarios/$scenarioId";
      fullPath: "/scenarios/$scenarioId";
      preLoaderRoute: typeof AppScenariosScenarioIdRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/ideas-lists/settings": {
      id: "/_app/ideas-lists/settings";
      path: "/ideas-lists/settings";
      fullPath: "/ideas-lists/settings";
      preLoaderRoute: typeof AppIdeasListsSettingsRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/ideas-lists/$ideasListId": {
      id: "/_app/ideas-lists/$ideasListId";
      path: "/ideas-lists/$ideasListId";
      fullPath: "/ideas-lists/$ideasListId";
      preLoaderRoute: typeof AppIdeasListsIdeasListIdRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
  }
}

interface AppRouteRouteChildren {
  AppArchiveRoute: typeof AppArchiveRoute;
  AppProfilesRoute: typeof AppProfilesRoute;
  AppIndexRoute: typeof AppIndexRoute;
  AppIdeasListsIdeasListIdRoute: typeof AppIdeasListsIdeasListIdRoute;
  AppIdeasListsSettingsRoute: typeof AppIdeasListsSettingsRoute;
  AppScenariosScenarioIdRoute: typeof AppScenariosScenarioIdRoute;
  AppScenariosSettingsRoute: typeof AppScenariosSettingsRoute;
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute;
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppArchiveRoute: AppArchiveRoute,
  AppProfilesRoute: AppProfilesRoute,
  AppIndexRoute: AppIndexRoute,
  AppIdeasListsIdeasListIdRoute: AppIdeasListsIdeasListIdRoute,
  AppIdeasListsSettingsRoute: AppIdeasListsSettingsRoute,
  AppScenariosScenarioIdRoute: AppScenariosScenarioIdRoute,
  AppScenariosSettingsRoute: AppScenariosSettingsRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
);

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute;
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
