/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

import { sessionSchema } from "./session-schema.ts";

/**
 * @description Success
 */
export const getListSessions200Schema = z.array(z.lazy(() => sessionSchema));

/**
 * @description Bad Request. Usually due to missing parameters, or invalid parameters.
 */
export const getListSessions400Schema = z.object({
  message: z.string(),
});

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export const getListSessions401Schema = z.object({
  message: z.string(),
});

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export const getListSessions403Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Not Found. The requested resource was not found.
 */
export const getListSessions404Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export const getListSessions429Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export const getListSessions500Schema = z.object({
  message: z.optional(z.string()),
});

export const getListSessionsQueryResponseSchema = z.lazy(
  () => getListSessions200Schema,
);
