/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Success
 */
export const postAdminHasPermission200Schema = z.object({
  error: z.optional(z.string()),
  success: z.boolean(),
});

/**
 * @description Bad Request. Usually due to missing parameters, or invalid parameters.
 */
export const postAdminHasPermission400Schema = z.object({
  message: z.string(),
});

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export const postAdminHasPermission401Schema = z.object({
  message: z.string(),
});

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export const postAdminHasPermission403Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Not Found. The requested resource was not found.
 */
export const postAdminHasPermission404Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export const postAdminHasPermission429Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export const postAdminHasPermission500Schema = z.object({
  message: z.optional(z.string()),
});

export const postAdminHasPermissionMutationRequestSchema = z.object({
  permission: z.optional(z.object({}).describe("The permission to check")),
  permissions: z.object({}).describe("The permission to check"),
});

export const postAdminHasPermissionMutationResponseSchema = z.lazy(
  () => postAdminHasPermission200Schema,
);
