/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Success - Returns either session details or redirect URL
 */
export const postSignInEmail200Schema = z
  .object({
    redirect: z.literal(false),
    token: z.string().describe("Session token"),
    url: z.null().nullish(),
    user: z.object({
      id: z.string(),
      email: z.string(),
      name: z.string().nullish(),
      image: z.string().nullish(),
      emailVerified: z.boolean(),
      createdAt: z.iso.datetime(),
      updatedAt: z.iso.datetime(),
    }),
  })
  .describe("Session response when idToken is provided");

/**
 * @description Bad Request. Usually due to missing parameters, or invalid parameters.
 */
export const postSignInEmail400Schema = z.object({
  message: z.string(),
});

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export const postSignInEmail401Schema = z.object({
  message: z.string(),
});

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export const postSignInEmail403Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Not Found. The requested resource was not found.
 */
export const postSignInEmail404Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export const postSignInEmail429Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export const postSignInEmail500Schema = z.object({
  message: z.optional(z.string()),
});

export const postSignInEmailMutationRequestSchema = z.object({
  email: z.string().describe("Email of the user"),
  password: z.string().describe("Password of the user"),
  callbackURL: z
    .string()
    .describe("Callback URL to use as a redirect for email verification")
    .nullish(),
  rememberMe: z.string().nullish(),
});

export const postSignInEmailMutationResponseSchema = z.lazy(
  () => postSignInEmail200Schema,
);
