/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description User deletion processed successfully
 */
export const postDeleteUser200Schema = z.object({
  success: z.boolean().describe("Indicates if the operation was successful"),
  message: z
    .enum(["User deleted", "Verification email sent"])
    .describe("Status message of the deletion process"),
});

/**
 * @description Bad Request. Usually due to missing parameters, or invalid parameters.
 */
export const postDeleteUser400Schema = z.object({
  message: z.string(),
});

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export const postDeleteUser401Schema = z.object({
  message: z.string(),
});

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export const postDeleteUser403Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Not Found. The requested resource was not found.
 */
export const postDeleteUser404Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export const postDeleteUser429Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export const postDeleteUser500Schema = z.object({
  message: z.optional(z.string()),
});

export const postDeleteUserMutationRequestSchema = z.object({
  callbackURL: z
    .string()
    .describe("The callback URL to redirect to after the user is deleted")
    .nullish(),
  password: z
    .string()
    .describe("The password of the user is required to delete the user")
    .nullish(),
  token: z
    .string()
    .describe("The token to delete the user is required")
    .nullish(),
});

export const postDeleteUserMutationResponseSchema = z.lazy(
  () => postDeleteUser200Schema,
);
