/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

/**
 * @description Success
 */
export const postAccountInfo200Schema = z.object({
  user: z.object({
    id: z.string(),
    name: z.optional(z.string()),
    email: z.optional(z.string()),
    image: z.optional(z.string()),
    emailVerified: z.boolean(),
  }),
  data: z.object({}).catchall(z.any()),
});

/**
 * @description Bad Request. Usually due to missing parameters, or invalid parameters.
 */
export const postAccountInfo400Schema = z.object({
  message: z.string(),
});

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export const postAccountInfo401Schema = z.object({
  message: z.string(),
});

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export const postAccountInfo403Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Not Found. The requested resource was not found.
 */
export const postAccountInfo404Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export const postAccountInfo429Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export const postAccountInfo500Schema = z.object({
  message: z.optional(z.string()),
});

export const postAccountInfoMutationRequestSchema = z.object({
  accountId: z
    .string()
    .describe(
      "The provider given account id for which to get the account info",
    ),
});

export const postAccountInfoMutationResponseSchema = z.lazy(
  () => postAccountInfo200Schema,
);
