/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Success
 */
export const postLinkSocial200Schema = z.object({
  url: z.optional(
    z.string().describe("The authorization URL to redirect the user to"),
  ),
  redirect: z
    .boolean()
    .describe(
      "Indicates if the user should be redirected to the authorization URL",
    ),
  status: z.optional(z.boolean()),
});

/**
 * @description Bad Request. Usually due to missing parameters, or invalid parameters.
 */
export const postLinkSocial400Schema = z.object({
  message: z.string(),
});

/**
 * @description Unauthorized. Due to missing or invalid authentication.
 */
export const postLinkSocial401Schema = z.object({
  message: z.string(),
});

/**
 * @description Forbidden. You do not have permission to access this resource or to perform this action.
 */
export const postLinkSocial403Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Not Found. The requested resource was not found.
 */
export const postLinkSocial404Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Too Many Requests. You have exceeded the rate limit. Try again later.
 */
export const postLinkSocial429Schema = z.object({
  message: z.optional(z.string()),
});

/**
 * @description Internal Server Error. This is a problem with the server that you cannot fix.
 */
export const postLinkSocial500Schema = z.object({
  message: z.optional(z.string()),
});

export const postLinkSocialMutationRequestSchema = z.object({
  callbackURL: z
    .string()
    .describe("The URL to redirect to after the user has signed in")
    .nullish(),
  provider: z.string(),
  idToken: z
    .object({
      token: z.string(),
      nonce: z.string().nullish(),
      accessToken: z.string().nullish(),
      refreshToken: z.string().nullish(),
      scopes: z.array(z.any()).nullish(),
    })
    .nullish(),
  requestSignUp: z.boolean().nullish(),
  scopes: z
    .array(z.any())
    .describe("Additional scopes to request from the provider")
    .nullish(),
  errorCallbackURL: z
    .string()
    .describe(
      "The URL to redirect to if there is an error during the link process",
    )
    .nullish(),
  disableRedirect: z
    .boolean()
    .describe(
      "Disable automatic redirection to the provider. Useful for handling the redirection yourself",
    )
    .nullish(),
});

export const postLinkSocialMutationResponseSchema = z.lazy(
  () => postLinkSocial200Schema,
);
