/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const verificationSchema = z.object({
  id: z.optional(z.string()),
  identifier: z.string(),
  value: z.string(),
  expiresAt: z.string(),
  createdAt: z.string().default("Generated at runtime"),
  updatedAt: z.string().default("Generated at runtime"),
});
