/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Add payment method body
 * @description Add payment method body description
 */
export type AddPaymentMethodBodySchema = {
  /**
   * @type string | undefined
   */
  redirectPath?: string;
};
