/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Application
 * @description Application description
 */
export type ApplicationSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  email: string;
  comment: string | null;
  /**
   * @type boolean
   */
  marketingAccepted: boolean;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
