/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { IdeasListExtendedSchema } from "./ideas-list-extended-schema.ts";

/**
 * Archive ideas list
 * @description Archive ideas list description
 */
export type ArchiveIdeasListSchema = {
  /**
   * @type string
   */
  entity: "ideasList";
  /**
   * @description Ideas list extended description
   * @type object
   */
  data: IdeasListExtendedSchema;
};
