/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SubscriptionSchema } from "./subscription-schema.ts";

/**
 * Cancel subscription response
 * @description Cancel subscription response description
 */
export type CancelSubscriptionResponseSchema = {
  /**
   * @description Subscription description
   * @type object
   */
  data: SubscriptionSchema;
};
