/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const changeEmailResponseSchemaMessageEnum = {
  "Email updated": "Email updated",
  "Verification email sent": "Verification email sent",
} as const;

export type ChangeEmailResponseSchemaMessageEnumKey =
  (typeof changeEmailResponseSchemaMessageEnum)[keyof typeof changeEmailResponseSchemaMessageEnum];

/**
 * Change email response
 * @description Change email response description
 */
export type ChangeEmailResponseSchema = {
  /**
   * @type boolean
   */
  status: boolean;
  message?: ChangeEmailResponseSchemaMessageEnumKey | null;
};
