/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const createProfileAttachmentBodySchemaTypeEnum = {
  "actor-reference": "actor-reference",
  "thumbnail-reference": "thumbnail-reference",
  "video-reference": "video-reference",
} as const;

export type CreateProfileAttachmentBodySchemaTypeEnumKey =
  (typeof createProfileAttachmentBodySchemaTypeEnum)[keyof typeof createProfileAttachmentBodySchemaTypeEnum];

/**
 * Create profile attachment body
 * @description Create profile attachment body description
 */
export type CreateProfileAttachmentBodySchema = {
  /**
   * @minLength 1
   * @type string, binary
   */
  file: Blob;
  /**
   * @type string
   */
  type: CreateProfileAttachmentBodySchemaTypeEnumKey;
};
