/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Create application body
 * @description Create application body description
 */
export type CreateApplicationBodySchema = {
  /**
   * @type string, email
   */
  email: string;
  /**
   * @type array | undefined
   */
  featureIds?: string[];
  /**
   * @maxLength 4096
   * @type string | undefined
   */
  comment?: string;
  /**
   * @default false
   * @type boolean | undefined
   */
  marketingAccepted?: boolean;
};
