/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Create ideas list body
 * @description Create ideas list body description
 */
export type CreateIdeasListBodySchema = {
  templateId?: string | null;
  profileId?: string | null;
  name?: string | null;
  description?: string | null;
  targetAudience?: string | null;
  /**
   * @type array | undefined
   */
  toneIds?: string[];
  /**
   * @type array | undefined
   */
  videoTypeIds?: string[];
};
