/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Create profile body
 * @description Create profile body description
 */
export type CreateProfileBodySchema = {
  /**
   * @minLength 1
   * @maxLength 256
   * @type string
   */
  name: string;
  /**
   * @maxLength 8192
   * @type string | undefined
   */
  positioning?: string;
  /**
   * @maxLength 1024
   * @type string | undefined
   */
  targetAudience?: string;
  /**
   * @maxLength 8192
   * @type string | undefined
   */
  additionalInfo?: string;
  /**
   * @type string, uuid
   */
  typeId: string;
  /**
   * @type array | undefined
   */
  platformIds?: string[];
};
