/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProfileChannelVideoSchema } from "./profile-channel-video-schema.ts";

/**
 * Create profile channel video response
 * @description Create profile channel video response description
 */
export type CreateProfileChannelVideoResponseSchema = {
  /**
   * @description Profile channel video description
   * @type object
   */
  data: ProfileChannelVideoSchema;
};
