/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProfileChannelUrlValidationSchema } from "./profile-channel-url-validation-schema.ts";

/**
 * Create profiles from channels error
 * @description Create profiles from channels error description
 */
export type CreateProfilesFromChannelsErrorSchema = {
  /**
   * @type array
   */
  data: ProfileChannelUrlValidationSchema[];
};
