/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Create profile channel video body
 * @description Create profile channel video body description
 */
export type CreateProfileChannelVideoBodySchema = {
  /**
   * @type string, uuid
   */
  profileId: string;
  /**
   * @type string, uri
   */
  url: string;
};
