/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Credits package
 * @description Credits package description
 */
export type CreditsPackageSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  description: string | null;
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  amount: number;
  /**
   * @minLength -8388608
   * @maxLength 8388607
   * @type number
   */
  price: number;
  oldPrice: number | null;
  /**
   * @type boolean
   */
  forPurchase: boolean;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
