/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreditsBatchSchema } from "./credits-batch-schema.ts";

export const creditsUsageExtendedSchemaEntityEnum = {
  "ideas-list": "ideas-list",
  "scenario-chapters": "scenario-chapters",
  "scenario-chapter-scenes": "scenario-chapter-scenes",
  "scenario-scene-preview": "scenario-scene-preview",
  "scenario-metadata": "scenario-metadata",
  "scenario-metadata-item": "scenario-metadata-item",
} as const;

export type CreditsUsageExtendedSchemaEntityEnumKey =
  (typeof creditsUsageExtendedSchemaEntityEnum)[keyof typeof creditsUsageExtendedSchemaEntityEnum];

/**
 * Credits usage extended
 * @description Credits usage extended description
 */
export type CreditsUsageExtendedSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  /**
   * @type string, uuid
   */
  batchId: string;
  /**
   * @type string
   */
  entity: CreditsUsageExtendedSchemaEntityEnumKey;
  /**
   * @type string, uuid
   */
  entityId: string;
  /**
   * @minLength -8388608
   * @maxLength 8388607
   * @type number
   */
  creditsAmount: number;
  /**
   * @minLength -8388608
   * @maxLength 8388607
   * @type number
   */
  tokensPerCredit: number;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
  /**
   * @description Credits batch description
   * @type object
   */
  batch: CreditsBatchSchema;
};
