/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProfileChannelVideoSchema } from "./profile-channel-video-schema.ts";

/**
 * Delete profile channel video response
 * @description Delete profile channel video response description
 */
export type DeleteProfileChannelVideoResponseSchema = {
  /**
   * @description Profile channel video description
   * @type object
   */
  data: ProfileChannelVideoSchema;
};
