/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteApiV1ScenariosScenarioIdPathParams = {
  /**
   * @type string, uuid
   */
  scenarioId: string;
};

/**
 * @description Scenario deleted successfully
 */
export type DeleteApiV1ScenariosScenarioId200 = {
  /**
   * @type object
   */
  data: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    userId: string;
    currentVersionId: string | null;
    profileId: string | null;
    templateId: string | null;
    platformId: string | null;
    videoTypeId: string | null;
    videoDurationId: string | null;
    /**
     * @type boolean
     */
    saved: boolean;
    name: string | null;
    description: string | null;
    targetAudience: string | null;
    /**
     * @type string
     */
    createdAt: string;
    /**
     * @type string
     */
    updatedAt: string;
  };
};

/**
 * Bad request response
 * @description Bad request
 */
export type DeleteApiV1ScenariosScenarioId400 = string;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type DeleteApiV1ScenariosScenarioId401 = string;

/**
 * Forbidden response
 * @description Forbidden
 */
export type DeleteApiV1ScenariosScenarioId403 = string;

/**
 * Not found response
 * @description Not found
 */
export type DeleteApiV1ScenariosScenarioId404 = string;

/**
 * Internal server error response
 * @description Internal server error
 */
export type DeleteApiV1ScenariosScenarioId500 = string;

export type DeleteApiV1ScenariosScenarioIdMutationResponse =
  DeleteApiV1ScenariosScenarioId200;

export type DeleteApiV1ScenariosScenarioIdMutation = {
  Response: DeleteApiV1ScenariosScenarioId200;
  PathParams: DeleteApiV1ScenariosScenarioIdPathParams;
  Errors:
    | DeleteApiV1ScenariosScenarioId400
    | DeleteApiV1ScenariosScenarioId401
    | DeleteApiV1ScenariosScenarioId403
    | DeleteApiV1ScenariosScenarioId404
    | DeleteApiV1ScenariosScenarioId500;
};
