/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { DeleteScenarioSceneResponseSchema } from "./delete-scenario-scene-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export type DeleteApiV1ScenariosScenesBySceneIdPathParams = {
  /**
   * @type string, uuid
   */
  sceneId: string;
};

/**
 * Delete scenario scene response
 * @description Scenario scene deleted successfully
 */
export type DeleteApiV1ScenariosScenesBySceneId200 =
  DeleteScenarioSceneResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type DeleteApiV1ScenariosScenesBySceneId400 = BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type DeleteApiV1ScenariosScenesBySceneId401 = UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type DeleteApiV1ScenariosScenesBySceneId402 =
  PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type DeleteApiV1ScenariosScenesBySceneId403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type DeleteApiV1ScenariosScenesBySceneId404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type DeleteApiV1ScenariosScenesBySceneId500 =
  InternalServerErrorResponseSchema;

export type DeleteApiV1ScenariosScenesBySceneIdMutationResponse =
  DeleteApiV1ScenariosScenesBySceneId200;

export type DeleteApiV1ScenariosScenesBySceneIdMutation = {
  Response: DeleteApiV1ScenariosScenesBySceneId200;
  PathParams: DeleteApiV1ScenariosScenesBySceneIdPathParams;
  Errors:
    | DeleteApiV1ScenariosScenesBySceneId400
    | DeleteApiV1ScenariosScenesBySceneId401
    | DeleteApiV1ScenariosScenesBySceneId402
    | DeleteApiV1ScenariosScenesBySceneId403
    | DeleteApiV1ScenariosScenesBySceneId404
    | DeleteApiV1ScenariosScenesBySceneId500;
};
