/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteApiV1ScenariosVersionsVersionIdPathParams = {
  /**
   * @type string, uuid
   */
  versionId: string;
};

export const dataStatusEnum9 = {
  pending: "pending",
  generation: "generation",
  failed: "failed",
  ready: "ready",
} as const;

export type DataStatusEnum9Key =
  (typeof dataStatusEnum9)[keyof typeof dataStatusEnum9];

/**
 * @description Scenario version deleted successfully
 */
export type DeleteApiV1ScenariosVersionsVersionId200 = {
  /**
   * @type object
   */
  data: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    scenarioId: string;
    /**
     * @type string
     */
    status: DataStatusEnum9Key;
    /**
     * @type string
     */
    createdAt: string;
    /**
     * @type string
     */
    updatedAt: string;
  };
};

/**
 * Bad request response
 * @description Bad request
 */
export type DeleteApiV1ScenariosVersionsVersionId400 = string;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type DeleteApiV1ScenariosVersionsVersionId401 = string;

/**
 * Forbidden response
 * @description Forbidden
 */
export type DeleteApiV1ScenariosVersionsVersionId403 = string;

/**
 * Not found response
 * @description Not found
 */
export type DeleteApiV1ScenariosVersionsVersionId404 = string;

/**
 * Internal server error response
 * @description Internal server error
 */
export type DeleteApiV1ScenariosVersionsVersionId500 = string;

export type DeleteApiV1ScenariosVersionsVersionIdMutationResponse =
  DeleteApiV1ScenariosVersionsVersionId200;

export type DeleteApiV1ScenariosVersionsVersionIdMutation = {
  Response: DeleteApiV1ScenariosVersionsVersionId200;
  PathParams: DeleteApiV1ScenariosVersionsVersionIdPathParams;
  Errors:
    | DeleteApiV1ScenariosVersionsVersionId400
    | DeleteApiV1ScenariosVersionsVersionId401
    | DeleteApiV1ScenariosVersionsVersionId403
    | DeleteApiV1ScenariosVersionsVersionId404
    | DeleteApiV1ScenariosVersionsVersionId500;
};
