/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { DeletePaymentMethodResponseSchema } from "./delete-payment-method-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export type DeleteApiV1BillingPaymentMethodsByPaymentMethodIdPathParams = {
  /**
   * @type string, uuid
   */
  paymentMethodId: string;
};

/**
 * Delete payment method response
 * @description Payment method deleted successfully
 */
export type DeleteApiV1BillingPaymentMethodsByPaymentMethodId200 =
  DeletePaymentMethodResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type DeleteApiV1BillingPaymentMethodsByPaymentMethodId400 =
  BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type DeleteApiV1BillingPaymentMethodsByPaymentMethodId401 =
  UnauthorizedResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type DeleteApiV1BillingPaymentMethodsByPaymentMethodId403 =
  ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type DeleteApiV1BillingPaymentMethodsByPaymentMethodId404 =
  NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type DeleteApiV1BillingPaymentMethodsByPaymentMethodId500 =
  InternalServerErrorResponseSchema;

export type DeleteApiV1BillingPaymentMethodsByPaymentMethodIdMutationResponse =
  DeleteApiV1BillingPaymentMethodsByPaymentMethodId200;

export type DeleteApiV1BillingPaymentMethodsByPaymentMethodIdMutation = {
  Response: DeleteApiV1BillingPaymentMethodsByPaymentMethodId200;
  PathParams: DeleteApiV1BillingPaymentMethodsByPaymentMethodIdPathParams;
  Errors:
    | DeleteApiV1BillingPaymentMethodsByPaymentMethodId400
    | DeleteApiV1BillingPaymentMethodsByPaymentMethodId401
    | DeleteApiV1BillingPaymentMethodsByPaymentMethodId403
    | DeleteApiV1BillingPaymentMethodsByPaymentMethodId404
    | DeleteApiV1BillingPaymentMethodsByPaymentMethodId500;
};
