/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GetProfileTypesResponseSchema } from "./get-profile-types-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

/**
 * Get profile types response
 * @description Profile types retrieved successfully
 */
export type GetApiV1ProfilesTypes200 = GetProfileTypesResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1ProfilesTypes400 = BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1ProfilesTypes401 = UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type GetApiV1ProfilesTypes402 = PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1ProfilesTypes403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1ProfilesTypes404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1ProfilesTypes500 = InternalServerErrorResponseSchema;

export type GetApiV1ProfilesTypesQueryResponse = GetApiV1ProfilesTypes200;

export type GetApiV1ProfilesTypesQuery = {
  Response: GetApiV1ProfilesTypes200;
  Errors:
    | GetApiV1ProfilesTypes400
    | GetApiV1ProfilesTypes401
    | GetApiV1ProfilesTypes402
    | GetApiV1ProfilesTypes403
    | GetApiV1ProfilesTypes404
    | GetApiV1ProfilesTypes500;
};
