/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Templates retrieved successfully
 */
export type GetApiV1Templates200 = {
  /**
   * @type array
   */
  data: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string
     */
    slug: string;
    /**
     * @type string
     */
    name: string;
    description: string | null;
    icon: string | null;
    /**
     * @type string
     */
    color: string;
    /**
     * @type string
     */
    createdAt: string;
    /**
     * @type string
     */
    updatedAt: string;
  }[];
};

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1Templates400 = string;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1Templates401 = string;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1Templates403 = string;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1Templates404 = string;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1Templates500 = string;

export type GetApiV1TemplatesQueryResponse = GetApiV1Templates200;

export type GetApiV1TemplatesQuery = {
  Response: GetApiV1Templates200;
  Errors:
    | GetApiV1Templates400
    | GetApiV1Templates401
    | GetApiV1Templates403
    | GetApiV1Templates404
    | GetApiV1Templates500;
};
