/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const userRoleEnum = {
  user: "user",
  admin: "admin",
} as const;

export type UserRoleEnumKey = (typeof userRoleEnum)[keyof typeof userRoleEnum];

/**
 * @description My profiles retrieved successfully
 */
export type GetApiV1ProfilesMy200 = {
  /**
   * @type array
   */
  data: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    userId: string;
    /**
     * @type string
     */
    name: string;
    description: string | null;
    targetAudience: string | null;
    typeId: string | null;
    /**
     * @type string
     */
    createdAt: string;
    /**
     * @type string
     */
    updatedAt: string;
    /**
     * @type object
     */
    user: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      email: string;
      /**
       * @type boolean
       */
      emailVerified: boolean;
      phone: string | null;
      /**
       * @type boolean
       */
      phoneVerified: boolean;
      /**
       * @type string
       */
      name: string;
      image: string | null;
      /**
       * @type string
       */
      role: UserRoleEnumKey;
      /**
       * @type boolean
       */
      banned: boolean;
      banReason: string | null;
      banExpires: string | null;
      /**
       * @type string
       */
      createdAt: string;
      /**
       * @type string
       */
      updatedAt: string;
    };
    /**
     * @type object
     */
    type: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      slug: string;
      /**
       * @type string
       */
      name: string;
      description: string | null;
      icon: string | null;
      /**
       * @type string
       */
      createdAt: string;
      /**
       * @type string
       */
      updatedAt: string;
    };
    /**
     * @type array
     */
    platforms: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      slug: string;
      /**
       * @type string
       */
      name: string;
      description: string | null;
      logoUrl: string | null;
      baseUrl: string | null;
      /**
       * @type string
       */
      createdAt: string;
      /**
       * @type string
       */
      updatedAt: string;
    }[];
    /**
     * @type array
     */
    tones: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      slug: string;
      /**
       * @type string
       */
      name: string;
      description: string | null;
      icon: string | null;
      /**
       * @type string
       */
      createdAt: string;
      /**
       * @type string
       */
      updatedAt: string;
    }[];
  }[];
};

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1ProfilesMy400 = string;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1ProfilesMy401 = string;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1ProfilesMy403 = string;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1ProfilesMy404 = string;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1ProfilesMy500 = string;

export type GetApiV1ProfilesMyQueryResponse = GetApiV1ProfilesMy200;

export type GetApiV1ProfilesMyQuery = {
  Response: GetApiV1ProfilesMy200;
  Errors:
    | GetApiV1ProfilesMy400
    | GetApiV1ProfilesMy401
    | GetApiV1ProfilesMy403
    | GetApiV1ProfilesMy404
    | GetApiV1ProfilesMy500;
};
