/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { IdeasListsFiltersSchema } from "./ideas-lists-filters-schema.ts";

/**
 * Get ideas lists filters response
 * @description Ideas lists filters response payload
 */
export type GetIdeasListsFiltersResponseSchema = {
  /**
   * @description Ideas lists filters description
   * @type array
   */
  data: IdeasListsFiltersSchema;
};
