/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SubscriptionExtendedSchema } from "./subscription-extended-schema.ts";

/**
 * Get my subscriptions response
 * @description Get my subscriptions response description
 */
export type GetMySubscriptionsResponseSchema = {
  /**
   * @type array
   */
  data: SubscriptionExtendedSchema[];
};
