/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GetScenarioCurrentVersionResponseSchema } from "./get-scenario-current-version-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export type GetApiV1ScenariosByScenarioIdCurrentVersionPathParams = {
  /**
   * @type string, uuid
   */
  scenarioId: string;
};

/**
 * Get scenario current version response
 * @description Scenario current version retrieved successfully
 */
export type GetApiV1ScenariosByScenarioIdCurrentVersion200 =
  GetScenarioCurrentVersionResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1ScenariosByScenarioIdCurrentVersion400 =
  BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1ScenariosByScenarioIdCurrentVersion401 =
  UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type GetApiV1ScenariosByScenarioIdCurrentVersion402 =
  PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1ScenariosByScenarioIdCurrentVersion403 =
  ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1ScenariosByScenarioIdCurrentVersion404 =
  NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1ScenariosByScenarioIdCurrentVersion500 =
  InternalServerErrorResponseSchema;

export type GetApiV1ScenariosByScenarioIdCurrentVersionQueryResponse =
  GetApiV1ScenariosByScenarioIdCurrentVersion200;

export type GetApiV1ScenariosByScenarioIdCurrentVersionQuery = {
  Response: GetApiV1ScenariosByScenarioIdCurrentVersion200;
  PathParams: GetApiV1ScenariosByScenarioIdCurrentVersionPathParams;
  Errors:
    | GetApiV1ScenariosByScenarioIdCurrentVersion400
    | GetApiV1ScenariosByScenarioIdCurrentVersion401
    | GetApiV1ScenariosByScenarioIdCurrentVersion402
    | GetApiV1ScenariosByScenarioIdCurrentVersion403
    | GetApiV1ScenariosByScenarioIdCurrentVersion404
    | GetApiV1ScenariosByScenarioIdCurrentVersion500;
};
