/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GetLegalDocumentsResponseSchema } from "./get-legal-documents-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

/**
 * Get legal documents response
 * @description Legal documents retrieved successfully
 */
export type GetApiV1LegalDocuments200 = GetLegalDocumentsResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1LegalDocuments400 = BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1LegalDocuments401 = UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type GetApiV1LegalDocuments402 = PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1LegalDocuments403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1LegalDocuments404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1LegalDocuments500 = InternalServerErrorResponseSchema;

export type GetApiV1LegalDocumentsQueryResponse = GetApiV1LegalDocuments200;

export type GetApiV1LegalDocumentsQuery = {
  Response: GetApiV1LegalDocuments200;
  Errors:
    | GetApiV1LegalDocuments400
    | GetApiV1LegalDocuments401
    | GetApiV1LegalDocuments402
    | GetApiV1LegalDocuments403
    | GetApiV1LegalDocuments404
    | GetApiV1LegalDocuments500;
};
