/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GetIdeasListExportResponseSchema } from "./get-ideas-list-export-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export type GetApiV1IdeasListsByIdeasListIdExportsByExportIdPathParams = {
  /**
   * @type string, uuid
   */
  ideasListId: string;
  /**
   * @type string, uuid
   */
  exportId: string;
};

/**
 * Get ideas list export response
 * @description Ideas list export retrieved successfully
 */
export type GetApiV1IdeasListsByIdeasListIdExportsByExportId200 =
  GetIdeasListExportResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1IdeasListsByIdeasListIdExportsByExportId400 =
  BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1IdeasListsByIdeasListIdExportsByExportId401 =
  UnauthorizedResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1IdeasListsByIdeasListIdExportsByExportId403 =
  ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1IdeasListsByIdeasListIdExportsByExportId404 =
  NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1IdeasListsByIdeasListIdExportsByExportId500 =
  InternalServerErrorResponseSchema;

export type GetApiV1IdeasListsByIdeasListIdExportsByExportIdQueryResponse =
  GetApiV1IdeasListsByIdeasListIdExportsByExportId200;

export type GetApiV1IdeasListsByIdeasListIdExportsByExportIdQuery = {
  Response: GetApiV1IdeasListsByIdeasListIdExportsByExportId200;
  PathParams: GetApiV1IdeasListsByIdeasListIdExportsByExportIdPathParams;
  Errors:
    | GetApiV1IdeasListsByIdeasListIdExportsByExportId400
    | GetApiV1IdeasListsByIdeasListIdExportsByExportId401
    | GetApiV1IdeasListsByIdeasListIdExportsByExportId403
    | GetApiV1IdeasListsByIdeasListIdExportsByExportId404
    | GetApiV1IdeasListsByIdeasListIdExportsByExportId500;
};
