/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { IdeaExtendedSchema } from "./idea-extended-schema.ts";

/**
 * Get idea response
 * @description Get idea response description
 */
export type GetIdeaResponseSchema = {
  /**
   * @description Idea extended description
   * @type object
   */
  data: IdeaExtendedSchema;
};
