/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProductFeatureSchema } from "./product-feature-schema.ts";

/**
 * Get product features response
 * @description Get product features response description
 */
export type GetProductFeaturesResponseSchema = {
  /**
   * @type array
   */
  data: ProductFeatureSchema[];
};
