/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GetLegalDocumentResponseSchema } from "./get-legal-document-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export type GetApiV1LegalDocumentsBySlugPathParams = {
  /**
   * @minLength 1
   * @type string
   */
  slug: string;
};

/**
 * Get legal document response
 * @description Legal document retrieved successfully
 */
export type GetApiV1LegalDocumentsBySlug200 = GetLegalDocumentResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1LegalDocumentsBySlug400 = BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1LegalDocumentsBySlug401 = UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type GetApiV1LegalDocumentsBySlug402 = PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1LegalDocumentsBySlug403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1LegalDocumentsBySlug404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1LegalDocumentsBySlug500 = InternalServerErrorResponseSchema;

export type GetApiV1LegalDocumentsBySlugQueryResponse =
  GetApiV1LegalDocumentsBySlug200;

export type GetApiV1LegalDocumentsBySlugQuery = {
  Response: GetApiV1LegalDocumentsBySlug200;
  PathParams: GetApiV1LegalDocumentsBySlugPathParams;
  Errors:
    | GetApiV1LegalDocumentsBySlug400
    | GetApiV1LegalDocumentsBySlug401
    | GetApiV1LegalDocumentsBySlug402
    | GetApiV1LegalDocumentsBySlug403
    | GetApiV1LegalDocumentsBySlug404
    | GetApiV1LegalDocumentsBySlug500;
};
