/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProfileExtendedSchema } from "./profile-extended-schema.ts";

/**
 * Get profile response
 * @description Get profile response description
 */
export type GetProfileResponseSchema = {
  /**
   * @description Profile extended description
   * @type object
   */
  data: ProfileExtendedSchema;
};
