/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description My scenarios retrieved successfully
 */
export type GetApiV1ScenariosMy200 = {
  /**
   * @type array
   */
  data: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    userId: string;
    currentVersionId: string | null;
    profileId: string | null;
    templateId: string | null;
    platformId: string | null;
    videoTypeId: string | null;
    videoDurationId: string | null;
    /**
     * @type boolean
     */
    saved: boolean;
    name: string | null;
    description: string | null;
    targetAudience: string | null;
    /**
     * @type string
     */
    createdAt: string;
    /**
     * @type string
     */
    updatedAt: string;
  }[];
};

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1ScenariosMy400 = string;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1ScenariosMy401 = string;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1ScenariosMy403 = string;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1ScenariosMy404 = string;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1ScenariosMy500 = string;

export type GetApiV1ScenariosMyQueryResponse = GetApiV1ScenariosMy200;

export type GetApiV1ScenariosMyQuery = {
  Response: GetApiV1ScenariosMy200;
  Errors:
    | GetApiV1ScenariosMy400
    | GetApiV1ScenariosMy401
    | GetApiV1ScenariosMy403
    | GetApiV1ScenariosMy404
    | GetApiV1ScenariosMy500;
};
