/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GetScenariosFiltersResponseSchema } from "./get-scenarios-filters-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

/**
 * Get scenarios filters response
 * @description Scenarios filters retrieved successfully
 */
export type GetApiV1ScenariosFilters200 = GetScenariosFiltersResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1ScenariosFilters400 = BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1ScenariosFilters401 = UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type GetApiV1ScenariosFilters402 = PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1ScenariosFilters403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1ScenariosFilters404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1ScenariosFilters500 = InternalServerErrorResponseSchema;

export type GetApiV1ScenariosFiltersQueryResponse = GetApiV1ScenariosFilters200;

export type GetApiV1ScenariosFiltersQuery = {
  Response: GetApiV1ScenariosFilters200;
  Errors:
    | GetApiV1ScenariosFilters400
    | GetApiV1ScenariosFilters401
    | GetApiV1ScenariosFilters402
    | GetApiV1ScenariosFilters403
    | GetApiV1ScenariosFilters404
    | GetApiV1ScenariosFilters500;
};
