/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Get referral info response
 * @description Get referral info response description
 */
export type GetReferralInfoResponseSchema = {
  /**
   * @type object
   */
  data: {
    /**
     * @type string
     */
    referralBasicInfo: string;
    /**
     * @type string
     */
    referralDocumentLink: string;
  };
};
