/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const dataBillingPeriodEnum = {
  month: "month",
  year: "year",
} as const;

export type DataBillingPeriodEnumKey =
  (typeof dataBillingPeriodEnum)[keyof typeof dataBillingPeriodEnum];

/**
 * @description Tariffs retrieved successfully
 */
export type GetApiV1Tariffs200 = {
  /**
   * @type array
   */
  data: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @maxLength 255
     * @type string
     */
    slug: string;
    /**
     * @type string
     */
    name: string;
    description: string | null;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    price: number;
    oldPrice: number | null;
    /**
     * @minLength -9007199254740991
     * @maxLength 9007199254740991
     * @type integer
     */
    creditsAmount: number;
    billingPeriod: DataBillingPeriodEnumKey | null;
    /**
     * @type boolean
     */
    priority: boolean;
    /**
     * @type string
     */
    createdAt: string;
    /**
     * @type string
     */
    updatedAt: string;
    trial?: {
      /**
       * @type string, uuid
       */
      id: string;
      tariffId: string | null;
      /**
       * @maxLength 255
       * @type string
       */
      slug: string;
      /**
       * @minLength -9007199254740991
       * @maxLength 9007199254740991
       * @type integer
       */
      price: number;
      /**
       * @minLength -9007199254740991
       * @maxLength 9007199254740991
       * @type integer
       */
      creditsAmount: number;
      /**
       * @type boolean
       */
      active: boolean;
      /**
       * @type boolean
       */
      firstTimeOnly: boolean;
      /**
       * @minLength -9007199254740991
       * @maxLength 9007199254740991
       * @type integer
       */
      durationDays: number;
      /**
       * @type string
       */
      createdAt: string;
      /**
       * @type string
       */
      updatedAt: string;
    } | null;
  }[];
};

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1Tariffs400 = string;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1Tariffs401 = string;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1Tariffs403 = string;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1Tariffs404 = string;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1Tariffs500 = string;

export type GetApiV1TariffsQueryResponse = GetApiV1Tariffs200;

export type GetApiV1TariffsQuery = {
  Response: GetApiV1Tariffs200;
  Errors:
    | GetApiV1Tariffs400
    | GetApiV1Tariffs401
    | GetApiV1Tariffs403
    | GetApiV1Tariffs404
    | GetApiV1Tariffs500;
};
