/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiV1ScenariosScenarioIdVersionsPathParams = {
  /**
   * @type string, uuid
   */
  scenarioId: string;
};

export const dataStatusEnum11 = {
  pending: "pending",
  generation: "generation",
  failed: "failed",
  ready: "ready",
} as const;

export type DataStatusEnum11Key =
  (typeof dataStatusEnum11)[keyof typeof dataStatusEnum11];

/**
 * @description Scenario versions retrieved successfully
 */
export type GetApiV1ScenariosScenarioIdVersions200 = {
  /**
   * @type array
   */
  data: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    scenarioId: string;
    /**
     * @type string
     */
    status: DataStatusEnum11Key;
    /**
     * @type string
     */
    createdAt: string;
    /**
     * @type string
     */
    updatedAt: string;
  }[];
};

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1ScenariosScenarioIdVersions400 = string;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1ScenariosScenarioIdVersions401 = string;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1ScenariosScenarioIdVersions403 = string;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1ScenariosScenarioIdVersions404 = string;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1ScenariosScenarioIdVersions500 = string;

export type GetApiV1ScenariosScenarioIdVersionsQueryResponse =
  GetApiV1ScenariosScenarioIdVersions200;

export type GetApiV1ScenariosScenarioIdVersionsQuery = {
  Response: GetApiV1ScenariosScenarioIdVersions200;
  PathParams: GetApiV1ScenariosScenarioIdVersionsPathParams;
  Errors:
    | GetApiV1ScenariosScenarioIdVersions400
    | GetApiV1ScenariosScenarioIdVersions401
    | GetApiV1ScenariosScenarioIdVersions403
    | GetApiV1ScenariosScenarioIdVersions404
    | GetApiV1ScenariosScenarioIdVersions500;
};
