/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProfileTypeSchema } from "./profile-type-schema.ts";

/**
 * Get profile types response
 * @description Get profile types response description
 */
export type GetProfileTypesResponseSchema = {
  /**
   * @type array
   */
  data: ProfileTypeSchema[];
};
