/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const getMyIdeasListResponseMetaSchemaSortOrderEnum = {
  asc: "asc",
  desc: "desc",
} as const;

export type GetMyIdeasListResponseMetaSchemaSortOrderEnumKey =
  (typeof getMyIdeasListResponseMetaSchemaSortOrderEnum)[keyof typeof getMyIdeasListResponseMetaSchemaSortOrderEnum];

export const getMyIdeasListResponseMetaSchemaSortByEnum = {
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const;

export type GetMyIdeasListResponseMetaSchemaSortByEnumKey =
  (typeof getMyIdeasListResponseMetaSchemaSortByEnum)[keyof typeof getMyIdeasListResponseMetaSchemaSortByEnum];

/**
 * Get my ideas list response meta
 * @description Get my ideas list response meta description
 */
export type GetMyIdeasListResponseMetaSchema = {
  /**
   * @description Номер предыдущей страницы
   */
  previousPage: number | null;
  /**
   * @description Номер текущей страницы
   * @type number
   */
  currentPage: number;
  /**
   * @description Номер следующей страницы
   */
  nextPage: number | null;
  /**
   * @description Количество элементов в одной странице ответа
   * @type number
   */
  perPage: number;
  /**
   * @description Общее количество элементов по запросу
   * @type number
   */
  totalItems: number;
  /**
   * @description Общее количество страниц по запросу
   * @type number
   */
  totalPages: number;
  /**
   * @description Вид сортировки
   * @type string
   */
  sortOrder: GetMyIdeasListResponseMetaSchemaSortOrderEnumKey;
  /**
   * @type string
   */
  sortBy: GetMyIdeasListResponseMetaSchemaSortByEnumKey;
  /**
   * @description Строка поиска
   * @type string | undefined
   */
  q?: string;
  /**
   * @type string | undefined, uuid
   */
  profileId?: string;
};
