/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GetScenarioVersionsResponseSchema } from "./get-scenario-versions-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export type GetApiV1ScenariosByScenarioIdVersionsPathParams = {
  /**
   * @type string, uuid
   */
  scenarioId: string;
};

/**
 * Get scenario versions response
 * @description Scenario versions retrieved successfully
 */
export type GetApiV1ScenariosByScenarioIdVersions200 =
  GetScenarioVersionsResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1ScenariosByScenarioIdVersions400 = BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1ScenariosByScenarioIdVersions401 =
  UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type GetApiV1ScenariosByScenarioIdVersions402 =
  PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1ScenariosByScenarioIdVersions403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1ScenariosByScenarioIdVersions404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1ScenariosByScenarioIdVersions500 =
  InternalServerErrorResponseSchema;

export type GetApiV1ScenariosByScenarioIdVersionsQueryResponse =
  GetApiV1ScenariosByScenarioIdVersions200;

export type GetApiV1ScenariosByScenarioIdVersionsQuery = {
  Response: GetApiV1ScenariosByScenarioIdVersions200;
  PathParams: GetApiV1ScenariosByScenarioIdVersionsPathParams;
  Errors:
    | GetApiV1ScenariosByScenarioIdVersions400
    | GetApiV1ScenariosByScenarioIdVersions401
    | GetApiV1ScenariosByScenarioIdVersions402
    | GetApiV1ScenariosByScenarioIdVersions403
    | GetApiV1ScenariosByScenarioIdVersions404
    | GetApiV1ScenariosByScenarioIdVersions500;
};
