/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GetArchiveFiltersResponseSchema } from "./get-archive-filters-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

/**
 * Get archive filters response
 * @description Archive filters retrieved successfully
 */
export type GetApiV1ArchiveFilters200 = GetArchiveFiltersResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1ArchiveFilters400 = BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1ArchiveFilters401 = UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type GetApiV1ArchiveFilters402 = PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1ArchiveFilters403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1ArchiveFilters404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1ArchiveFilters500 = InternalServerErrorResponseSchema;

export type GetApiV1ArchiveFiltersQueryResponse = GetApiV1ArchiveFilters200;

export type GetApiV1ArchiveFiltersQuery = {
  Response: GetApiV1ArchiveFilters200;
  Errors:
    | GetApiV1ArchiveFilters400
    | GetApiV1ArchiveFilters401
    | GetApiV1ArchiveFilters402
    | GetApiV1ArchiveFilters403
    | GetApiV1ArchiveFilters404
    | GetApiV1ArchiveFilters500;
};
