/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GetMyIdeasListsResponseSchema } from "./get-my-ideas-lists-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export type GetApiV1IdeasListsQueryParams = {
  /**
   * @description Строка поиска
   * @type string | undefined
   */
  q?: string;
  /**
   * @description Номер страницы
   * @type number | undefined
   */
  page?: number;
  /**
   * @description Количество элементов в одной странице ответа
   * @type number | undefined
   */
  perPage?: number;
  /**
   * @type string | undefined
   */
  sort?: string;
  templateIds?: string[] | string;
  profileIds?: string[] | string;
  toneIds?: string[] | string;
  videoTypeIds?: string[] | string;
};

/**
 * Get my ideas lists response
 * @description Ideas lists retrieved successfully
 */
export type GetApiV1IdeasLists200 = GetMyIdeasListsResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1IdeasLists400 = BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1IdeasLists401 = UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type GetApiV1IdeasLists402 = PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1IdeasLists403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1IdeasLists404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1IdeasLists500 = InternalServerErrorResponseSchema;

export type GetApiV1IdeasListsQueryResponse = GetApiV1IdeasLists200;

export type GetApiV1IdeasListsQuery = {
  Response: GetApiV1IdeasLists200;
  QueryParams: GetApiV1IdeasListsQueryParams;
  Errors:
    | GetApiV1IdeasLists400
    | GetApiV1IdeasLists401
    | GetApiV1IdeasLists402
    | GetApiV1IdeasLists403
    | GetApiV1IdeasLists404
    | GetApiV1IdeasLists500;
};
