/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GetProductionStatusesResponseSchema } from "./get-production-statuses-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export const getApiV1ProductionStatusesQueryParamsEntityEnum = {
  scenario: "scenario",
  scenarioChapter: "scenarioChapter",
} as const;

export type GetApiV1ProductionStatusesQueryParamsEntityEnumKey =
  (typeof getApiV1ProductionStatusesQueryParamsEntityEnum)[keyof typeof getApiV1ProductionStatusesQueryParamsEntityEnum];

export type GetApiV1ProductionStatusesQueryParams = {
  /**
   * @type string
   */
  entity: GetApiV1ProductionStatusesQueryParamsEntityEnumKey;
};

/**
 * Get production statuses response
 * @description Production statuses retrieved successfully
 */
export type GetApiV1ProductionStatuses200 = GetProductionStatusesResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1ProductionStatuses400 = BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1ProductionStatuses401 = UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type GetApiV1ProductionStatuses402 = PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1ProductionStatuses403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1ProductionStatuses404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1ProductionStatuses500 = InternalServerErrorResponseSchema;

export type GetApiV1ProductionStatusesQueryResponse =
  GetApiV1ProductionStatuses200;

export type GetApiV1ProductionStatusesQuery = {
  Response: GetApiV1ProductionStatuses200;
  QueryParams: GetApiV1ProductionStatusesQueryParams;
  Errors:
    | GetApiV1ProductionStatuses400
    | GetApiV1ProductionStatuses401
    | GetApiV1ProductionStatuses402
    | GetApiV1ProductionStatuses403
    | GetApiV1ProductionStatuses404
    | GetApiV1ProductionStatuses500;
};
