/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GetIdeaResponseSchema } from "./get-idea-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export type GetApiV1IdeasByIdeaIdPathParams = {
  /**
   * @type string, uuid
   */
  ideaId: string;
};

/**
 * Get idea response
 * @description Idea retrieved successfully
 */
export type GetApiV1IdeasByIdeaId200 = GetIdeaResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1IdeasByIdeaId400 = BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1IdeasByIdeaId401 = UnauthorizedResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1IdeasByIdeaId403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1IdeasByIdeaId404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1IdeasByIdeaId500 = InternalServerErrorResponseSchema;

export type GetApiV1IdeasByIdeaIdQueryResponse = GetApiV1IdeasByIdeaId200;

export type GetApiV1IdeasByIdeaIdQuery = {
  Response: GetApiV1IdeasByIdeaId200;
  PathParams: GetApiV1IdeasByIdeaIdPathParams;
  Errors:
    | GetApiV1IdeasByIdeaId400
    | GetApiV1IdeasByIdeaId401
    | GetApiV1IdeasByIdeaId403
    | GetApiV1IdeasByIdeaId404
    | GetApiV1IdeasByIdeaId500;
};
