/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiV1IdeasListsIdeasListIdPathParams = {
  /**
   * @type string, uuid
   */
  ideasListId: string;
};

export type GetApiV1IdeasListsIdeasListIdQueryParams = {
  /**
   * @type boolean | undefined
   */
  saved?: boolean;
};

export const dataStatusEnum3 = {
  pending: "pending",
  generation: "generation",
  failed: "failed",
  ready: "ready",
} as const;

export type DataStatusEnum3Key =
  (typeof dataStatusEnum3)[keyof typeof dataStatusEnum3];

/**
 * @description Ideas list retrieved successfully
 */
export type GetApiV1IdeasListsIdeasListId200 = {
  /**
   * @type object
   */
  data: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    userId: string;
    profileId: string | null;
    templateId: string | null;
    /**
     * @type string
     */
    status: DataStatusEnum3Key;
    name: string | null;
    description: string | null;
    targetAudience: string | null;
    /**
     * @type string
     */
    createdAt: string;
    /**
     * @type string
     */
    updatedAt: string;
    template: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      slug: string;
      /**
       * @type string
       */
      name: string;
      description: string | null;
      icon: string | null;
      /**
       * @type string
       */
      color: string;
      /**
       * @type string
       */
      createdAt: string;
      /**
       * @type string
       */
      updatedAt: string;
    } | null;
    profile: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string, uuid
       */
      userId: string;
      /**
       * @type string
       */
      name: string;
      description: string | null;
      targetAudience: string | null;
      typeId: string | null;
      /**
       * @type string
       */
      createdAt: string;
      /**
       * @type string
       */
      updatedAt: string;
    } | null;
    /**
     * @type array
     */
    tones: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      slug: string;
      /**
       * @type string
       */
      name: string;
      description: string | null;
      icon: string | null;
      /**
       * @type string
       */
      createdAt: string;
      /**
       * @type string
       */
      updatedAt: string;
    }[];
    /**
     * @type array
     */
    videoTypes: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string
       */
      slug: string;
      /**
       * @type string
       */
      name: string;
      description: string | null;
      icon: string | null;
      /**
       * @type string
       */
      createdAt: string;
      /**
       * @type string
       */
      updatedAt: string;
    }[];
    /**
     * @type array
     */
    ideas: {
      /**
       * @type string, uuid
       */
      id: string;
      /**
       * @type string, uuid
       */
      ideasListId: string;
      /**
       * @type string, uuid
       */
      videoTypeId: string;
      /**
       * @type boolean
       */
      saved: boolean;
      liked: boolean | null;
      name: string | null;
      description: string | null;
      reason: string | null;
      /**
       * @type string
       */
      createdAt: string;
      /**
       * @type string
       */
      updatedAt: string;
    }[];
  };
};

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1IdeasListsIdeasListId400 = string;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1IdeasListsIdeasListId401 = string;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1IdeasListsIdeasListId403 = string;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1IdeasListsIdeasListId404 = string;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1IdeasListsIdeasListId500 = string;

export type GetApiV1IdeasListsIdeasListIdQueryResponse =
  GetApiV1IdeasListsIdeasListId200;

export type GetApiV1IdeasListsIdeasListIdQuery = {
  Response: GetApiV1IdeasListsIdeasListId200;
  PathParams: GetApiV1IdeasListsIdeasListIdPathParams;
  QueryParams: GetApiV1IdeasListsIdeasListIdQueryParams;
  Errors:
    | GetApiV1IdeasListsIdeasListId400
    | GetApiV1IdeasListsIdeasListId401
    | GetApiV1IdeasListsIdeasListId403
    | GetApiV1IdeasListsIdeasListId404
    | GetApiV1IdeasListsIdeasListId500;
};
