/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const itemsTypeEnum = {
  "profile": "profile",
  "ideas-list": "ideas-list",
  "scenario": "scenario",
  "metadata": "metadata",
} as const;

export type ItemsTypeEnumKey =
  (typeof itemsTypeEnum)[keyof typeof itemsTypeEnum];

export const itemsStatusEnum = {
  pending: "pending",
  completed: "completed",
  locked: "locked",
} as const;

export type ItemsStatusEnumKey =
  (typeof itemsStatusEnum)[keyof typeof itemsStatusEnum];

/**
 * Get onboarding response
 * @description Get onboarding response description
 */
export type GetOnboardingResponseSchema = {
  /**
   * @type string
   */
  icon: string;
  /**
   * @type string
   */
  title: string;
  /**
   * @type string
   */
  description: string;
  /**
   * @type array
   */
  items: {
    /**
     * @type string
     */
    type: ItemsTypeEnumKey;
    /**
     * @type string
     */
    status: ItemsStatusEnumKey;
    /**
     * @type string
     */
    title: string;
    /**
     * @type string
     */
    description: string;
  }[];
};
