/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Tones retrieved successfully
 */
export type GetApiV1Tones200 = {
  /**
   * @type array
   */
  data: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string
     */
    slug: string;
    /**
     * @type string
     */
    name: string;
    description: string | null;
    icon: string | null;
    /**
     * @type string
     */
    createdAt: string;
    /**
     * @type string
     */
    updatedAt: string;
  }[];
};

/**
 * Bad request response
 * @description Bad request
 */
export type GetApiV1Tones400 = string;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type GetApiV1Tones401 = string;

/**
 * Forbidden response
 * @description Forbidden
 */
export type GetApiV1Tones403 = string;

/**
 * Not found response
 * @description Not found
 */
export type GetApiV1Tones404 = string;

/**
 * Internal server error response
 * @description Internal server error
 */
export type GetApiV1Tones500 = string;

export type GetApiV1TonesQueryResponse = GetApiV1Tones200;

export type GetApiV1TonesQuery = {
  Response: GetApiV1Tones200;
  Errors:
    | GetApiV1Tones400
    | GetApiV1Tones401
    | GetApiV1Tones403
    | GetApiV1Tones404
    | GetApiV1Tones500;
};
