/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Initiate subscription payment body
 * @description Initiate subscription payment body description
 */
export type InitiateSubscriptionPaymentBodySchema = {
  /**
   * @type string
   */
  tariffSlug: string;
  /**
   * @type string | undefined
   */
  trialTariffSlug?: string;
  /**
   * @type string | undefined
   */
  redirect?: string;
};
