/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PatchApiV1ScenariosSceneComponentsSceneComponentIdPathParams = {
  /**
   * @type string, uuid
   */
  sceneComponentId: string;
};

/**
 * @description Scenario scene component updated successfully
 */
export type PatchApiV1ScenariosSceneComponentsSceneComponentId200 = {
  /**
   * @type object
   */
  data: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    typeId: string;
    /**
     * @type string, uuid
     */
    scenarioSceneId: string;
    /**
     * @type string
     */
    name: string;
    content: string | null;
    /**
     * @type string
     */
    createdAt: string;
    /**
     * @type string
     */
    updatedAt: string;
  };
};

/**
 * Bad request response
 * @description Bad request
 */
export type PatchApiV1ScenariosSceneComponentsSceneComponentId400 = string;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type PatchApiV1ScenariosSceneComponentsSceneComponentId401 = string;

/**
 * Forbidden response
 * @description Forbidden
 */
export type PatchApiV1ScenariosSceneComponentsSceneComponentId403 = string;

/**
 * Not found response
 * @description Not found
 */
export type PatchApiV1ScenariosSceneComponentsSceneComponentId404 = string;

/**
 * Internal server error response
 * @description Internal server error
 */
export type PatchApiV1ScenariosSceneComponentsSceneComponentId500 = string;

export type PatchApiV1ScenariosSceneComponentsSceneComponentIdMutationRequest =
  {
    /**
     * @type string | undefined
     */
    name?: string;
    content?: string | null;
    icon?: string | null;
    color?: string | null;
  };

export type PatchApiV1ScenariosSceneComponentsSceneComponentIdMutationResponse =
  PatchApiV1ScenariosSceneComponentsSceneComponentId200;

export type PatchApiV1ScenariosSceneComponentsSceneComponentIdMutation = {
  Response: PatchApiV1ScenariosSceneComponentsSceneComponentId200;
  Request: PatchApiV1ScenariosSceneComponentsSceneComponentIdMutationRequest;
  PathParams: PatchApiV1ScenariosSceneComponentsSceneComponentIdPathParams;
  Errors:
    | PatchApiV1ScenariosSceneComponentsSceneComponentId400
    | PatchApiV1ScenariosSceneComponentsSceneComponentId401
    | PatchApiV1ScenariosSceneComponentsSceneComponentId403
    | PatchApiV1ScenariosSceneComponentsSceneComponentId404
    | PatchApiV1ScenariosSceneComponentsSceneComponentId500;
};
