/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PatchApiV1ProfilesProfileIdPathParams = {
  /**
   * @type string, uuid
   */
  profileId: string;
};

/**
 * @description Profile updated successfully
 */
export type PatchApiV1ProfilesProfileId200 = {
  /**
   * @type object
   */
  data: {
    /**
     * @type string, uuid
     */
    id: string;
    /**
     * @type string, uuid
     */
    userId: string;
    /**
     * @type string
     */
    name: string;
    description: string | null;
    targetAudience: string | null;
    typeId: string | null;
    /**
     * @type string
     */
    createdAt: string;
    /**
     * @type string
     */
    updatedAt: string;
  };
};

/**
 * Bad request response
 * @description Bad request
 */
export type PatchApiV1ProfilesProfileId400 = string;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type PatchApiV1ProfilesProfileId401 = string;

/**
 * Forbidden response
 * @description Forbidden
 */
export type PatchApiV1ProfilesProfileId403 = string;

/**
 * Not found response
 * @description Not found
 */
export type PatchApiV1ProfilesProfileId404 = string;

/**
 * Internal server error response
 * @description Internal server error
 */
export type PatchApiV1ProfilesProfileId500 = string;

export type PatchApiV1ProfilesProfileIdMutationRequest = {
  /**
   * @type string | undefined
   */
  name?: string;
  description?: string | null;
  targetAudience?: string | null;
  typeId?: string | null;
  /**
   * @type array | undefined
   */
  platformIds?: string[];
  /**
   * @type array | undefined
   */
  toneIds?: string[];
};

export type PatchApiV1ProfilesProfileIdMutationResponse =
  PatchApiV1ProfilesProfileId200;

export type PatchApiV1ProfilesProfileIdMutation = {
  Response: PatchApiV1ProfilesProfileId200;
  Request: PatchApiV1ProfilesProfileIdMutationRequest;
  PathParams: PatchApiV1ProfilesProfileIdPathParams;
  Errors:
    | PatchApiV1ProfilesProfileId400
    | PatchApiV1ProfilesProfileId401
    | PatchApiV1ProfilesProfileId403
    | PatchApiV1ProfilesProfileId404
    | PatchApiV1ProfilesProfileId500;
};
