/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const paymentSchemaStatusEnum = {
  pending: "pending",
  succeeded: "succeeded",
  canceled: "canceled",
  failed: "failed",
} as const;

export type PaymentSchemaStatusEnumKey =
  (typeof paymentSchemaStatusEnum)[keyof typeof paymentSchemaStatusEnum];

/**
 * Payment method
 * @description Payment description
 */
export type PaymentSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  paymentMethodId: string | null;
  /**
   * @type string
   */
  externalId: string;
  paymentLink: string | null;
  /**
   * @minLength -8388608
   * @maxLength 8388607
   * @type number
   */
  amount: number;
  /**
   * @type string
   */
  currency: string;
  /**
   * @type string
   */
  status: PaymentSchemaStatusEnumKey;
  statusDetails: string | null;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
