/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreditsBatchExtendedSchema } from "./credits-batch-extended-schema.ts";
import type { PaymentMethodSchema } from "./payment-method-schema.ts";
import type { SubscriptionExtendedSchema } from "./subscription-extended-schema.ts";

export const paymentExtendedSchemaStatusEnum = {
  pending: "pending",
  succeeded: "succeeded",
  canceled: "canceled",
  failed: "failed",
} as const;

export type PaymentExtendedSchemaStatusEnumKey =
  (typeof paymentExtendedSchemaStatusEnum)[keyof typeof paymentExtendedSchemaStatusEnum];

/**
 * Payment extended
 * @description Payment extended description
 */
export type PaymentExtendedSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  paymentMethodId: string | null;
  /**
   * @type string
   */
  externalId: string;
  paymentLink: string | null;
  /**
   * @minLength -8388608
   * @maxLength 8388607
   * @type number
   */
  amount: number;
  /**
   * @type string
   */
  currency: string;
  /**
   * @type string
   */
  status: PaymentExtendedSchemaStatusEnumKey;
  statusDetails: string | null;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
  paymentMethod?: PaymentMethodSchema | null;
  subscription?: SubscriptionExtendedSchema | null;
  creditsBatch?: CreditsBatchExtendedSchema | null;
};
