/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Platform
 * @description Platform description
 */
export type PlatformSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  description: string | null;
  details: string | null;
  metadataDetails: string | null;
  logoUrl: string | null;
  baseUrl: string | null;
  urlRegex: string | null;
  channelUrlRegex: string | null;
  videoUrlRegex: string | null;
  /**
   * @type boolean
   */
  hasAutoImport: boolean;
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  priority: number;
  /**
   * @type string
   */
  slug: string;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
