/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateProfilesFromChannelsBodySchema } from "./create-profiles-from-channels-body-schema.ts";
import type { CreateProfilesFromChannelsErrorSchema } from "./create-profiles-from-channels-error-schema.ts";
import type { CreateProfilesFromChannelsResponseSchema } from "./create-profiles-from-channels-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

/**
 * Create profiles from channels response
 * @description Profiles from channels created successfully
 */
export type PostApiV1ProfilesChannels201 =
  CreateProfilesFromChannelsResponseSchema;

/**
 * Create profiles from channels error
 * @description Profiles from channels creation failed
 */
export type PostApiV1ProfilesChannels400 =
  CreateProfilesFromChannelsErrorSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type PostApiV1ProfilesChannels401 = UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type PostApiV1ProfilesChannels402 = PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type PostApiV1ProfilesChannels403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type PostApiV1ProfilesChannels404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type PostApiV1ProfilesChannels500 = InternalServerErrorResponseSchema;

/**
 * Create profiles from channels body
 */
export type PostApiV1ProfilesChannelsMutationRequest =
  CreateProfilesFromChannelsBodySchema;

export type PostApiV1ProfilesChannelsMutationResponse =
  PostApiV1ProfilesChannels201;

export type PostApiV1ProfilesChannelsMutation = {
  Response: PostApiV1ProfilesChannels201;
  Request: PostApiV1ProfilesChannelsMutationRequest;
  Errors:
    | PostApiV1ProfilesChannels400
    | PostApiV1ProfilesChannels401
    | PostApiV1ProfilesChannels402
    | PostApiV1ProfilesChannels403
    | PostApiV1ProfilesChannels404
    | PostApiV1ProfilesChannels500;
};
