/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { CreateIdeasListExportBodySchema } from "./create-ideas-list-export-body-schema.ts";
import type { CreateIdeasListExportResponseSchema } from "./create-ideas-list-export-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export type PostApiV1IdeasListsByIdeasListIdExportsPathParams = {
  /**
   * @type string, uuid
   */
  ideasListId: string;
};

/**
 * Create ideas list export response
 * @description Ideas list export created successfully
 */
export type PostApiV1IdeasListsByIdeasListIdExports201 =
  CreateIdeasListExportResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type PostApiV1IdeasListsByIdeasListIdExports400 =
  BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type PostApiV1IdeasListsByIdeasListIdExports401 =
  UnauthorizedResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type PostApiV1IdeasListsByIdeasListIdExports403 =
  ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type PostApiV1IdeasListsByIdeasListIdExports404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type PostApiV1IdeasListsByIdeasListIdExports500 =
  InternalServerErrorResponseSchema;

/**
 * Create ideas list export body
 */
export type PostApiV1IdeasListsByIdeasListIdExportsMutationRequest =
  CreateIdeasListExportBodySchema;

export type PostApiV1IdeasListsByIdeasListIdExportsMutationResponse =
  PostApiV1IdeasListsByIdeasListIdExports201;

export type PostApiV1IdeasListsByIdeasListIdExportsMutation = {
  Response: PostApiV1IdeasListsByIdeasListIdExports201;
  Request: PostApiV1IdeasListsByIdeasListIdExportsMutationRequest;
  PathParams: PostApiV1IdeasListsByIdeasListIdExportsPathParams;
  Errors:
    | PostApiV1IdeasListsByIdeasListIdExports400
    | PostApiV1IdeasListsByIdeasListIdExports401
    | PostApiV1IdeasListsByIdeasListIdExports403
    | PostApiV1IdeasListsByIdeasListIdExports404
    | PostApiV1IdeasListsByIdeasListIdExports500;
};
