/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { TriggerUpcomingChargesNewsletterResponseSchema } from "./trigger-upcoming-charges-newsletter-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

/**
 * Trigger upcoming charges newsletter response
 * @description Upcoming charges newsletter job has been enqueued
 */
export type PostApiV1BillingUpcomingChargesNewsletter202 =
  TriggerUpcomingChargesNewsletterResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type PostApiV1BillingUpcomingChargesNewsletter400 =
  BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type PostApiV1BillingUpcomingChargesNewsletter401 =
  UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type PostApiV1BillingUpcomingChargesNewsletter402 =
  PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type PostApiV1BillingUpcomingChargesNewsletter403 =
  ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type PostApiV1BillingUpcomingChargesNewsletter404 =
  NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type PostApiV1BillingUpcomingChargesNewsletter500 =
  InternalServerErrorResponseSchema;

export type PostApiV1BillingUpcomingChargesNewsletterMutationResponse =
  PostApiV1BillingUpcomingChargesNewsletter202;

export type PostApiV1BillingUpcomingChargesNewsletterMutation = {
  Response: PostApiV1BillingUpcomingChargesNewsletter202;
  Errors:
    | PostApiV1BillingUpcomingChargesNewsletter400
    | PostApiV1BillingUpcomingChargesNewsletter401
    | PostApiV1BillingUpcomingChargesNewsletter402
    | PostApiV1BillingUpcomingChargesNewsletter403
    | PostApiV1BillingUpcomingChargesNewsletter404
    | PostApiV1BillingUpcomingChargesNewsletter500;
};
