/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { CreateProfileChannelVideoBodySchema } from "./create-profile-channel-video-body-schema.ts";
import type { CreateProfileChannelVideoResponseSchema } from "./create-profile-channel-video-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

/**
 * Create profile channel video response
 * @description Profile channel video created successfully
 */
export type PostApiV1ProfilesChannelsVideos200 =
  CreateProfileChannelVideoResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type PostApiV1ProfilesChannelsVideos400 = BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type PostApiV1ProfilesChannelsVideos401 = UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type PostApiV1ProfilesChannelsVideos402 = PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type PostApiV1ProfilesChannelsVideos403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type PostApiV1ProfilesChannelsVideos404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type PostApiV1ProfilesChannelsVideos500 =
  InternalServerErrorResponseSchema;

/**
 * Create profile channel video body
 */
export type PostApiV1ProfilesChannelsVideosMutationRequest =
  CreateProfileChannelVideoBodySchema;

export type PostApiV1ProfilesChannelsVideosMutationResponse =
  PostApiV1ProfilesChannelsVideos200;

export type PostApiV1ProfilesChannelsVideosMutation = {
  Response: PostApiV1ProfilesChannelsVideos200;
  Request: PostApiV1ProfilesChannelsVideosMutationRequest;
  Errors:
    | PostApiV1ProfilesChannelsVideos400
    | PostApiV1ProfilesChannelsVideos401
    | PostApiV1ProfilesChannelsVideos402
    | PostApiV1ProfilesChannelsVideos403
    | PostApiV1ProfilesChannelsVideos404
    | PostApiV1ProfilesChannelsVideos500;
};
