/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";
import type { UpgradeSubscriptionBodySchema } from "./upgrade-subscription-body-schema.ts";
import type { UpgradeSubscriptionResponseSchema } from "./upgrade-subscription-response-schema.ts";

/**
 * Upgrade subscription response
 * @description Subscription upgraded successfully
 */
export type PostApiV1SubscriptionsUpgrade200 =
  UpgradeSubscriptionResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type PostApiV1SubscriptionsUpgrade400 = BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type PostApiV1SubscriptionsUpgrade401 = UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type PostApiV1SubscriptionsUpgrade402 = PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type PostApiV1SubscriptionsUpgrade403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type PostApiV1SubscriptionsUpgrade404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type PostApiV1SubscriptionsUpgrade500 =
  InternalServerErrorResponseSchema;

/**
 * Upgrade subscription body
 */
export type PostApiV1SubscriptionsUpgradeMutationRequest =
  UpgradeSubscriptionBodySchema;

export type PostApiV1SubscriptionsUpgradeMutationResponse =
  PostApiV1SubscriptionsUpgrade200;

export type PostApiV1SubscriptionsUpgradeMutation = {
  Response: PostApiV1SubscriptionsUpgrade200;
  Request: PostApiV1SubscriptionsUpgradeMutationRequest;
  Errors:
    | PostApiV1SubscriptionsUpgrade400
    | PostApiV1SubscriptionsUpgrade401
    | PostApiV1SubscriptionsUpgrade402
    | PostApiV1SubscriptionsUpgrade403
    | PostApiV1SubscriptionsUpgrade404
    | PostApiV1SubscriptionsUpgrade500;
};
