/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GetScenarioVersionExportResponseSchema } from "./get-scenario-version-export-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export type PostApiV1ScenariosVersionsByVersionIdExportPathParams = {
  /**
   * @type string, uuid
   */
  versionId: string;
};

/**
 * Get scenario version export response
 * @description Scenario version export retrieved successfully
 */
export type PostApiV1ScenariosVersionsByVersionIdExport200 =
  GetScenarioVersionExportResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type PostApiV1ScenariosVersionsByVersionIdExport400 =
  BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type PostApiV1ScenariosVersionsByVersionIdExport401 =
  UnauthorizedResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type PostApiV1ScenariosVersionsByVersionIdExport403 =
  ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type PostApiV1ScenariosVersionsByVersionIdExport404 =
  NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type PostApiV1ScenariosVersionsByVersionIdExport500 =
  InternalServerErrorResponseSchema;

export const postApiV1ScenariosVersionsByVersionIdExportMutationRequestFormatEnum =
  {
    pdf: "pdf",
    docx: "docx",
  } as const;

export type PostApiV1ScenariosVersionsByVersionIdExportMutationRequestFormatEnumKey =
  (typeof postApiV1ScenariosVersionsByVersionIdExportMutationRequestFormatEnum)[keyof typeof postApiV1ScenariosVersionsByVersionIdExportMutationRequestFormatEnum];

export type PostApiV1ScenariosVersionsByVersionIdExportMutationRequest = {
  /**
   * @type string
   */
  format: PostApiV1ScenariosVersionsByVersionIdExportMutationRequestFormatEnumKey;
};

export type PostApiV1ScenariosVersionsByVersionIdExportMutationResponse =
  PostApiV1ScenariosVersionsByVersionIdExport200;

export type PostApiV1ScenariosVersionsByVersionIdExportMutation = {
  Response: PostApiV1ScenariosVersionsByVersionIdExport200;
  Request: PostApiV1ScenariosVersionsByVersionIdExportMutationRequest;
  PathParams: PostApiV1ScenariosVersionsByVersionIdExportPathParams;
  Errors:
    | PostApiV1ScenariosVersionsByVersionIdExport400
    | PostApiV1ScenariosVersionsByVersionIdExport401
    | PostApiV1ScenariosVersionsByVersionIdExport403
    | PostApiV1ScenariosVersionsByVersionIdExport404
    | PostApiV1ScenariosVersionsByVersionIdExport500;
};
