/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { GenerateMoreIdeasBodySchema } from "./generate-more-ideas-body-schema.ts";
import type { GenerateMoreIdeasResponseSchema } from "./generate-more-ideas-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export type PostApiV1IdeasListsByIdeasListIdMoreIdeasPathParams = {
  /**
   * @type string, uuid
   */
  ideasListId: string;
};

/**
 * Generate more ideas response
 * @description More ideas generation queued successfully
 */
export type PostApiV1IdeasListsByIdeasListIdMoreIdeas202 =
  GenerateMoreIdeasResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type PostApiV1IdeasListsByIdeasListIdMoreIdeas400 =
  BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type PostApiV1IdeasListsByIdeasListIdMoreIdeas401 =
  UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type PostApiV1IdeasListsByIdeasListIdMoreIdeas402 =
  PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type PostApiV1IdeasListsByIdeasListIdMoreIdeas403 =
  ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type PostApiV1IdeasListsByIdeasListIdMoreIdeas404 =
  NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type PostApiV1IdeasListsByIdeasListIdMoreIdeas500 =
  InternalServerErrorResponseSchema;

/**
 * Generate more ideas body
 */
export type PostApiV1IdeasListsByIdeasListIdMoreIdeasMutationRequest =
  GenerateMoreIdeasBodySchema;

export type PostApiV1IdeasListsByIdeasListIdMoreIdeasMutationResponse =
  PostApiV1IdeasListsByIdeasListIdMoreIdeas202;

export type PostApiV1IdeasListsByIdeasListIdMoreIdeasMutation = {
  Response: PostApiV1IdeasListsByIdeasListIdMoreIdeas202;
  Request: PostApiV1IdeasListsByIdeasListIdMoreIdeasMutationRequest;
  PathParams: PostApiV1IdeasListsByIdeasListIdMoreIdeasPathParams;
  Errors:
    | PostApiV1IdeasListsByIdeasListIdMoreIdeas400
    | PostApiV1IdeasListsByIdeasListIdMoreIdeas401
    | PostApiV1IdeasListsByIdeasListIdMoreIdeas402
    | PostApiV1IdeasListsByIdeasListIdMoreIdeas403
    | PostApiV1IdeasListsByIdeasListIdMoreIdeas404
    | PostApiV1IdeasListsByIdeasListIdMoreIdeas500;
};
