/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { CreateIdeasListExportBodySchema } from "./create-ideas-list-export-body-schema.ts";
import type { CreateIdeasListExportResponseSchema } from "./create-ideas-list-export-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

export type PostApiV1IdeasListsByIdeasListIdExportPathParams = {
  /**
   * @type string, uuid
   */
  ideasListId: string;
};

/**
 * Create ideas list export response
 * @description Ideas list export retrieved successfully
 */
export type PostApiV1IdeasListsByIdeasListIdExport200 =
  CreateIdeasListExportResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type PostApiV1IdeasListsByIdeasListIdExport400 =
  BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type PostApiV1IdeasListsByIdeasListIdExport401 =
  UnauthorizedResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type PostApiV1IdeasListsByIdeasListIdExport403 = ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type PostApiV1IdeasListsByIdeasListIdExport404 = NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type PostApiV1IdeasListsByIdeasListIdExport500 =
  InternalServerErrorResponseSchema;

/**
 * Create ideas list export body
 */
export type PostApiV1IdeasListsByIdeasListIdExportMutationRequest =
  CreateIdeasListExportBodySchema;

export type PostApiV1IdeasListsByIdeasListIdExportMutationResponse =
  PostApiV1IdeasListsByIdeasListIdExport200;

export type PostApiV1IdeasListsByIdeasListIdExportMutation = {
  Response: PostApiV1IdeasListsByIdeasListIdExport200;
  Request: PostApiV1IdeasListsByIdeasListIdExportMutationRequest;
  PathParams: PostApiV1IdeasListsByIdeasListIdExportPathParams;
  Errors:
    | PostApiV1IdeasListsByIdeasListIdExport400
    | PostApiV1IdeasListsByIdeasListIdExport401
    | PostApiV1IdeasListsByIdeasListIdExport403
    | PostApiV1IdeasListsByIdeasListIdExport404
    | PostApiV1IdeasListsByIdeasListIdExport500;
};
