/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestResponseSchema } from "./bad-request-response-schema.ts";
import type { ForbiddenResponseSchema } from "./forbidden-response-schema.ts";
import type { InternalServerErrorResponseSchema } from "./internal-server-error-response-schema.ts";
import type { NotFoundResponseSchema } from "./not-found-response-schema.ts";
import type { PaymentRequiredResponseSchema } from "./payment-required-response-schema.ts";
import type { SendVerificationOtpBodySchema } from "./send-verification-otp-body-schema.ts";
import type { SendVerificationOtpResponseSchema } from "./send-verification-otp-response-schema.ts";
import type { UnauthorizedResponseSchema } from "./unauthorized-response-schema.ts";

/**
 * Send verification OTP response
 * @description Verification OTP sent successfully
 */
export type PostApiV1AuthEmailOtpSendVerificationOtp200 =
  SendVerificationOtpResponseSchema;

/**
 * Bad request response
 * @description Bad request
 */
export type PostApiV1AuthEmailOtpSendVerificationOtp400 =
  BadRequestResponseSchema;

/**
 * Unauthorized response
 * @description Unauthorized
 */
export type PostApiV1AuthEmailOtpSendVerificationOtp401 =
  UnauthorizedResponseSchema;

/**
 * Payment required response
 * @description Payment required
 */
export type PostApiV1AuthEmailOtpSendVerificationOtp402 =
  PaymentRequiredResponseSchema;

/**
 * Forbidden response
 * @description Forbidden
 */
export type PostApiV1AuthEmailOtpSendVerificationOtp403 =
  ForbiddenResponseSchema;

/**
 * Not found response
 * @description Not found
 */
export type PostApiV1AuthEmailOtpSendVerificationOtp404 =
  NotFoundResponseSchema;

/**
 * Internal server error response
 * @description Internal server error
 */
export type PostApiV1AuthEmailOtpSendVerificationOtp500 =
  InternalServerErrorResponseSchema;

/**
 * Send verification OTP body
 */
export type PostApiV1AuthEmailOtpSendVerificationOtpMutationRequest =
  SendVerificationOtpBodySchema;

export type PostApiV1AuthEmailOtpSendVerificationOtpMutationResponse =
  PostApiV1AuthEmailOtpSendVerificationOtp200;

export type PostApiV1AuthEmailOtpSendVerificationOtpMutation = {
  Response: PostApiV1AuthEmailOtpSendVerificationOtp200;
  Request: PostApiV1AuthEmailOtpSendVerificationOtpMutationRequest;
  Errors:
    | PostApiV1AuthEmailOtpSendVerificationOtp400
    | PostApiV1AuthEmailOtpSendVerificationOtp401
    | PostApiV1AuthEmailOtpSendVerificationOtp402
    | PostApiV1AuthEmailOtpSendVerificationOtp403
    | PostApiV1AuthEmailOtpSendVerificationOtp404
    | PostApiV1AuthEmailOtpSendVerificationOtp500;
};
