/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Product feature
 * @description Product feature description
 */
export type ProductFeatureSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  icon: string;
  /**
   * @type string
   */
  color: string;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  description: string;
  /**
   * @type boolean
   */
  available: boolean;
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  priority: number;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
