/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Production status
 * @description Production status description
 */
export type ProductionStatusSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  description: string | null;
  icon: string | null;
  color: string | null;
  /**
   * @type boolean
   */
  isDefault: boolean;
  /**
   * @type boolean
   */
  forScenario: boolean;
  /**
   * @type boolean
   */
  forScenarioChapter: boolean;
  /**
   * @minLength -9007199254740991
   * @maxLength 9007199254740991
   * @type integer
   */
  priority: number;
  /**
   * @type string
   */
  slug: string;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
