/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Profile attachment file
 * @description Profile attachment file description
 */
export type ProfileAttachmentFileSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  /**
   * @type string
   */
  fileName: string;
  /**
   * @type string
   */
  mimeType: string;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
  /**
   * @type string
   */
  url: string;
};
