/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Profile channel video
 * @description Profile channel video description
 */
export type ProfileChannelVideoSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  profileId: string;
  /**
   * @type string, uuid
   */
  platformId: string;
  profileChannelId: string | null;
  externalId: string | null;
  url: string | null;
  thumbnailUrl: string | null;
  name: string | null;
  description: string | null;
  likes: number | null;
  views: number | null;
  comments: number | null;
  duration: string | null;
  summary: string | null;
  mainTopics: string[] | null;
  keyPoints: string[] | null;
  tone: string | null;
  targetAudience: string | null;
  quotes: string[] | null;
  timeline: string | null;
  wordCount: number | null;
  segments: number | null;
  transcript: string | null;
  transcriptSegments?: any[] | null;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
