/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const referralRewardSchemaTypeEnum = {
  credits: "credits",
  tariff_discount: "tariff_discount",
} as const;

export type ReferralRewardSchemaTypeEnumKey =
  (typeof referralRewardSchemaTypeEnum)[keyof typeof referralRewardSchemaTypeEnum];

export const referralRewardSchemaUserTypeEnum = {
  referral_source: "referral_source",
  referral_target: "referral_target",
} as const;

export type ReferralRewardSchemaUserTypeEnumKey =
  (typeof referralRewardSchemaUserTypeEnum)[keyof typeof referralRewardSchemaUserTypeEnum];

/**
 * Referral reward
 * @description Referral reward description
 */
export type ReferralRewardSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string
   */
  name: string;
  description: string | null;
  /**
   * @type string
   */
  type: ReferralRewardSchemaTypeEnumKey;
  /**
   * @type string
   */
  userType: ReferralRewardSchemaUserTypeEnumKey;
  /**
   * @minLength -8388608
   * @maxLength 8388607
   * @type number
   */
  value: number;
  /**
   * @type string
   */
  slug: string;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
