/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ScenarioMetadataExtendedSchema } from "./scenario-metadata-extended-schema.ts";

/**
 * Regenerate scenario metadata response
 * @description Regenerate scenario metadata response description
 */
export type RegenerateScenarioMetadataResponseSchema = {
  /**
   * @description Scenario metadata extended description
   * @type object
   */
  data: ScenarioMetadataExtendedSchema;
};
