/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { IdeaSchema } from "./idea-schema.ts";

/**
 * Save idea response
 * @description Save idea response description
 */
export type SaveIdeaResponseSchema = {
  /**
   * @description Idea description
   * @type object
   */
  data: IdeaSchema;
};
