/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const scenarioScenePreviewSchemaStatusEnum = {
  pending: "pending",
  generation: "generation",
  failed: "failed",
  ready: "ready",
} as const;

export type ScenarioScenePreviewSchemaStatusEnumKey =
  (typeof scenarioScenePreviewSchemaStatusEnum)[keyof typeof scenarioScenePreviewSchemaStatusEnum];

/**
 * Scenario scene preview
 * @description Scenario scene preview description
 */
export type ScenarioScenePreviewSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  scenarioSceneId: string;
  attachmentId: string | null;
  compressedAttachmentId: string | null;
  /**
   * @type string
   */
  status: ScenarioScenePreviewSchemaStatusEnumKey;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
  url: string | null;
  urlCompressed: string | null;
};
