/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PlatformSchema } from "./platform-schema.ts";
import type { ProductionStatusSchema } from "./production-status-schema.ts";
import type { ProfileSchema } from "./profile-schema.ts";
import type { ScenarioVersionExtendedSchema } from "./scenario-version-extended-schema.ts";
import type { TemplateSchema } from "./template-schema.ts";
import type { ToneSchema } from "./tone-schema.ts";
import type { VideoDurationSchema } from "./video-duration-schema.ts";
import type { VideoTypeSchema } from "./video-type-schema.ts";

/**
 * Scenario extended
 * @description Scenario extended description
 */
export type ScenarioExtendedSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  profileId: string | null;
  templateId: string | null;
  videoTypeId: string | null;
  videoDurationId: string | null;
  productionStatusId: string | null;
  /**
   * @type boolean
   */
  saved: boolean;
  /**
   * @type string
   */
  name: string;
  /**
   * @type string
   */
  description: string;
  targetAudience: string | null;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
  currentVersion?: ScenarioVersionExtendedSchema | null;
  profile?: ProfileSchema | null;
  template?: TemplateSchema | null;
  videoType?: VideoTypeSchema | null;
  videoDuration?: VideoDurationSchema | null;
  productionStatus?: ProductionStatusSchema | null;
  platforms?: PlatformSchema[] | null;
  tones?: ToneSchema[] | null;
};
