/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Scenario
 * @description Scenario description
 */
export type ScenarioSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  currentVersionId: string | null;
  profileId: string | null;
  templateId: string | null;
  platformId: string | null;
  videoTypeId: string | null;
  videoDurationId: string | null;
  /**
   * @type boolean
   */
  saved: boolean;
  name: string | null;
  description: string | null;
  targetAudience: string | null;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
