/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Send verification OTP response
 * @description Send verification OTP response description
 */
export type SendVerificationOtpResponseSchema = {
  /**
   * @type boolean | undefined
   */
  success?: boolean;
};
