/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const subscriptionSchemaStatusEnum = {
  pending: "pending",
  active: "active",
  overdue: "overdue",
  cancelled: "cancelled",
} as const;

export type SubscriptionSchemaStatusEnumKey =
  (typeof subscriptionSchemaStatusEnum)[keyof typeof subscriptionSchemaStatusEnum];

/**
 * Subscription
 * @description Subscription description
 */
export type SubscriptionSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  /**
   * @type string, uuid
   */
  tariffId: string;
  /**
   * @type string
   */
  startsAt: string;
  endsAt: string | null;
  lastBilledAt: string | null;
  nextBillingAt: string | null;
  status: SubscriptionSchemaStatusEnumKey | null;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
};
