/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TariffSchema } from "./tariff-schema.ts";

export const subscriptionExtendedSchemaStatusEnum = {
  pending: "pending",
  active: "active",
  overdue: "overdue",
  cancelled: "cancelled",
} as const;

export type SubscriptionExtendedSchemaStatusEnumKey =
  (typeof subscriptionExtendedSchemaStatusEnum)[keyof typeof subscriptionExtendedSchemaStatusEnum];

/**
 * Subscription extended
 * @description Subscription extended description
 */
export type SubscriptionExtendedSchema = {
  /**
   * @type string, uuid
   */
  id: string;
  /**
   * @type string, uuid
   */
  userId: string;
  /**
   * @type string, uuid
   */
  tariffId: string;
  /**
   * @type string
   */
  startsAt: string;
  endsAt: string | null;
  lastBilledAt: string | null;
  nextBillingAt: string | null;
  status: SubscriptionExtendedSchemaStatusEnumKey | null;
  /**
   * @type string
   */
  createdAt: string;
  /**
   * @type string
   */
  updatedAt: string;
  /**
   * @description Tariff description
   * @type object
   */
  tariff: TariffSchema;
};
