/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Update scenario chapter body
 * @description Update scenario chapter body description
 */
export type UpdateScenarioChapterBodySchema = {
  /**
   * @minLength 3
   * @maxLength 256
   * @type string
   */
  name: string;
  /**
   * @minLength 16
   * @maxLength 4096
   * @type string
   */
  description: string;
};
