/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Update idea body
 * @description Update idea body description
 */
export type UpdateIdeaBodySchema = {
  /**
   * @type boolean | undefined
   */
  saved?: boolean;
  liked?: boolean | null;
  /**
   * @minLength 3
   * @maxLength 256
   * @type string
   */
  name: string;
  /**
   * @minLength 16
   * @maxLength 4096
   * @type string
   */
  description: string;
  reason?: string | null;
  hook?: string | null;
  /**
   * @minLength 0
   * @maxLength 5
   * @type integer | undefined
   */
  complexity?: number;
  /**
   * @minLength 0
   * @maxLength 5
   * @type integer | undefined
   */
  potential?: number;
};
