/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Update scenario body
 * @description Update scenario body description
 */
export type UpdateScenarioBodySchema = {
  /**
   * @minLength 3
   * @maxLength 256
   * @type string
   */
  name: string;
  /**
   * @minLength 16
   * @maxLength 4096
   * @type string
   */
  description: string;
  templateId?: string | null;
  videoTypeId?: string | null;
  videoDurationId?: string | null;
  profileId?: string | null;
  productionStatusId?: string | null;
  targetAudience?: string | null;
  platformIds?: string[] | null;
  toneIds?: string[] | null;
  regenerate?: boolean | null;
};
