/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { IdeasListSchema } from "./ideas-list-schema.ts";

/**
 * Update ideas list response
 * @description Update ideas list response description
 */
export type UpdateIdeasListResponseSchema = {
  /**
   * @description IdeasList description
   * @type object
   */
  data: IdeasListSchema;
};
