/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ScenarioSchema } from "./scenario-schema.ts";

/**
 * Update scenario current version response
 * @description Update scenario current version response description
 */
export type UpdateScenarioCurrentVersionResponseSchema = {
  /**
   * @description Scenario description
   * @type object
   */
  data: ScenarioSchema;
};
