/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Update user body
 * @description Update user body description
 */
export type UpdateUserBodySchema = {
  /**
   * @minLength 1
   * @type string | undefined
   */
  name?: string;
  /**
   * @type string | undefined
   */
  image?: string;
};
