/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Update scenario scene component body
 * @description Update scenario scene component body description
 */
export type UpdateScenarioSceneComponentBodySchema = {
  /**
   * @type string | undefined
   */
  name?: string;
  content?: string | null;
  icon?: string | null;
  color?: string | null;
};
