/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  DeleteApiV1ScenariosVersionsByVersionId400,
  DeleteApiV1ScenariosVersionsByVersionId401,
  DeleteApiV1ScenariosVersionsByVersionId402,
  DeleteApiV1ScenariosVersionsByVersionId403,
  DeleteApiV1ScenariosVersionsByVersionId404,
  DeleteApiV1ScenariosVersionsByVersionId500,
  DeleteApiV1ScenariosVersionsByVersionIdMutationResponse,
  DeleteApiV1ScenariosVersionsByVersionIdPathParams,
} from "../models/delete-api-v1-scenarios-versions-by-version-id.ts";

function getDeleteApiV1ScenariosVersionsByVersionIdUrl({
  versionId,
}: {
  versionId: DeleteApiV1ScenariosVersionsByVersionIdPathParams["versionId"];
}) {
  const res = {
    method: "DELETE",
    url: `/api/v1/scenarios/versions/${versionId}` as const,
  };
  return res;
}

/**
 * {@link /api/v1/scenarios/versions/:versionId}
 */
export async function deleteApiV1ScenariosVersionsByVersionId(
  {
    versionId,
  }: {
    versionId: DeleteApiV1ScenariosVersionsByVersionIdPathParams["versionId"];
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteApiV1ScenariosVersionsByVersionIdMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1ScenariosVersionsByVersionId400
      | DeleteApiV1ScenariosVersionsByVersionId401
      | DeleteApiV1ScenariosVersionsByVersionId402
      | DeleteApiV1ScenariosVersionsByVersionId403
      | DeleteApiV1ScenariosVersionsByVersionId404
      | DeleteApiV1ScenariosVersionsByVersionId500
    >,
    unknown
  >({
    method: "DELETE",
    url: getDeleteApiV1ScenariosVersionsByVersionIdUrl({
      versionId,
    }).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
