/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  DeleteApiV1ScenariosChaptersByChapterId400,
  DeleteApiV1ScenariosChaptersByChapterId401,
  DeleteApiV1ScenariosChaptersByChapterId403,
  DeleteApiV1ScenariosChaptersByChapterId404,
  DeleteApiV1ScenariosChaptersByChapterId500,
  DeleteApiV1ScenariosChaptersByChapterIdMutationResponse,
  DeleteApiV1ScenariosChaptersByChapterIdPathParams,
} from "../models/delete-api-v1-scenarios-chapters-by-chapter-id.ts";
import { deleteApiV1ScenariosChaptersByChapterIdMutationResponseSchema } from "../zod/delete-api-v1-scenarios-chapters-by-chapter-id-schema.ts";

function getDeleteApiV1ScenariosChaptersByChapterIdUrl({
  chapterId,
}: {
  chapterId: DeleteApiV1ScenariosChaptersByChapterIdPathParams["chapterId"];
}) {
  const res = {
    method: "DELETE",
    url: `/api/v1/scenarios/chapters/${chapterId}` as const,
  };
  return res;
}

/**
 * {@link /api/v1/scenarios/chapters/:chapterId}
 */
export async function deleteApiV1ScenariosChaptersByChapterId(
  {
    chapterId,
  }: {
    chapterId: DeleteApiV1ScenariosChaptersByChapterIdPathParams["chapterId"];
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteApiV1ScenariosChaptersByChapterIdMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1ScenariosChaptersByChapterId400
      | DeleteApiV1ScenariosChaptersByChapterId401
      | DeleteApiV1ScenariosChaptersByChapterId403
      | DeleteApiV1ScenariosChaptersByChapterId404
      | DeleteApiV1ScenariosChaptersByChapterId500
    >,
    unknown
  >({
    method: "DELETE",
    url: getDeleteApiV1ScenariosChaptersByChapterIdUrl({
      chapterId,
    }).url.toString(),
    ...requestConfig,
  });
  return deleteApiV1ScenariosChaptersByChapterIdMutationResponseSchema.parse(
    res.data,
  );
}
