/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  GetApiV1IdeasListsByIdeasListId400,
  GetApiV1IdeasListsByIdeasListId401,
  GetApiV1IdeasListsByIdeasListId402,
  GetApiV1IdeasListsByIdeasListId403,
  GetApiV1IdeasListsByIdeasListId404,
  GetApiV1IdeasListsByIdeasListId500,
  GetApiV1IdeasListsByIdeasListIdPathParams,
  GetApiV1IdeasListsByIdeasListIdQueryParams,
  GetApiV1IdeasListsByIdeasListIdQueryResponse,
} from "../models/get-api-v1-ideas-lists-by-ideas-list-id.ts";

function getGetApiV1IdeasListsByIdeasListIdUrl({
  ideasListId,
}: {
  ideasListId: GetApiV1IdeasListsByIdeasListIdPathParams["ideasListId"];
}) {
  const res = {
    method: "GET",
    url: `/api/v1/ideas-lists/${ideasListId}` as const,
  };
  return res;
}

/**
 * {@link /api/v1/ideas-lists/:ideasListId}
 */
export async function getApiV1IdeasListsByIdeasListId(
  {
    ideasListId,
    params,
  }: {
    ideasListId: GetApiV1IdeasListsByIdeasListIdPathParams["ideasListId"];
    params?: GetApiV1IdeasListsByIdeasListIdQueryParams;
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1IdeasListsByIdeasListIdQueryResponse,
    ResponseErrorConfig<
      | GetApiV1IdeasListsByIdeasListId400
      | GetApiV1IdeasListsByIdeasListId401
      | GetApiV1IdeasListsByIdeasListId402
      | GetApiV1IdeasListsByIdeasListId403
      | GetApiV1IdeasListsByIdeasListId404
      | GetApiV1IdeasListsByIdeasListId500
    >,
    unknown
  >({
    method: "GET",
    url: getGetApiV1IdeasListsByIdeasListIdUrl({ ideasListId }).url.toString(),
    params,
    ...requestConfig,
  });
  return res.data;
}
