/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  GetApiV1IdeasListsFilters400,
  GetApiV1IdeasListsFilters401,
  GetApiV1IdeasListsFilters402,
  GetApiV1IdeasListsFilters403,
  GetApiV1IdeasListsFilters404,
  GetApiV1IdeasListsFilters500,
  GetApiV1IdeasListsFiltersQueryResponse,
} from "../models/get-api-v1-ideas-lists-filters.ts";

function getGetApiV1IdeasListsFiltersUrl() {
  const res = { method: "GET", url: `/api/v1/ideas-lists/filters` as const };
  return res;
}

/**
 * {@link /api/v1/ideas-lists/filters}
 */
export async function getApiV1IdeasListsFilters(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1IdeasListsFiltersQueryResponse,
    ResponseErrorConfig<
      | GetApiV1IdeasListsFilters400
      | GetApiV1IdeasListsFilters401
      | GetApiV1IdeasListsFilters402
      | GetApiV1IdeasListsFilters403
      | GetApiV1IdeasListsFilters404
      | GetApiV1IdeasListsFilters500
    >,
    unknown
  >({
    method: "GET",
    url: getGetApiV1IdeasListsFiltersUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
