/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  GetApiV1ProfilesByProfileId400,
  GetApiV1ProfilesByProfileId401,
  GetApiV1ProfilesByProfileId403,
  GetApiV1ProfilesByProfileId404,
  GetApiV1ProfilesByProfileId500,
  GetApiV1ProfilesByProfileIdPathParams,
  GetApiV1ProfilesByProfileIdQueryResponse,
} from "../models/get-api-v1-profiles-by-profile-id.ts";
import { getApiV1ProfilesByProfileIdQueryResponseSchema } from "../zod/get-api-v1-profiles-by-profile-id-schema.ts";

function getGetApiV1ProfilesByProfileIdUrl({
  profileId,
}: {
  profileId: GetApiV1ProfilesByProfileIdPathParams["profileId"];
}) {
  const res = { method: "GET", url: `/api/v1/profiles/${profileId}` as const };
  return res;
}

/**
 * {@link /api/v1/profiles/:profileId}
 */
export async function getApiV1ProfilesByProfileId(
  {
    profileId,
  }: { profileId: GetApiV1ProfilesByProfileIdPathParams["profileId"] },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1ProfilesByProfileIdQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ProfilesByProfileId400
      | GetApiV1ProfilesByProfileId401
      | GetApiV1ProfilesByProfileId403
      | GetApiV1ProfilesByProfileId404
      | GetApiV1ProfilesByProfileId500
    >,
    unknown
  >({
    method: "GET",
    url: getGetApiV1ProfilesByProfileIdUrl({ profileId }).url.toString(),
    ...requestConfig,
  });
  return getApiV1ProfilesByProfileIdQueryResponseSchema.parse(res.data);
}
