/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  GetApiV1ScenariosChaptersByChapterId400,
  GetApiV1ScenariosChaptersByChapterId401,
  GetApiV1ScenariosChaptersByChapterId402,
  GetApiV1ScenariosChaptersByChapterId403,
  GetApiV1ScenariosChaptersByChapterId404,
  GetApiV1ScenariosChaptersByChapterId500,
  GetApiV1ScenariosChaptersByChapterIdPathParams,
  GetApiV1ScenariosChaptersByChapterIdQueryResponse,
} from "../models/get-api-v1-scenarios-chapters-by-chapter-id.ts";
import { getApiV1ScenariosChaptersByChapterIdQueryResponseSchema } from "../zod/get-api-v1-scenarios-chapters-by-chapter-id-schema.ts";

function getGetApiV1ScenariosChaptersByChapterIdUrl({
  chapterId,
}: {
  chapterId: GetApiV1ScenariosChaptersByChapterIdPathParams["chapterId"];
}) {
  const res = {
    method: "GET",
    url: `/api/v1/scenarios/chapters/${chapterId}` as const,
  };
  return res;
}

/**
 * {@link /api/v1/scenarios/chapters/:chapterId}
 */
export async function getApiV1ScenariosChaptersByChapterId(
  {
    chapterId,
  }: { chapterId: GetApiV1ScenariosChaptersByChapterIdPathParams["chapterId"] },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1ScenariosChaptersByChapterIdQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ScenariosChaptersByChapterId400
      | GetApiV1ScenariosChaptersByChapterId401
      | GetApiV1ScenariosChaptersByChapterId402
      | GetApiV1ScenariosChaptersByChapterId403
      | GetApiV1ScenariosChaptersByChapterId404
      | GetApiV1ScenariosChaptersByChapterId500
    >,
    unknown
  >({
    method: "GET",
    url: getGetApiV1ScenariosChaptersByChapterIdUrl({
      chapterId,
    }).url.toString(),
    ...requestConfig,
  });
  return getApiV1ScenariosChaptersByChapterIdQueryResponseSchema.parse(
    res.data,
  );
}
