/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  GetApiV1ProductFeatures400,
  GetApiV1ProductFeatures401,
  GetApiV1ProductFeatures402,
  GetApiV1ProductFeatures403,
  GetApiV1ProductFeatures404,
  GetApiV1ProductFeatures500,
  GetApiV1ProductFeaturesQueryResponse,
} from "../models/get-api-v1-product-features.ts";

function getGetApiV1ProductFeaturesUrl() {
  const res = { method: "GET", url: `/api/v1/product-features` as const };
  return res;
}

/**
 * {@link /api/v1/product-features}
 */
export async function getApiV1ProductFeatures(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1ProductFeaturesQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ProductFeatures400
      | GetApiV1ProductFeatures401
      | GetApiV1ProductFeatures402
      | GetApiV1ProductFeatures403
      | GetApiV1ProductFeatures404
      | GetApiV1ProductFeatures500
    >,
    unknown
  >({
    method: "GET",
    url: getGetApiV1ProductFeaturesUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
