/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import type {
  GetApiV1IdeasListsIdeasListId400,
  GetApiV1IdeasListsIdeasListId401,
  GetApiV1IdeasListsIdeasListId403,
  GetApiV1IdeasListsIdeasListId404,
  GetApiV1IdeasListsIdeasListId500,
  GetApiV1IdeasListsIdeasListIdPathParams,
  GetApiV1IdeasListsIdeasListIdQueryParams,
  GetApiV1IdeasListsIdeasListIdQueryResponse,
} from "../models/get-api-v1-ideas-lists-ideas-list-id.ts";
import { getApiV1IdeasListsIdeasListIdQueryResponseSchema } from "../zod/get-api-v1-ideas-lists-ideas-list-id-schema.ts";

function getGetApiV1IdeasListsIdeasListIdUrl({
  ideasListId,
}: {
  ideasListId: GetApiV1IdeasListsIdeasListIdPathParams["ideasListId"];
}) {
  const res = {
    method: "GET",
    url: `/api/v1/ideas-lists/${ideasListId}` as const,
  };
  return res;
}

/**
 * {@link /api/v1/ideas-lists/:ideasListId}
 */
export async function getApiV1IdeasListsIdeasListId(
  {
    ideasListId,
    params,
  }: {
    ideasListId: GetApiV1IdeasListsIdeasListIdPathParams["ideasListId"];
    params?: GetApiV1IdeasListsIdeasListIdQueryParams;
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1IdeasListsIdeasListIdQueryResponse,
    ResponseErrorConfig<
      | GetApiV1IdeasListsIdeasListId400
      | GetApiV1IdeasListsIdeasListId401
      | GetApiV1IdeasListsIdeasListId403
      | GetApiV1IdeasListsIdeasListId404
      | GetApiV1IdeasListsIdeasListId500
    >,
    unknown
  >({
    method: "GET",
    url: getGetApiV1IdeasListsIdeasListIdUrl({ ideasListId }).url.toString(),
    params,
    ...requestConfig,
  });
  return getApiV1IdeasListsIdeasListIdQueryResponseSchema.parse(res.data);
}
