/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  GetApiV1BillingPaymentMethodsMy400,
  GetApiV1BillingPaymentMethodsMy401,
  GetApiV1BillingPaymentMethodsMy402,
  GetApiV1BillingPaymentMethodsMy403,
  GetApiV1BillingPaymentMethodsMy404,
  GetApiV1BillingPaymentMethodsMy500,
  GetApiV1BillingPaymentMethodsMyQueryResponse,
} from "../models/get-api-v1-billing-payment-methods-my.ts";

function getGetApiV1BillingPaymentMethodsMyUrl() {
  const res = {
    method: "GET",
    url: `/api/v1/billing/payment-methods/my` as const,
  };
  return res;
}

/**
 * {@link /api/v1/billing/payment-methods/my}
 */
export async function getApiV1BillingPaymentMethodsMy(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1BillingPaymentMethodsMyQueryResponse,
    ResponseErrorConfig<
      | GetApiV1BillingPaymentMethodsMy400
      | GetApiV1BillingPaymentMethodsMy401
      | GetApiV1BillingPaymentMethodsMy402
      | GetApiV1BillingPaymentMethodsMy403
      | GetApiV1BillingPaymentMethodsMy404
      | GetApiV1BillingPaymentMethodsMy500
    >,
    unknown
  >({
    method: "GET",
    url: getGetApiV1BillingPaymentMethodsMyUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
