/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  GetApiV1ProfilesChannelsPlatforms400,
  GetApiV1ProfilesChannelsPlatforms401,
  GetApiV1ProfilesChannelsPlatforms402,
  GetApiV1ProfilesChannelsPlatforms403,
  GetApiV1ProfilesChannelsPlatforms404,
  GetApiV1ProfilesChannelsPlatforms500,
  GetApiV1ProfilesChannelsPlatformsQueryResponse,
} from "../models/get-api-v1-profiles-channels-platforms.ts";

function getGetApiV1ProfilesChannelsPlatformsUrl() {
  const res = {
    method: "GET",
    url: `/api/v1/profiles/channels/platforms` as const,
  };
  return res;
}

/**
 * {@link /api/v1/profiles/channels/platforms}
 */
export async function getApiV1ProfilesChannelsPlatforms(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1ProfilesChannelsPlatformsQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ProfilesChannelsPlatforms400
      | GetApiV1ProfilesChannelsPlatforms401
      | GetApiV1ProfilesChannelsPlatforms402
      | GetApiV1ProfilesChannelsPlatforms403
      | GetApiV1ProfilesChannelsPlatforms404
      | GetApiV1ProfilesChannelsPlatforms500
    >,
    unknown
  >({
    method: "GET",
    url: getGetApiV1ProfilesChannelsPlatformsUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
