/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  GetApiV1BillingPaymentsByPaymentId400,
  GetApiV1BillingPaymentsByPaymentId401,
  GetApiV1BillingPaymentsByPaymentId402,
  GetApiV1BillingPaymentsByPaymentId403,
  GetApiV1BillingPaymentsByPaymentId404,
  GetApiV1BillingPaymentsByPaymentId500,
  GetApiV1BillingPaymentsByPaymentIdPathParams,
  GetApiV1BillingPaymentsByPaymentIdQueryResponse,
} from "../models/get-api-v1-billing-payments-by-payment-id.ts";

function getGetApiV1BillingPaymentsByPaymentIdUrl({
  paymentId,
}: {
  paymentId: GetApiV1BillingPaymentsByPaymentIdPathParams["paymentId"];
}) {
  const res = {
    method: "GET",
    url: `/api/v1/billing/payments/${paymentId}` as const,
  };
  return res;
}

/**
 * {@link /api/v1/billing/payments/:paymentId}
 */
export async function getApiV1BillingPaymentsByPaymentId(
  {
    paymentId,
  }: { paymentId: GetApiV1BillingPaymentsByPaymentIdPathParams["paymentId"] },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1BillingPaymentsByPaymentIdQueryResponse,
    ResponseErrorConfig<
      | GetApiV1BillingPaymentsByPaymentId400
      | GetApiV1BillingPaymentsByPaymentId401
      | GetApiV1BillingPaymentsByPaymentId402
      | GetApiV1BillingPaymentsByPaymentId403
      | GetApiV1BillingPaymentsByPaymentId404
      | GetApiV1BillingPaymentsByPaymentId500
    >,
    unknown
  >({
    method: "GET",
    url: getGetApiV1BillingPaymentsByPaymentIdUrl({ paymentId }).url.toString(),
    ...requestConfig,
  });
  return res.data;
}
