/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import type {
  GetApiV1ReferralInfo400,
  GetApiV1ReferralInfo401,
  GetApiV1ReferralInfo403,
  GetApiV1ReferralInfo404,
  GetApiV1ReferralInfo500,
  GetApiV1ReferralInfoQueryResponse,
} from "../models/get-api-v1-referral-info.ts";
import { getApiV1ReferralInfoQueryResponseSchema } from "../zod/get-api-v1-referral-info-schema.ts";

function getGetApiV1ReferralInfoUrl() {
  const res = { method: "GET", url: `/api/v1/referral/info` as const };
  return res;
}

/**
 * {@link /api/v1/referral/info}
 */
export async function getApiV1ReferralInfo(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1ReferralInfoQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ReferralInfo400
      | GetApiV1ReferralInfo401
      | GetApiV1ReferralInfo403
      | GetApiV1ReferralInfo404
      | GetApiV1ReferralInfo500
    >,
    unknown
  >({
    method: "GET",
    url: getGetApiV1ReferralInfoUrl().url.toString(),
    ...requestConfig,
  });
  return getApiV1ReferralInfoQueryResponseSchema.parse(res.data);
}
