/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import type {
  GetApiV1AttachmentsByAttachmentIdDownload400,
  GetApiV1AttachmentsByAttachmentIdDownload401,
  GetApiV1AttachmentsByAttachmentIdDownload403,
  GetApiV1AttachmentsByAttachmentIdDownload404,
  GetApiV1AttachmentsByAttachmentIdDownload500,
  GetApiV1AttachmentsByAttachmentIdDownloadPathParams,
  GetApiV1AttachmentsByAttachmentIdDownloadQueryResponse,
} from "../models/get-api-v1-attachments-by-attachment-id-download.ts";
import { getApiV1AttachmentsByAttachmentIdDownloadQueryResponseSchema } from "../zod/get-api-v1-attachments-by-attachment-id-download-schema.ts";

function getGetApiV1AttachmentsByAttachmentIdDownloadUrl({
  attachmentId,
}: {
  attachmentId: GetApiV1AttachmentsByAttachmentIdDownloadPathParams["attachmentId"];
}) {
  const res = {
    method: "GET",
    url: `/api/v1/attachments/${attachmentId}/download` as const,
  };
  return res;
}

/**
 * {@link /api/v1/attachments/:attachmentId/download}
 */
export async function getApiV1AttachmentsByAttachmentIdDownload(
  {
    attachmentId,
  }: {
    attachmentId: GetApiV1AttachmentsByAttachmentIdDownloadPathParams["attachmentId"];
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetApiV1AttachmentsByAttachmentIdDownloadQueryResponse,
    ResponseErrorConfig<
      | GetApiV1AttachmentsByAttachmentIdDownload400
      | GetApiV1AttachmentsByAttachmentIdDownload401
      | GetApiV1AttachmentsByAttachmentIdDownload403
      | GetApiV1AttachmentsByAttachmentIdDownload404
      | GetApiV1AttachmentsByAttachmentIdDownload500
    >,
    unknown
  >({
    method: "GET",
    url: getGetApiV1AttachmentsByAttachmentIdDownloadUrl({
      attachmentId,
    }).url.toString(),
    ...requestConfig,
  });
  return getApiV1AttachmentsByAttachmentIdDownloadQueryResponseSchema.parse(
    res.data,
  );
}
