/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  PatchApiV1AuthUser400,
  PatchApiV1AuthUser401,
  PatchApiV1AuthUser402,
  PatchApiV1AuthUser403,
  PatchApiV1AuthUser404,
  PatchApiV1AuthUser500,
  PatchApiV1AuthUserMutationRequest,
  PatchApiV1AuthUserMutationResponse,
} from "../models/patch-api-v1-auth-user.ts";

function getPatchApiV1AuthUserUrl() {
  const res = { method: "PATCH", url: `/api/v1/auth/user` as const };
  return res;
}

/**
 * {@link /api/v1/auth/user}
 */
export async function patchApiV1AuthUser(
  { data }: { data: PatchApiV1AuthUserMutationRequest },
  config: Partial<RequestConfig<PatchApiV1AuthUserMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchApiV1AuthUserMutationResponse,
    ResponseErrorConfig<
      | PatchApiV1AuthUser400
      | PatchApiV1AuthUser401
      | PatchApiV1AuthUser402
      | PatchApiV1AuthUser403
      | PatchApiV1AuthUser404
      | PatchApiV1AuthUser500
    >,
    PatchApiV1AuthUserMutationRequest
  >({
    method: "PATCH",
    url: getPatchApiV1AuthUserUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
