/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import type {
  PatchApiV1IdeasIdeaId400,
  PatchApiV1IdeasIdeaId401,
  PatchApiV1IdeasIdeaId403,
  PatchApiV1IdeasIdeaId404,
  PatchApiV1IdeasIdeaId500,
  PatchApiV1IdeasIdeaIdMutationRequest,
  PatchApiV1IdeasIdeaIdMutationResponse,
  PatchApiV1IdeasIdeaIdPathParams,
} from "../models/patch-api-v1-ideas-idea-id.ts";
import {
  patchApiV1IdeasIdeaIdMutationRequestSchema,
  patchApiV1IdeasIdeaIdMutationResponseSchema,
} from "../zod/patch-api-v1-ideas-idea-id-schema.ts";

function getPatchApiV1IdeasIdeaIdUrl({
  ideaId,
}: {
  ideaId: PatchApiV1IdeasIdeaIdPathParams["ideaId"];
}) {
  const res = { method: "PATCH", url: `/api/v1/ideas/${ideaId}` as const };
  return res;
}

/**
 * {@link /api/v1/ideas/:ideaId}
 */
export async function patchApiV1IdeasIdeaId(
  {
    ideaId,
    data,
  }: {
    ideaId: PatchApiV1IdeasIdeaIdPathParams["ideaId"];
    data?: PatchApiV1IdeasIdeaIdMutationRequest;
  },
  config: Partial<RequestConfig<PatchApiV1IdeasIdeaIdMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = patchApiV1IdeasIdeaIdMutationRequestSchema.parse(data);

  const res = await request<
    PatchApiV1IdeasIdeaIdMutationResponse,
    ResponseErrorConfig<
      | PatchApiV1IdeasIdeaId400
      | PatchApiV1IdeasIdeaId401
      | PatchApiV1IdeasIdeaId403
      | PatchApiV1IdeasIdeaId404
      | PatchApiV1IdeasIdeaId500
    >,
    PatchApiV1IdeasIdeaIdMutationRequest
  >({
    method: "PATCH",
    url: getPatchApiV1IdeasIdeaIdUrl({ ideaId }).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return patchApiV1IdeasIdeaIdMutationResponseSchema.parse(res.data);
}
