/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import type {
  PatchApiV1ScenariosScenarioId400,
  PatchApiV1ScenariosScenarioId401,
  PatchApiV1ScenariosScenarioId403,
  PatchApiV1ScenariosScenarioId404,
  PatchApiV1ScenariosScenarioId500,
  PatchApiV1ScenariosScenarioIdMutationRequest,
  PatchApiV1ScenariosScenarioIdMutationResponse,
  PatchApiV1ScenariosScenarioIdPathParams,
} from "../models/patch-api-v1-scenarios-scenario-id.ts";
import {
  patchApiV1ScenariosScenarioIdMutationRequestSchema,
  patchApiV1ScenariosScenarioIdMutationResponseSchema,
} from "../zod/patch-api-v1-scenarios-scenario-id-schema.ts";

function getPatchApiV1ScenariosScenarioIdUrl({
  scenarioId,
}: {
  scenarioId: PatchApiV1ScenariosScenarioIdPathParams["scenarioId"];
}) {
  const res = {
    method: "PATCH",
    url: `/api/v1/scenarios/${scenarioId}` as const,
  };
  return res;
}

/**
 * {@link /api/v1/scenarios/:scenarioId}
 */
export async function patchApiV1ScenariosScenarioId(
  {
    scenarioId,
    data,
  }: {
    scenarioId: PatchApiV1ScenariosScenarioIdPathParams["scenarioId"];
    data?: PatchApiV1ScenariosScenarioIdMutationRequest;
  },
  config: Partial<
    RequestConfig<PatchApiV1ScenariosScenarioIdMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData =
    patchApiV1ScenariosScenarioIdMutationRequestSchema.parse(data);

  const res = await request<
    PatchApiV1ScenariosScenarioIdMutationResponse,
    ResponseErrorConfig<
      | PatchApiV1ScenariosScenarioId400
      | PatchApiV1ScenariosScenarioId401
      | PatchApiV1ScenariosScenarioId403
      | PatchApiV1ScenariosScenarioId404
      | PatchApiV1ScenariosScenarioId500
    >,
    PatchApiV1ScenariosScenarioIdMutationRequest
  >({
    method: "PATCH",
    url: getPatchApiV1ScenariosScenarioIdUrl({ scenarioId }).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return patchApiV1ScenariosScenarioIdMutationResponseSchema.parse(res.data);
}
