/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import type {
  PatchApiV1ScenariosScenarioIdSave400,
  PatchApiV1ScenariosScenarioIdSave401,
  PatchApiV1ScenariosScenarioIdSave403,
  PatchApiV1ScenariosScenarioIdSave404,
  PatchApiV1ScenariosScenarioIdSave500,
  PatchApiV1ScenariosScenarioIdSaveMutationRequest,
  PatchApiV1ScenariosScenarioIdSaveMutationResponse,
  PatchApiV1ScenariosScenarioIdSavePathParams,
} from "../models/patch-api-v1-scenarios-scenario-id-save.ts";
import {
  patchApiV1ScenariosScenarioIdSaveMutationRequestSchema,
  patchApiV1ScenariosScenarioIdSaveMutationResponseSchema,
} from "../zod/patch-api-v1-scenarios-scenario-id-save-schema.ts";

function getPatchApiV1ScenariosScenarioIdSaveUrl({
  scenarioId,
}: {
  scenarioId: PatchApiV1ScenariosScenarioIdSavePathParams["scenarioId"];
}) {
  const res = {
    method: "PATCH",
    url: `/api/v1/scenarios/${scenarioId}/save` as const,
  };
  return res;
}

/**
 * {@link /api/v1/scenarios/:scenarioId/save}
 */
export async function patchApiV1ScenariosScenarioIdSave(
  {
    scenarioId,
    data,
  }: {
    scenarioId: PatchApiV1ScenariosScenarioIdSavePathParams["scenarioId"];
    data: PatchApiV1ScenariosScenarioIdSaveMutationRequest;
  },
  config: Partial<
    RequestConfig<PatchApiV1ScenariosScenarioIdSaveMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData =
    patchApiV1ScenariosScenarioIdSaveMutationRequestSchema.parse(data);

  const res = await request<
    PatchApiV1ScenariosScenarioIdSaveMutationResponse,
    ResponseErrorConfig<
      | PatchApiV1ScenariosScenarioIdSave400
      | PatchApiV1ScenariosScenarioIdSave401
      | PatchApiV1ScenariosScenarioIdSave403
      | PatchApiV1ScenariosScenarioIdSave404
      | PatchApiV1ScenariosScenarioIdSave500
    >,
    PatchApiV1ScenariosScenarioIdSaveMutationRequest
  >({
    method: "PATCH",
    url: getPatchApiV1ScenariosScenarioIdSaveUrl({ scenarioId }).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return patchApiV1ScenariosScenarioIdSaveMutationResponseSchema.parse(
    res.data,
  );
}
