/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  PostApiV1IdeasListsByIdeasListIdExport400,
  PostApiV1IdeasListsByIdeasListIdExport401,
  PostApiV1IdeasListsByIdeasListIdExport403,
  PostApiV1IdeasListsByIdeasListIdExport404,
  PostApiV1IdeasListsByIdeasListIdExport500,
  PostApiV1IdeasListsByIdeasListIdExportMutationRequest,
  PostApiV1IdeasListsByIdeasListIdExportMutationResponse,
  PostApiV1IdeasListsByIdeasListIdExportPathParams,
} from "../models/post-api-v1-ideas-lists-by-ideas-list-id-export.ts";
import {
  postApiV1IdeasListsByIdeasListIdExportMutationRequestSchema,
  postApiV1IdeasListsByIdeasListIdExportMutationResponseSchema,
} from "../zod/post-api-v1-ideas-lists-by-ideas-list-id-export-schema.ts";

function getPostApiV1IdeasListsByIdeasListIdExportUrl({
  ideasListId,
}: {
  ideasListId: PostApiV1IdeasListsByIdeasListIdExportPathParams["ideasListId"];
}) {
  const res = {
    method: "POST",
    url: `/api/v1/ideas-lists/${ideasListId}/export` as const,
  };
  return res;
}

/**
 * {@link /api/v1/ideas-lists/:ideasListId/export}
 */
export async function postApiV1IdeasListsByIdeasListIdExport(
  {
    ideasListId,
    data,
  }: {
    ideasListId: PostApiV1IdeasListsByIdeasListIdExportPathParams["ideasListId"];
    data: PostApiV1IdeasListsByIdeasListIdExportMutationRequest;
  },
  config: Partial<
    RequestConfig<PostApiV1IdeasListsByIdeasListIdExportMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData =
    postApiV1IdeasListsByIdeasListIdExportMutationRequestSchema.parse(data);

  const res = await request<
    PostApiV1IdeasListsByIdeasListIdExportMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsByIdeasListIdExport400
      | PostApiV1IdeasListsByIdeasListIdExport401
      | PostApiV1IdeasListsByIdeasListIdExport403
      | PostApiV1IdeasListsByIdeasListIdExport404
      | PostApiV1IdeasListsByIdeasListIdExport500
    >,
    PostApiV1IdeasListsByIdeasListIdExportMutationRequest
  >({
    method: "POST",
    url: getPostApiV1IdeasListsByIdeasListIdExportUrl({
      ideasListId,
    }).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return postApiV1IdeasListsByIdeasListIdExportMutationResponseSchema.parse(
    res.data,
  );
}
