/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  PostApiV1AuthSignOut400,
  PostApiV1AuthSignOut401,
  PostApiV1AuthSignOut402,
  PostApiV1AuthSignOut403,
  PostApiV1AuthSignOut404,
  PostApiV1AuthSignOut500,
  PostApiV1AuthSignOutMutationResponse,
} from "../models/post-api-v1-auth-sign-out.ts";

function getPostApiV1AuthSignOutUrl() {
  const res = { method: "POST", url: `/api/v1/auth/sign-out` as const };
  return res;
}

/**
 * {@link /api/v1/auth/sign-out}
 */
export async function postApiV1AuthSignOut(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostApiV1AuthSignOutMutationResponse,
    ResponseErrorConfig<
      | PostApiV1AuthSignOut400
      | PostApiV1AuthSignOut401
      | PostApiV1AuthSignOut402
      | PostApiV1AuthSignOut403
      | PostApiV1AuthSignOut404
      | PostApiV1AuthSignOut500
    >,
    unknown
  >({
    method: "POST",
    url: getPostApiV1AuthSignOutUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
