/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  PostApiV1ProfilesChannels400,
  PostApiV1ProfilesChannels401,
  PostApiV1ProfilesChannels402,
  PostApiV1ProfilesChannels403,
  PostApiV1ProfilesChannels404,
  PostApiV1ProfilesChannels500,
  PostApiV1ProfilesChannelsMutationRequest,
  PostApiV1ProfilesChannelsMutationResponse,
} from "../models/post-api-v1-profiles-channels.ts";
import {
  postApiV1ProfilesChannelsMutationRequestSchema,
  postApiV1ProfilesChannelsMutationResponseSchema,
} from "../zod/post-api-v1-profiles-channels-schema.ts";

function getPostApiV1ProfilesChannelsUrl() {
  const res = { method: "POST", url: `/api/v1/profiles/channels` as const };
  return res;
}

/**
 * {@link /api/v1/profiles/channels}
 */
export async function postApiV1ProfilesChannels(
  { data }: { data: PostApiV1ProfilesChannelsMutationRequest },
  config: Partial<RequestConfig<PostApiV1ProfilesChannelsMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData =
    postApiV1ProfilesChannelsMutationRequestSchema.parse(data);

  const res = await request<
    PostApiV1ProfilesChannelsMutationResponse,
    ResponseErrorConfig<
      | PostApiV1ProfilesChannels400
      | PostApiV1ProfilesChannels401
      | PostApiV1ProfilesChannels402
      | PostApiV1ProfilesChannels403
      | PostApiV1ProfilesChannels404
      | PostApiV1ProfilesChannels500
    >,
    PostApiV1ProfilesChannelsMutationRequest
  >({
    method: "POST",
    url: getPostApiV1ProfilesChannelsUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return postApiV1ProfilesChannelsMutationResponseSchema.parse(res.data);
}
