/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import type {
  PostApiV1ScenariosVersionsByVersionIdExports400,
  PostApiV1ScenariosVersionsByVersionIdExports401,
  PostApiV1ScenariosVersionsByVersionIdExports403,
  PostApiV1ScenariosVersionsByVersionIdExports404,
  PostApiV1ScenariosVersionsByVersionIdExports500,
  PostApiV1ScenariosVersionsByVersionIdExportsMutationRequest,
  PostApiV1ScenariosVersionsByVersionIdExportsMutationResponse,
  PostApiV1ScenariosVersionsByVersionIdExportsPathParams,
} from "../models/post-api-v1-scenarios-versions-by-version-id-exports.ts";
import {
  postApiV1ScenariosVersionsByVersionIdExportsMutationRequestSchema,
  postApiV1ScenariosVersionsByVersionIdExportsMutationResponseSchema,
} from "../zod/post-api-v1-scenarios-versions-by-version-id-exports-schema.ts";

function getPostApiV1ScenariosVersionsByVersionIdExportsUrl({
  versionId,
}: {
  versionId: PostApiV1ScenariosVersionsByVersionIdExportsPathParams["versionId"];
}) {
  const res = {
    method: "POST",
    url: `/api/v1/scenarios/versions/${versionId}/exports` as const,
  };
  return res;
}

/**
 * {@link /api/v1/scenarios/versions/:versionId/exports}
 */
export async function postApiV1ScenariosVersionsByVersionIdExports(
  {
    versionId,
    data,
  }: {
    versionId: PostApiV1ScenariosVersionsByVersionIdExportsPathParams["versionId"];
    data: PostApiV1ScenariosVersionsByVersionIdExportsMutationRequest;
  },
  config: Partial<
    RequestConfig<PostApiV1ScenariosVersionsByVersionIdExportsMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData =
    postApiV1ScenariosVersionsByVersionIdExportsMutationRequestSchema.parse(
      data,
    );

  const res = await request<
    PostApiV1ScenariosVersionsByVersionIdExportsMutationResponse,
    ResponseErrorConfig<
      | PostApiV1ScenariosVersionsByVersionIdExports400
      | PostApiV1ScenariosVersionsByVersionIdExports401
      | PostApiV1ScenariosVersionsByVersionIdExports403
      | PostApiV1ScenariosVersionsByVersionIdExports404
      | PostApiV1ScenariosVersionsByVersionIdExports500
    >,
    PostApiV1ScenariosVersionsByVersionIdExportsMutationRequest
  >({
    method: "POST",
    url: getPostApiV1ScenariosVersionsByVersionIdExportsUrl({
      versionId,
    }).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return postApiV1ScenariosVersionsByVersionIdExportsMutationResponseSchema.parse(
    res.data,
  );
}
