/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  PostApiV1CreditsPackagesInitiatePayment400,
  PostApiV1CreditsPackagesInitiatePayment401,
  PostApiV1CreditsPackagesInitiatePayment402,
  PostApiV1CreditsPackagesInitiatePayment403,
  PostApiV1CreditsPackagesInitiatePayment404,
  PostApiV1CreditsPackagesInitiatePayment500,
  PostApiV1CreditsPackagesInitiatePaymentMutationRequest,
  PostApiV1CreditsPackagesInitiatePaymentMutationResponse,
} from "../models/post-api-v1-credits-packages-initiate-payment.ts";

function getPostApiV1CreditsPackagesInitiatePaymentUrl() {
  const res = {
    method: "POST",
    url: `/api/v1/credits/packages/initiate-payment` as const,
  };
  return res;
}

/**
 * {@link /api/v1/credits/packages/initiate-payment}
 */
export async function postApiV1CreditsPackagesInitiatePayment(
  { data }: { data: PostApiV1CreditsPackagesInitiatePaymentMutationRequest },
  config: Partial<
    RequestConfig<PostApiV1CreditsPackagesInitiatePaymentMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostApiV1CreditsPackagesInitiatePaymentMutationResponse,
    ResponseErrorConfig<
      | PostApiV1CreditsPackagesInitiatePayment400
      | PostApiV1CreditsPackagesInitiatePayment401
      | PostApiV1CreditsPackagesInitiatePayment402
      | PostApiV1CreditsPackagesInitiatePayment403
      | PostApiV1CreditsPackagesInitiatePayment404
      | PostApiV1CreditsPackagesInitiatePayment500
    >,
    PostApiV1CreditsPackagesInitiatePaymentMutationRequest
  >({
    method: "POST",
    url: getPostApiV1CreditsPackagesInitiatePaymentUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
