/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  PostApiV1ProfilesChannelsValidate400,
  PostApiV1ProfilesChannelsValidate401,
  PostApiV1ProfilesChannelsValidate402,
  PostApiV1ProfilesChannelsValidate403,
  PostApiV1ProfilesChannelsValidate404,
  PostApiV1ProfilesChannelsValidate500,
  PostApiV1ProfilesChannelsValidateMutationRequest,
  PostApiV1ProfilesChannelsValidateMutationResponse,
} from "../models/post-api-v1-profiles-channels-validate.ts";

function getPostApiV1ProfilesChannelsValidateUrl() {
  const res = {
    method: "POST",
    url: `/api/v1/profiles/channels/validate` as const,
  };
  return res;
}

/**
 * {@link /api/v1/profiles/channels/validate}
 */
export async function postApiV1ProfilesChannelsValidate(
  { data }: { data: PostApiV1ProfilesChannelsValidateMutationRequest },
  config: Partial<
    RequestConfig<PostApiV1ProfilesChannelsValidateMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostApiV1ProfilesChannelsValidateMutationResponse,
    ResponseErrorConfig<
      | PostApiV1ProfilesChannelsValidate400
      | PostApiV1ProfilesChannelsValidate401
      | PostApiV1ProfilesChannelsValidate402
      | PostApiV1ProfilesChannelsValidate403
      | PostApiV1ProfilesChannelsValidate404
      | PostApiV1ProfilesChannelsValidate500
    >,
    PostApiV1ProfilesChannelsValidateMutationRequest
  >({
    method: "POST",
    url: getPostApiV1ProfilesChannelsValidateUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
