/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";
import fetch from "@/lib/api/client";

import type {
  PostApiV1ProfilesByProfileIdChannelVideos400,
  PostApiV1ProfilesByProfileIdChannelVideos401,
  PostApiV1ProfilesByProfileIdChannelVideos402,
  PostApiV1ProfilesByProfileIdChannelVideos403,
  PostApiV1ProfilesByProfileIdChannelVideos404,
  PostApiV1ProfilesByProfileIdChannelVideos500,
  PostApiV1ProfilesByProfileIdChannelVideosMutationRequest,
  PostApiV1ProfilesByProfileIdChannelVideosMutationResponse,
  PostApiV1ProfilesByProfileIdChannelVideosPathParams,
} from "../models/post-api-v1-profiles-by-profile-id-channel-videos.ts";

function getPostApiV1ProfilesByProfileIdChannelVideosUrl({
  profileId,
}: {
  profileId: PostApiV1ProfilesByProfileIdChannelVideosPathParams["profileId"];
}) {
  const res = {
    method: "POST",
    url: `/api/v1/profiles/${profileId}/channel-videos` as const,
  };
  return res;
}

/**
 * {@link /api/v1/profiles/:profileId/channel-videos}
 */
export async function postApiV1ProfilesByProfileIdChannelVideos(
  {
    profileId,
    data,
  }: {
    profileId: PostApiV1ProfilesByProfileIdChannelVideosPathParams["profileId"];
    data: PostApiV1ProfilesByProfileIdChannelVideosMutationRequest;
  },
  config: Partial<
    RequestConfig<PostApiV1ProfilesByProfileIdChannelVideosMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostApiV1ProfilesByProfileIdChannelVideosMutationResponse,
    ResponseErrorConfig<
      | PostApiV1ProfilesByProfileIdChannelVideos400
      | PostApiV1ProfilesByProfileIdChannelVideos401
      | PostApiV1ProfilesByProfileIdChannelVideos402
      | PostApiV1ProfilesByProfileIdChannelVideos403
      | PostApiV1ProfilesByProfileIdChannelVideos404
      | PostApiV1ProfilesByProfileIdChannelVideos500
    >,
    PostApiV1ProfilesByProfileIdChannelVideosMutationRequest
  >({
    method: "POST",
    url: getPostApiV1ProfilesByProfileIdChannelVideosUrl({
      profileId,
    }).url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
