/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import type {
  PostApiV1ScenariosScenesSceneIdPreview400,
  PostApiV1ScenariosScenesSceneIdPreview401,
  PostApiV1ScenariosScenesSceneIdPreview403,
  PostApiV1ScenariosScenesSceneIdPreview404,
  PostApiV1ScenariosScenesSceneIdPreview500,
  PostApiV1ScenariosScenesSceneIdPreviewMutationResponse,
  PostApiV1ScenariosScenesSceneIdPreviewPathParams,
} from "../models/post-api-v1-scenarios-scenes-scene-id-preview.ts";
import { postApiV1ScenariosScenesSceneIdPreviewMutationResponseSchema } from "../zod/post-api-v1-scenarios-scenes-scene-id-preview-schema.ts";

function getPostApiV1ScenariosScenesSceneIdPreviewUrl({
  sceneId,
}: {
  sceneId: PostApiV1ScenariosScenesSceneIdPreviewPathParams["sceneId"];
}) {
  const res = {
    method: "POST",
    url: `/api/v1/scenarios/scenes/${sceneId}/preview` as const,
  };
  return res;
}

/**
 * {@link /api/v1/scenarios/scenes/:sceneId/preview}
 */
export async function postApiV1ScenariosScenesSceneIdPreview(
  {
    sceneId,
  }: { sceneId: PostApiV1ScenariosScenesSceneIdPreviewPathParams["sceneId"] },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostApiV1ScenariosScenesSceneIdPreviewMutationResponse,
    ResponseErrorConfig<
      | PostApiV1ScenariosScenesSceneIdPreview400
      | PostApiV1ScenariosScenesSceneIdPreview401
      | PostApiV1ScenariosScenesSceneIdPreview403
      | PostApiV1ScenariosScenesSceneIdPreview404
      | PostApiV1ScenariosScenesSceneIdPreview500
    >,
    unknown
  >({
    method: "POST",
    url: getPostApiV1ScenariosScenesSceneIdPreviewUrl({
      sceneId,
    }).url.toString(),
    ...requestConfig,
  });
  return postApiV1ScenariosScenesSceneIdPreviewMutationResponseSchema.parse(
    res.data,
  );
}
