/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Add payment method body description
 */
export const addPaymentMethodBodySchemaSchema = z
  .object({
    redirectPath: z.optional(z.string()),
  })
  .describe("Add payment method body description");
