/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { authSessionSchemaSchema } from "./auth-session-schema-schema.ts";
import { userSchemaSchema } from "./user-schema-schema.ts";

/**
 * @description Authenticated session description
 */
export const authenticatedSessionSchemaSchema = z
  .object({
    get session() {
      return authSessionSchemaSchema.describe("Auth session description");
    },
    get user() {
      return userSchemaSchema.describe("User description");
    },
  })
  .describe("Authenticated session description");
