/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Change email body description
 */
export const changeEmailBodySchemaSchema = z
  .object({
    newEmail: z.email(),
    callbackURL: z.optional(z.url()),
  })
  .describe("Change email body description");
