/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Create profile body description
 */
export const createProfileBodySchemaSchema = z
  .object({
    name: z.string().min(1).max(256),
    description: z.string().min(64).max(8192),
    targetAudience: z.optional(z.string().min(1).max(1024)),
    typeId: z.uuid(),
    toneIds: z.optional(z.array(z.uuid())),
    platformIds: z.optional(z.array(z.uuid())),
  })
  .describe("Create profile body description");
