/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Create scenario version export body description
 */
export const createScenarioVersionExportBodySchemaSchema = z
  .object({
    format: z.enum(["pdf", "docx"]),
  })
  .describe("Create scenario version export body description");
