/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { scenarioVersionExportWithUrlSchemaSchema } from "./scenario-version-export-with-url-schema-schema.ts";

/**
 * @description Create scenario version export response description
 */
export const createScenarioVersionExportResponseSchemaSchema = z
  .object({
    get data() {
      return scenarioVersionExportWithUrlSchemaSchema.describe(
        "Scenario version export with url description",
      );
    },
  })
  .describe("Create scenario version export response description");
