/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { exportDocumentShortSchemaSchema } from "./export-document-short-schema-schema.ts";

/**
 * @description Create ideas list export response description
 */
export const createIdeasListExportResponseSchemaSchema = z
  .object({
    get data() {
      return exportDocumentShortSchemaSchema.describe(
        "Export document short description",
      );
    },
  })
  .describe("Create ideas list export response description");
