/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Create profile channel video body description
 */
export const createProfileChannelVideoBodySchemaSchema = z
  .object({
    url: z.url(),
  })
  .describe("Create profile channel video body description");
