/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { profileAttachmentExtendedSchemaSchema } from "./profile-attachment-extended-schema-schema.ts";

/**
 * @description Create profile attachment response description
 */
export const createProfileAttachmentResponseSchemaSchema = z
  .object({
    get data() {
      return profileAttachmentExtendedSchemaSchema.describe(
        "Profile attachment extended description",
      );
    },
  })
  .describe("Create profile attachment response description");
