/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { deleteIdeaResponseSchemaSchema } from "./delete-idea-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { paymentRequiredResponseSchemaSchema } from "./payment-required-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

export const deleteApiV1IdeasByIdeaIdPathParamsSchema = z.object({
  ideaId: z.uuid(),
});

/**
 * @description Idea deleted successfully
 */
export const deleteApiV1IdeasByIdeaId200Schema = z
  .lazy(() => deleteIdeaResponseSchemaSchema)
  .describe("Delete idea response description");

/**
 * @description Bad request
 */
export const deleteApiV1IdeasByIdeaId400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const deleteApiV1IdeasByIdeaId401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Payment required
 */
export const deleteApiV1IdeasByIdeaId402Schema = z
  .lazy(() => paymentRequiredResponseSchemaSchema)
  .describe("Payment required response description");

/**
 * @description Forbidden
 */
export const deleteApiV1IdeasByIdeaId403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const deleteApiV1IdeasByIdeaId404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const deleteApiV1IdeasByIdeaId500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const deleteApiV1IdeasByIdeaIdMutationResponseSchema = z.lazy(
  () => deleteApiV1IdeasByIdeaId200Schema,
);
