/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { scenarioVersionSchemaSchema } from "./scenario-version-schema-schema.ts";

/**
 * @description Delete scenario version response description
 */
export const deleteScenarioVersionResponseSchemaSchema = z
  .object({
    get data() {
      return scenarioVersionSchemaSchema.describe(
        "Scenario version description",
      );
    },
  })
  .describe("Delete scenario version response description");
