/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { deleteScenarioResponseSchemaSchema } from "./delete-scenario-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

export const deleteApiV1ScenariosByScenarioIdPathParamsSchema = z.object({
  scenarioId: z.uuid(),
});

/**
 * @description Scenario deleted successfully
 */
export const deleteApiV1ScenariosByScenarioId200Schema = z
  .lazy(() => deleteScenarioResponseSchemaSchema)
  .describe("Delete scenario response description");

/**
 * @description Bad request
 */
export const deleteApiV1ScenariosByScenarioId400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const deleteApiV1ScenariosByScenarioId401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Forbidden
 */
export const deleteApiV1ScenariosByScenarioId403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const deleteApiV1ScenariosByScenarioId404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const deleteApiV1ScenariosByScenarioId500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const deleteApiV1ScenariosByScenarioIdMutationResponseSchema = z.lazy(
  () => deleteApiV1ScenariosByScenarioId200Schema,
);
