/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { ideasListSchemaSchema } from "./ideas-list-schema-schema.ts";

/**
 * @description Delete ideas list response description
 */
export const deleteIdeasListResponseSchemaSchema = z
  .object({
    get data() {
      return ideasListSchemaSchema.describe("IdeasList description");
    },
  })
  .describe("Delete ideas list response description");
