/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { scenarioSceneComponentSchemaSchema } from "./scenario-scene-component-schema-schema.ts";

/**
 * @description Delete scenario scene component response description
 */
export const deleteScenarioSceneComponentResponseSchemaSchema = z
  .object({
    get data() {
      return scenarioSceneComponentSchemaSchema.describe(
        "Scenario scene component description",
      );
    },
  })
  .describe("Delete scenario scene component response description");
