/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const deleteApiV1IdeasIdeaIdPathParamsSchema = z.object({
  ideaId: z.uuid(),
});

/**
 * @description Idea deleted successfully
 */
export const deleteApiV1IdeasIdeaId200Schema = z.object({
  data: z.object({
    id: z.uuid(),
    ideasListId: z.uuid(),
    videoTypeId: z.uuid(),
    saved: z.boolean(),
    liked: z.union([z.boolean(), z.null()]),
    name: z.union([z.string(), z.null()]),
    description: z.union([z.string(), z.null()]),
    reason: z.union([z.string(), z.null()]),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
});

/**
 * @description Bad request
 */
export const deleteApiV1IdeasIdeaId400Schema = z.string();

/**
 * @description Unauthorized
 */
export const deleteApiV1IdeasIdeaId401Schema = z.string();

/**
 * @description Forbidden
 */
export const deleteApiV1IdeasIdeaId403Schema = z.string();

/**
 * @description Not found
 */
export const deleteApiV1IdeasIdeaId404Schema = z.string();

/**
 * @description Internal server error
 */
export const deleteApiV1IdeasIdeaId500Schema = z.string();

export const deleteApiV1IdeasIdeaIdMutationResponseSchema = z.lazy(
  () => deleteApiV1IdeasIdeaId200Schema,
);
