/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { deleteProfileResponseSchemaSchema } from "./delete-profile-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

export const deleteApiV1ProfilesByProfileIdPathParamsSchema = z.object({
  profileId: z.uuid(),
});

/**
 * @description Profile deleted successfully
 */
export const deleteApiV1ProfilesByProfileId200Schema = z
  .lazy(() => deleteProfileResponseSchemaSchema)
  .describe("Delete profile response description");

/**
 * @description Bad request
 */
export const deleteApiV1ProfilesByProfileId400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const deleteApiV1ProfilesByProfileId401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Forbidden
 */
export const deleteApiV1ProfilesByProfileId403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const deleteApiV1ProfilesByProfileId404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const deleteApiV1ProfilesByProfileId500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const deleteApiV1ProfilesByProfileIdMutationResponseSchema = z.lazy(
  () => deleteApiV1ProfilesByProfileId200Schema,
);
