/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { deleteProfileAttachmentResponseSchemaSchema } from "./delete-profile-attachment-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { paymentRequiredResponseSchemaSchema } from "./payment-required-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

export const deleteApiV1ProfilesAttachmentsByAttachmentIdPathParamsSchema =
  z.object({
    attachmentId: z.uuid(),
  });

/**
 * @description Profile attachment deleted successfully
 */
export const deleteApiV1ProfilesAttachmentsByAttachmentId200Schema = z
  .lazy(() => deleteProfileAttachmentResponseSchemaSchema)
  .describe("Delete profile attachment response description");

/**
 * @description Bad request
 */
export const deleteApiV1ProfilesAttachmentsByAttachmentId400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const deleteApiV1ProfilesAttachmentsByAttachmentId401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Payment required
 */
export const deleteApiV1ProfilesAttachmentsByAttachmentId402Schema = z
  .lazy(() => paymentRequiredResponseSchemaSchema)
  .describe("Payment required response description");

/**
 * @description Forbidden
 */
export const deleteApiV1ProfilesAttachmentsByAttachmentId403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const deleteApiV1ProfilesAttachmentsByAttachmentId404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const deleteApiV1ProfilesAttachmentsByAttachmentId500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const deleteApiV1ProfilesAttachmentsByAttachmentIdMutationResponseSchema =
  z.lazy(() => deleteApiV1ProfilesAttachmentsByAttachmentId200Schema);
