/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { getMyReferralInvitesResponseSchemaSchema } from "./get-my-referral-invites-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { paymentRequiredResponseSchemaSchema } from "./payment-required-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

export const getApiV1ReferralInvitesMyQueryParamsSchema = z
  .object({
    q: z.optional(z.string().describe("Строка поиска")),
    page: z.optional(z.coerce.number().describe("Номер страницы")),
    perPage: z.optional(
      z.coerce
        .number()
        .describe("Количество элементов в одной странице ответа"),
    ),
    sort: z.optional(z.string()),
  })
  .optional();

/**
 * @description My referral invites retrieved successfully
 */
export const getApiV1ReferralInvitesMy200Schema = z
  .lazy(() => getMyReferralInvitesResponseSchemaSchema)
  .describe("Get my referral invites response description");

/**
 * @description Bad request
 */
export const getApiV1ReferralInvitesMy400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const getApiV1ReferralInvitesMy401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Payment required
 */
export const getApiV1ReferralInvitesMy402Schema = z
  .lazy(() => paymentRequiredResponseSchemaSchema)
  .describe("Payment required response description");

/**
 * @description Forbidden
 */
export const getApiV1ReferralInvitesMy403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const getApiV1ReferralInvitesMy404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const getApiV1ReferralInvitesMy500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const getApiV1ReferralInvitesMyQueryResponseSchema = z.lazy(
  () => getApiV1ReferralInvitesMy200Schema,
);
