/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { scenarioSchemaSchema } from "./scenario-schema-schema.ts";

/**
 * @description Get my scenarios response description
 */
export const getMyScenariosResponseSchemaSchema = z
  .object({
    get data() {
      return z.array(scenarioSchemaSchema.describe("Scenario description"));
    },
  })
  .describe("Get my scenarios response description");
