/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { getScenarioMetadataResponseSchemaSchema } from "./get-scenario-metadata-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { paymentRequiredResponseSchemaSchema } from "./payment-required-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

export const getApiV1ScenariosByScenarioIdMetadataPathParamsSchema = z.object({
  scenarioId: z.uuid(),
});

/**
 * @description Scenario metadata retrieved successfully
 */
export const getApiV1ScenariosByScenarioIdMetadata200Schema = z
  .lazy(() => getScenarioMetadataResponseSchemaSchema)
  .describe("Get scenario metadata response description");

/**
 * @description Bad request
 */
export const getApiV1ScenariosByScenarioIdMetadata400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const getApiV1ScenariosByScenarioIdMetadata401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Payment required
 */
export const getApiV1ScenariosByScenarioIdMetadata402Schema = z
  .lazy(() => paymentRequiredResponseSchemaSchema)
  .describe("Payment required response description");

/**
 * @description Forbidden
 */
export const getApiV1ScenariosByScenarioIdMetadata403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const getApiV1ScenariosByScenarioIdMetadata404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const getApiV1ScenariosByScenarioIdMetadata500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const getApiV1ScenariosByScenarioIdMetadataQueryResponseSchema = z.lazy(
  () => getApiV1ScenariosByScenarioIdMetadata200Schema,
);
