/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { getMyScenariosResponseMetaSchemaSchema } from "./get-my-scenarios-response-meta-schema-schema.ts";
import { scenarioExtendedSchemaSchema } from "./scenario-extended-schema-schema.ts";

/**
 * @description Scenarios response payload
 */
export const getMyScenariosResponseSchemaSchema = z
  .object({
    get data() {
      return z.array(
        scenarioExtendedSchemaSchema.describe("Scenario extended description"),
      );
    },
    get meta() {
      return getMyScenariosResponseMetaSchemaSchema.describe(
        "Get my scenarios response meta description",
      );
    },
  })
  .describe("Scenarios response payload");
