/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { getScenarioVersionsResponseSchemaSchema } from "./get-scenario-versions-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

export const getApiV1ScenariosByScenarioIdVersionsPathParamsSchema = z.object({
  scenarioId: z.uuid(),
});

/**
 * @description Scenario versions retrieved successfully
 */
export const getApiV1ScenariosByScenarioIdVersions200Schema = z
  .lazy(() => getScenarioVersionsResponseSchemaSchema)
  .describe("Get scenario versions response description");

/**
 * @description Bad request
 */
export const getApiV1ScenariosByScenarioIdVersions400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const getApiV1ScenariosByScenarioIdVersions401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Forbidden
 */
export const getApiV1ScenariosByScenarioIdVersions403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const getApiV1ScenariosByScenarioIdVersions404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const getApiV1ScenariosByScenarioIdVersions500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const getApiV1ScenariosByScenarioIdVersionsQueryResponseSchema = z.lazy(
  () => getApiV1ScenariosByScenarioIdVersions200Schema,
);
