/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { alertSchemaSchema } from "./alert-schema-schema.ts";

/**
 * @description Get alerts response description
 */
export const getAlertsResponseSchemaSchema = z
  .object({
    get data() {
      return z.array(alertSchemaSchema.describe("Alert description"));
    },
  })
  .describe("Get alerts response description");
