/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { getLegalDocumentsResponseSchemaSchema } from "./get-legal-documents-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { paymentRequiredResponseSchemaSchema } from "./payment-required-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

/**
 * @description Legal documents retrieved successfully
 */
export const getApiV1LegalDocuments200Schema = z
  .lazy(() => getLegalDocumentsResponseSchemaSchema)
  .describe("Get legal documents response description");

/**
 * @description Bad request
 */
export const getApiV1LegalDocuments400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const getApiV1LegalDocuments401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Payment required
 */
export const getApiV1LegalDocuments402Schema = z
  .lazy(() => paymentRequiredResponseSchemaSchema)
  .describe("Payment required response description");

/**
 * @description Forbidden
 */
export const getApiV1LegalDocuments403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const getApiV1LegalDocuments404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const getApiV1LegalDocuments500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const getApiV1LegalDocumentsQueryResponseSchema = z.lazy(
  () => getApiV1LegalDocuments200Schema,
);
