/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { getAlertsResponseSchemaSchema } from "./get-alerts-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { paymentRequiredResponseSchemaSchema } from "./payment-required-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

/**
 * @description Active alerts retrieved successfully
 */
export const getApiV1Alerts200Schema = z
  .lazy(() => getAlertsResponseSchemaSchema)
  .describe("Get alerts response description");

/**
 * @description Bad request
 */
export const getApiV1Alerts400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const getApiV1Alerts401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Payment required
 */
export const getApiV1Alerts402Schema = z
  .lazy(() => paymentRequiredResponseSchemaSchema)
  .describe("Payment required response description");

/**
 * @description Forbidden
 */
export const getApiV1Alerts403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const getApiV1Alerts404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const getApiV1Alerts500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const getApiV1AlertsQueryResponseSchema = z.lazy(
  () => getApiV1Alerts200Schema,
);
