/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { legalDocumentSchemaSchema } from "./legal-document-schema-schema.ts";

/**
 * @description Get legal documents response description
 */
export const getLegalDocumentsResponseSchemaSchema = z
  .object({
    get data() {
      return z.array(
        legalDocumentSchemaSchema.describe("Legal document description"),
      );
    },
  })
  .describe("Get legal documents response description");
