/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { scenarioChapterExtendedSchemaSchema } from "./scenario-chapter-extended-schema-schema.ts";

/**
 * @description Get scenario chapter response description
 */
export const getScenarioChapterResponseSchemaSchema = z
  .object({
    get data() {
      return scenarioChapterExtendedSchemaSchema.describe(
        "Scenario chapter extended description",
      );
    },
  })
  .describe("Get scenario chapter response description");
