/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Video durations retrieved successfully
 */
export const getApiV1VideoDurations200Schema = z.object({
  data: z.array(
    z.object({
      id: z.uuid(),
      slug: z.string(),
      name: z.string(),
      description: z.union([z.string(), z.null()]),
      minSeconds: z.int().min(-9007199254740991).max(9007199254740991),
      maxSeconds: z.union([z.int(), z.null()]),
      createdAt: z.string(),
      updatedAt: z.string(),
    }),
  ),
});

/**
 * @description Bad request
 */
export const getApiV1VideoDurations400Schema = z.string();

/**
 * @description Unauthorized
 */
export const getApiV1VideoDurations401Schema = z.string();

/**
 * @description Forbidden
 */
export const getApiV1VideoDurations403Schema = z.string();

/**
 * @description Not found
 */
export const getApiV1VideoDurations404Schema = z.string();

/**
 * @description Internal server error
 */
export const getApiV1VideoDurations500Schema = z.string();

export const getApiV1VideoDurationsQueryResponseSchema = z.lazy(
  () => getApiV1VideoDurations200Schema,
);
