/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { getIdeasListExportsResponseSchemaSchema } from "./get-ideas-list-exports-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

export const getApiV1IdeasListsByIdeasListIdExportsPathParamsSchema = z.object({
  ideasListId: z.uuid(),
});

export const getApiV1IdeasListsByIdeasListIdExportsQueryParamsSchema = z.object(
  {
    savedOnly: z.boolean().default(false),
  },
);

/**
 * @description Ideas list exports retrieved successfully
 */
export const getApiV1IdeasListsByIdeasListIdExports200Schema = z
  .lazy(() => getIdeasListExportsResponseSchemaSchema)
  .describe("Get ideas list exports response description");

/**
 * @description Bad request
 */
export const getApiV1IdeasListsByIdeasListIdExports400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const getApiV1IdeasListsByIdeasListIdExports401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Forbidden
 */
export const getApiV1IdeasListsByIdeasListIdExports403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const getApiV1IdeasListsByIdeasListIdExports404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const getApiV1IdeasListsByIdeasListIdExports500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const getApiV1IdeasListsByIdeasListIdExportsQueryResponseSchema = z.lazy(
  () => getApiV1IdeasListsByIdeasListIdExports200Schema,
);
