/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Tariffs retrieved successfully
 */
export const getApiV1Tariffs200Schema = z.object({
  data: z.array(
    z.object({
      id: z.uuid(),
      slug: z.string().max(255),
      name: z.string(),
      description: z.union([z.string(), z.null()]),
      price: z.int().min(-9007199254740991).max(9007199254740991),
      oldPrice: z.union([z.int(), z.null()]),
      creditsAmount: z.int().min(-9007199254740991).max(9007199254740991),
      billingPeriod: z.union([z.enum(["month", "year"]), z.null()]),
      priority: z.boolean(),
      createdAt: z.string(),
      updatedAt: z.string(),
      trial: z.optional(
        z.union([
          z.object({
            id: z.uuid(),
            tariffId: z.union([z.uuid(), z.null()]),
            slug: z.string().max(255),
            price: z.int().min(-9007199254740991).max(9007199254740991),
            creditsAmount: z.int().min(-9007199254740991).max(9007199254740991),
            active: z.boolean(),
            firstTimeOnly: z.boolean(),
            durationDays: z.int().min(-9007199254740991).max(9007199254740991),
            createdAt: z.string(),
            updatedAt: z.string(),
          }),
          z.null(),
        ]),
      ),
    }),
  ),
});

/**
 * @description Bad request
 */
export const getApiV1Tariffs400Schema = z.string();

/**
 * @description Unauthorized
 */
export const getApiV1Tariffs401Schema = z.string();

/**
 * @description Forbidden
 */
export const getApiV1Tariffs403Schema = z.string();

/**
 * @description Not found
 */
export const getApiV1Tariffs404Schema = z.string();

/**
 * @description Internal server error
 */
export const getApiV1Tariffs500Schema = z.string();

export const getApiV1TariffsQueryResponseSchema = z.lazy(
  () => getApiV1Tariffs200Schema,
);
