/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentExtendedSchemaSchema } from "./payment-extended-schema-schema.ts";

/**
 * @description Get my payments response description
 */
export const getMyPaymentsResponseSchemaSchema = z
  .object({
    get data() {
      return z.array(
        paymentExtendedSchemaSchema.describe("Payment extended description"),
      );
    },
  })
  .describe("Get my payments response description");
