/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Ideas list export with url description
 */
export const ideasListExportWithUrlSchemaSchema = z
  .object({
    id: z.uuid(),
    userId: z.uuid(),
    ideasListId: z.uuid(),
    attachmentId: z.union([z.uuid(), z.null()]),
    format: z.enum(["pdf", "docx"]),
    status: z.enum(["idle", "pending", "generation", "failed", "ready"]),
    savedOnly: z.boolean(),
    error: z.union([z.string(), z.null()]),
    createdAt: z.string(),
    updatedAt: z.string(),
    url: z.union([z.string(), z.null()]),
  })
  .describe("Ideas list export with url description");
