/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Initiate credits package payment body description
 */
export const initiateCreditsPackagePaymentBodySchemaSchema = z
  .object({
    creditsPackageId: z.string(),
    redirect: z.optional(z.string()),
  })
  .describe("Initiate credits package payment body description");
