/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { paymentSchemaSchema } from "./payment-schema-schema.ts";

/**
 * @description Initiate subscription payment response description
 */
export const initiateSubscriptionPaymentResponseSchemaSchema = z
  .object({
    get data() {
      return paymentSchemaSchema.describe("Payment description");
    },
  })
  .describe("Initiate subscription payment response description");
