/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Not found response description
 */
export const notFoundResponseSchemaSchema = z
  .string()
  .describe("Not found response description");
