/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { paymentRequiredResponseSchemaSchema } from "./payment-required-response-schema-schema.ts";
import { selectDefaultPaymentMethodResponseSchemaSchema } from "./select-default-payment-method-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

export const patchApiV1BillingPaymentMethodsByPaymentMethodIdDefaultPathParamsSchema =
  z.object({
    paymentMethodId: z.uuid(),
  });

/**
 * @description Default payment method selected successfully
 */
export const patchApiV1BillingPaymentMethodsByPaymentMethodIdDefault200Schema =
  z
    .lazy(() => selectDefaultPaymentMethodResponseSchemaSchema)
    .describe("Select default payment method response description");

/**
 * @description Bad request
 */
export const patchApiV1BillingPaymentMethodsByPaymentMethodIdDefault400Schema =
  z
    .lazy(() => badRequestResponseSchemaSchema)
    .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const patchApiV1BillingPaymentMethodsByPaymentMethodIdDefault401Schema =
  z
    .lazy(() => unauthorizedResponseSchemaSchema)
    .describe("Unauthorized response description");

/**
 * @description Payment required
 */
export const patchApiV1BillingPaymentMethodsByPaymentMethodIdDefault402Schema =
  z
    .lazy(() => paymentRequiredResponseSchemaSchema)
    .describe("Payment required response description");

/**
 * @description Forbidden
 */
export const patchApiV1BillingPaymentMethodsByPaymentMethodIdDefault403Schema =
  z
    .lazy(() => forbiddenResponseSchemaSchema)
    .describe("Forbidden response description");

/**
 * @description Not found
 */
export const patchApiV1BillingPaymentMethodsByPaymentMethodIdDefault404Schema =
  z
    .lazy(() => notFoundResponseSchemaSchema)
    .describe("Not found response description");

/**
 * @description Internal server error
 */
export const patchApiV1BillingPaymentMethodsByPaymentMethodIdDefault500Schema =
  z
    .lazy(() => internalServerErrorResponseSchemaSchema)
    .describe("Internal server error response description");

export const patchApiV1BillingPaymentMethodsByPaymentMethodIdDefaultMutationResponseSchema =
  z.lazy(
    () => patchApiV1BillingPaymentMethodsByPaymentMethodIdDefault200Schema,
  );
