/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { creditsBatchExtendedSchemaSchema } from "./credits-batch-extended-schema-schema.ts";
import { paymentMethodSchemaSchema } from "./payment-method-schema-schema.ts";
import { subscriptionWithTariffSchemaSchema } from "./subscription-with-tariff-schema-schema.ts";

/**
 * @description Payment extended description
 */
export const paymentExtendedSchemaSchema = z
  .object({
    id: z.uuid(),
    userId: z.uuid(),
    paymentMethodId: z.union([z.uuid(), z.null()]),
    externalId: z.string(),
    paymentLink: z.union([z.string(), z.null()]),
    amount: z.number().min(-8388608).max(8388607),
    currency: z.string(),
    status: z.enum(["pending", "succeeded", "canceled", "failed"]),
    statusDetails: z.union([z.string(), z.null()]),
    createdAt: z.string(),
    updatedAt: z.string(),
    get paymentMethod() {
      return z.union([paymentMethodSchemaSchema, z.null()]).optional();
    },
    get subscription() {
      return z.union([subscriptionWithTariffSchemaSchema, z.null()]).optional();
    },
    get creditsBatch() {
      return z.union([creditsBatchExtendedSchemaSchema, z.null()]).optional();
    },
  })
  .describe("Payment extended description");
