/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { creditsPackageSchemaSchema } from "./credits-package-schema-schema.ts";
import { paymentMethodSchemaSchema } from "./payment-method-schema-schema.ts";
import { tariffSchemaSchema } from "./tariff-schema-schema.ts";

/**
 * @description Payment extended description
 */
export const paymentExtendedSchemaSchema = z
  .object({
    id: z.uuid(),
    userId: z.uuid(),
    paymentMethodId: z.union([z.uuid(), z.null()]),
    paymentId: z.string(),
    amount: z.number().min(-8388608).max(8388607),
    currency: z.string(),
    status: z.enum(["pending", "succeeded", "canceled", "failed"]),
    statusDetails: z.union([z.string(), z.null()]),
    createdAt: z.string(),
    updatedAt: z.string(),
    get paymentMethod() {
      return z.union([paymentMethodSchemaSchema, z.null()]).optional();
    },
    get tariff() {
      return z.union([tariffSchemaSchema, z.null()]).optional();
    },
    get creditsPackage() {
      return z.union([creditsPackageSchemaSchema, z.null()]).optional();
    },
  })
  .describe("Payment extended description");
