/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { createIdeasListExportBodySchemaSchema } from "./create-ideas-list-export-body-schema-schema.ts";
import { createIdeasListExportResponseSchemaSchema } from "./create-ideas-list-export-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { paymentRequiredResponseSchemaSchema } from "./payment-required-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

export const postApiV1IdeasListsByIdeasListIdExportPathParamsSchema = z.object({
  ideasListId: z.uuid(),
});

/**
 * @description Ideas list export retrieved successfully
 */
export const postApiV1IdeasListsByIdeasListIdExport200Schema = z
  .lazy(() => createIdeasListExportResponseSchemaSchema)
  .describe("Create ideas list export response description");

/**
 * @description Bad request
 */
export const postApiV1IdeasListsByIdeasListIdExport400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const postApiV1IdeasListsByIdeasListIdExport401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Payment required
 */
export const postApiV1IdeasListsByIdeasListIdExport402Schema = z
  .lazy(() => paymentRequiredResponseSchemaSchema)
  .describe("Payment required response description");

/**
 * @description Forbidden
 */
export const postApiV1IdeasListsByIdeasListIdExport403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const postApiV1IdeasListsByIdeasListIdExport404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const postApiV1IdeasListsByIdeasListIdExport500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const postApiV1IdeasListsByIdeasListIdExportMutationRequestSchema = z
  .lazy(() => createIdeasListExportBodySchemaSchema)
  .describe("Create ideas list export body description");

export const postApiV1IdeasListsByIdeasListIdExportMutationResponseSchema =
  z.lazy(() => postApiV1IdeasListsByIdeasListIdExport200Schema);
