/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const postApiV1IdeasListsIdeasListIdIdeasPathParamsSchema = z.object({
  ideasListId: z.uuid(),
});

/**
 * @description Idea created successfully
 */
export const postApiV1IdeasListsIdeasListIdIdeas201Schema = z.object({
  data: z.object({
    id: z.uuid(),
    ideasListId: z.uuid(),
    videoTypeId: z.uuid(),
    saved: z.boolean(),
    liked: z.union([z.boolean(), z.null()]),
    name: z.union([z.string(), z.null()]),
    description: z.union([z.string(), z.null()]),
    reason: z.union([z.string(), z.null()]),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
});

/**
 * @description Bad request
 */
export const postApiV1IdeasListsIdeasListIdIdeas400Schema = z.string();

/**
 * @description Unauthorized
 */
export const postApiV1IdeasListsIdeasListIdIdeas401Schema = z.string();

/**
 * @description Forbidden
 */
export const postApiV1IdeasListsIdeasListIdIdeas403Schema = z.string();

/**
 * @description Not found
 */
export const postApiV1IdeasListsIdeasListIdIdeas404Schema = z.string();

/**
 * @description Internal server error
 */
export const postApiV1IdeasListsIdeasListIdIdeas500Schema = z.string();

export const postApiV1IdeasListsIdeasListIdIdeasMutationRequestSchema =
  z.object({
    videoTypeId: z.uuid(),
    name: z.optional(z.union([z.string(), z.null()])),
    description: z.optional(z.union([z.string(), z.null()])),
  });

export const postApiV1IdeasListsIdeasListIdIdeasMutationResponseSchema = z.lazy(
  () => postApiV1IdeasListsIdeasListIdIdeas201Schema,
);
