/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

export const postApiV1IdeasListsIdeasListIdMoreIdeasPathParamsSchema = z.object(
  {
    ideasListId: z.uuid(),
  },
);

/**
 * @description More ideas generation queued successfully
 */
export const postApiV1IdeasListsIdeasListIdMoreIdeas202Schema = z.object({
  data: z.object({
    id: z.uuid(),
    userId: z.uuid(),
    profileId: z.union([z.uuid(), z.null()]),
    templateId: z.union([z.uuid(), z.null()]),
    status: z.enum(["pending", "generation", "failed", "ready"]),
    name: z.union([z.string(), z.null()]),
    description: z.union([z.string(), z.null()]),
    targetAudience: z.union([z.string(), z.null()]),
    createdAt: z.string(),
    updatedAt: z.string(),
  }),
});

/**
 * @description Bad request
 */
export const postApiV1IdeasListsIdeasListIdMoreIdeas400Schema = z.string();

/**
 * @description Unauthorized
 */
export const postApiV1IdeasListsIdeasListIdMoreIdeas401Schema = z.string();

/**
 * @description Forbidden
 */
export const postApiV1IdeasListsIdeasListIdMoreIdeas403Schema = z.string();

/**
 * @description Not found
 */
export const postApiV1IdeasListsIdeasListIdMoreIdeas404Schema = z.string();

/**
 * @description Internal server error
 */
export const postApiV1IdeasListsIdeasListIdMoreIdeas500Schema = z.string();

export const postApiV1IdeasListsIdeasListIdMoreIdeasMutationRequestSchema =
  z.object({
    userPrompt: z.optional(z.union([z.string(), z.null()])),
  });

export const postApiV1IdeasListsIdeasListIdMoreIdeasMutationResponseSchema =
  z.lazy(() => postApiV1IdeasListsIdeasListIdMoreIdeas202Schema);
