/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { createAttachmentBodySchemaSchema } from "./create-attachment-body-schema-schema.ts";
import { createAttachmentResponseSchemaSchema } from "./create-attachment-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { paymentRequiredResponseSchemaSchema } from "./payment-required-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

/**
 * @description Attachment created successfully
 */
export const postApiV1Attachments201Schema = z
  .lazy(() => createAttachmentResponseSchemaSchema)
  .describe("Create attachment response description");

/**
 * @description Bad request
 */
export const postApiV1Attachments400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const postApiV1Attachments401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Payment required
 */
export const postApiV1Attachments402Schema = z
  .lazy(() => paymentRequiredResponseSchemaSchema)
  .describe("Payment required response description");

/**
 * @description Forbidden
 */
export const postApiV1Attachments403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const postApiV1Attachments404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const postApiV1Attachments500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const postApiV1AttachmentsMutationRequestSchema = z
  .lazy(() => createAttachmentBodySchemaSchema)
  .describe("Create attachment body description");

export const postApiV1AttachmentsMutationResponseSchema = z.lazy(
  () => postApiV1Attachments201Schema,
);
