/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { badRequestResponseSchemaSchema } from "./bad-request-response-schema-schema.ts";
import { forbiddenResponseSchemaSchema } from "./forbidden-response-schema-schema.ts";
import { generateMoreIdeasBodySchemaSchema } from "./generate-more-ideas-body-schema-schema.ts";
import { generateMoreIdeasResponseSchemaSchema } from "./generate-more-ideas-response-schema-schema.ts";
import { internalServerErrorResponseSchemaSchema } from "./internal-server-error-response-schema-schema.ts";
import { notFoundResponseSchemaSchema } from "./not-found-response-schema-schema.ts";
import { unauthorizedResponseSchemaSchema } from "./unauthorized-response-schema-schema.ts";

export const postApiV1IdeasListsByIdeasListIdMoreIdeasPathParamsSchema =
  z.object({
    ideasListId: z.uuid(),
  });

/**
 * @description More ideas generation queued successfully
 */
export const postApiV1IdeasListsByIdeasListIdMoreIdeas202Schema = z
  .lazy(() => generateMoreIdeasResponseSchemaSchema)
  .describe("Generate more ideas response description");

/**
 * @description Bad request
 */
export const postApiV1IdeasListsByIdeasListIdMoreIdeas400Schema = z
  .lazy(() => badRequestResponseSchemaSchema)
  .describe("Bad request response description");

/**
 * @description Unauthorized
 */
export const postApiV1IdeasListsByIdeasListIdMoreIdeas401Schema = z
  .lazy(() => unauthorizedResponseSchemaSchema)
  .describe("Unauthorized response description");

/**
 * @description Forbidden
 */
export const postApiV1IdeasListsByIdeasListIdMoreIdeas403Schema = z
  .lazy(() => forbiddenResponseSchemaSchema)
  .describe("Forbidden response description");

/**
 * @description Not found
 */
export const postApiV1IdeasListsByIdeasListIdMoreIdeas404Schema = z
  .lazy(() => notFoundResponseSchemaSchema)
  .describe("Not found response description");

/**
 * @description Internal server error
 */
export const postApiV1IdeasListsByIdeasListIdMoreIdeas500Schema = z
  .lazy(() => internalServerErrorResponseSchemaSchema)
  .describe("Internal server error response description");

export const postApiV1IdeasListsByIdeasListIdMoreIdeasMutationRequestSchema = z
  .lazy(() => generateMoreIdeasBodySchemaSchema)
  .describe("Generate more ideas body description");

export const postApiV1IdeasListsByIdeasListIdMoreIdeasMutationResponseSchema =
  z.lazy(() => postApiV1IdeasListsByIdeasListIdMoreIdeas202Schema);
