/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Production status description
 */
export const productionStatusSchemaSchema = z
  .object({
    id: z.uuid(),
    slug: z.string(),
    name: z.string(),
    description: z.union([z.string(), z.null()]),
    icon: z.union([z.string(), z.null()]),
    color: z.union([z.string(), z.null()]),
    isDefault: z.boolean(),
    forScenario: z.boolean(),
    forScenarioChapter: z.boolean(),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .describe("Production status description");
