/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Scenario version export item description
 */
export const scenarioVersionExportItemSchemaSchema = z
  .object({
    name: z.string(),
    format: z.enum(["pdf", "docx"]),
    state: z.enum(["idle", "pending", "generation", "failed", "ready"]),
    url: z.union([z.string(), z.null()]),
  })
  .describe("Scenario version export item description");
