/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Send verification OTP response description
 */
export const sendVerificationOtpResponseSchemaSchema = z
  .object({
    success: z.optional(z.boolean()),
  })
  .describe("Send verification OTP response description");
