/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Subscription description
 */
export const subscriptionSchemaSchema = z
  .object({
    id: z.uuid(),
    userId: z.uuid(),
    tariffId: z.uuid(),
    startsAt: z.union([z.string(), z.null()]),
    endsAt: z.union([z.string(), z.null()]),
    cycleStartsAt: z.union([z.string(), z.null()]),
    cycleEndsAt: z.union([z.string(), z.null()]),
    lastBilledAt: z.union([z.string(), z.null()]),
    nextBillingAt: z.union([z.string(), z.null()]),
    failedBillingAttempts: z.int().min(-9007199254740991).max(9007199254740991),
    status: z.enum(["pending", "active", "overdue", "cancelled", "terminated"]),
    statusUpdatedAt: z.union([z.string(), z.null()]),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .describe("Subscription description");
