/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Tariff discount description
 */
export const tariffDiscountSchemaSchema = z
  .object({
    id: z.uuid(),
    userId: z.uuid(),
    tariffId: z.union([z.uuid(), z.null()]),
    type: z.enum(["fixed", "percentage"]),
    value: z.string(),
    expiresAt: z.union([z.string(), z.null()]),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .describe("Tariff discount description");
