/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Tone description
 */
export const toneSchemaSchema = z
  .object({
    id: z.uuid(),
    slug: z.string(),
    name: z.string(),
    description: z.union([z.string(), z.null()]),
    icon: z.union([z.string(), z.null()]),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .describe("Tone description");
