/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Update scenario chapter body description
 */
export const updateScenarioChapterBodySchemaSchema = z
  .object({
    name: z.optional(z.string().min(3).max(256)),
    description: z.optional(z.string().min(16).max(4096)),
    productionStatusId: z.optional(z.uuid()),
  })
  .describe("Update scenario chapter body description");
