/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Update scenario scene component body description
 */
export const updateScenarioSceneComponentBodySchemaSchema = z
  .object({
    name: z.string().min(1).max(256),
    content: z.string().min(1).max(4096),
  })
  .describe("Update scenario scene component body description");
