/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { scenarioChapterSchemaSchema } from "./scenario-chapter-schema-schema.ts";

/**
 * @description Update scenario chapter response description
 */
export const updateScenarioChapterResponseSchemaSchema = z
  .object({
    get data() {
      return scenarioChapterSchemaSchema.describe(
        "Scenario chapter description",
      );
    },
  })
  .describe("Update scenario chapter response description");
