/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Update scenario scene body description
 */
export const updateScenarioSceneBodySchemaSchema = z
  .object({
    name: z.string().min(3).max(256),
  })
  .describe("Update scenario scene body description");
