/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

import { profileSchemaSchema } from "./profile-schema-schema.ts";

/**
 * @description Update profile response description
 */
export const updateProfileResponseSchemaSchema = z
  .object({
    get data() {
      return profileSchemaSchema.describe("Profile description");
    },
  })
  .describe("Update profile response description");
