/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description User description
 */
export const userSchemaSchema = z
  .object({
    id: z.uuid(),
    email: z.string(),
    emailVerified: z.boolean(),
    phone: z.union([z.string(), z.null()]),
    phoneVerified: z.boolean(),
    name: z.string(),
    image: z.union([z.string(), z.null()]),
    role: z.enum(["user", "admin"]),
    banned: z.boolean(),
    banReason: z.union([z.string(), z.null()]),
    banExpires: z.union([z.string(), z.null()]),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .describe("User description");
