/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "@/lib/zod/index.ts";

/**
 * @description Video duration description
 */
export const videoDurationSchemaSchema = z
  .object({
    id: z.uuid(),
    name: z.string(),
    description: z.union([z.string(), z.null()]),
    minSeconds: z.int().min(-9007199254740991).max(9007199254740991),
    maxSeconds: z.union([z.int(), z.null()]),
    slug: z.string(),
    createdAt: z.string(),
    updatedAt: z.string(),
  })
  .describe("Video duration description");
