/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";

import { deleteApiV1ScenariosVersionsByVersionId } from "../clients/delete-api-v1-scenarios-versions-by-version-id.ts";
import type {
  DeleteApiV1ScenariosVersionsByVersionId400,
  DeleteApiV1ScenariosVersionsByVersionId401,
  DeleteApiV1ScenariosVersionsByVersionId403,
  DeleteApiV1ScenariosVersionsByVersionId404,
  DeleteApiV1ScenariosVersionsByVersionId500,
  DeleteApiV1ScenariosVersionsByVersionIdMutationResponse,
  DeleteApiV1ScenariosVersionsByVersionIdPathParams,
} from "../models/delete-api-v1-scenarios-versions-by-version-id.ts";

export const deleteApiV1ScenariosVersionsByVersionIdMutationKey = () =>
  [{ url: "/api/v1/scenarios/versions/:versionId" }] as const;

export type DeleteApiV1ScenariosVersionsByVersionIdMutationKey = ReturnType<
  typeof deleteApiV1ScenariosVersionsByVersionIdMutationKey
>;

export function deleteApiV1ScenariosVersionsByVersionIdMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deleteApiV1ScenariosVersionsByVersionIdMutationKey();
  return mutationOptions<
    DeleteApiV1ScenariosVersionsByVersionIdMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1ScenariosVersionsByVersionId400
      | DeleteApiV1ScenariosVersionsByVersionId401
      | DeleteApiV1ScenariosVersionsByVersionId403
      | DeleteApiV1ScenariosVersionsByVersionId404
      | DeleteApiV1ScenariosVersionsByVersionId500
    >,
    {
      versionId: DeleteApiV1ScenariosVersionsByVersionIdPathParams["versionId"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ versionId }) => {
      return deleteApiV1ScenariosVersionsByVersionId({ versionId }, config);
    },
  });
}

/**
 * {@link /api/v1/scenarios/versions/:versionId}
 */
export function useDeleteApiV1ScenariosVersionsByVersionId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1ScenariosVersionsByVersionIdMutationResponse,
      ResponseErrorConfig<
        | DeleteApiV1ScenariosVersionsByVersionId400
        | DeleteApiV1ScenariosVersionsByVersionId401
        | DeleteApiV1ScenariosVersionsByVersionId403
        | DeleteApiV1ScenariosVersionsByVersionId404
        | DeleteApiV1ScenariosVersionsByVersionId500
      >,
      {
        versionId: DeleteApiV1ScenariosVersionsByVersionIdPathParams["versionId"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    deleteApiV1ScenariosVersionsByVersionIdMutationKey();

  const baseOptions = deleteApiV1ScenariosVersionsByVersionIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1ScenariosVersionsByVersionIdMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1ScenariosVersionsByVersionId400
      | DeleteApiV1ScenariosVersionsByVersionId401
      | DeleteApiV1ScenariosVersionsByVersionId403
      | DeleteApiV1ScenariosVersionsByVersionId404
      | DeleteApiV1ScenariosVersionsByVersionId500
    >,
    {
      versionId: DeleteApiV1ScenariosVersionsByVersionIdPathParams["versionId"];
    },
    TContext
  >;

  return useMutation<
    DeleteApiV1ScenariosVersionsByVersionIdMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1ScenariosVersionsByVersionId400
      | DeleteApiV1ScenariosVersionsByVersionId401
      | DeleteApiV1ScenariosVersionsByVersionId403
      | DeleteApiV1ScenariosVersionsByVersionId404
      | DeleteApiV1ScenariosVersionsByVersionId500
    >,
    {
      versionId: DeleteApiV1ScenariosVersionsByVersionIdPathParams["versionId"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1ScenariosVersionsByVersionIdMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1ScenariosVersionsByVersionId400
      | DeleteApiV1ScenariosVersionsByVersionId401
      | DeleteApiV1ScenariosVersionsByVersionId403
      | DeleteApiV1ScenariosVersionsByVersionId404
      | DeleteApiV1ScenariosVersionsByVersionId500
    >,
    {
      versionId: DeleteApiV1ScenariosVersionsByVersionIdPathParams["versionId"];
    },
    TContext
  >;
}
