/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";

import { deleteApiV1ScenariosScenarioId } from "../clients/delete-api-v1-scenarios-scenario-id.ts";
import type {
  DeleteApiV1ScenariosScenarioId400,
  DeleteApiV1ScenariosScenarioId401,
  DeleteApiV1ScenariosScenarioId403,
  DeleteApiV1ScenariosScenarioId404,
  DeleteApiV1ScenariosScenarioId500,
  DeleteApiV1ScenariosScenarioIdMutationResponse,
  DeleteApiV1ScenariosScenarioIdPathParams,
} from "../models/delete-api-v1-scenarios-scenario-id.ts";

export const deleteApiV1ScenariosScenarioIdMutationKey = () =>
  [{ url: "/api/v1/scenarios/:scenarioId" }] as const;

export type DeleteApiV1ScenariosScenarioIdMutationKey = ReturnType<
  typeof deleteApiV1ScenariosScenarioIdMutationKey
>;

export function deleteApiV1ScenariosScenarioIdMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deleteApiV1ScenariosScenarioIdMutationKey();
  return mutationOptions<
    DeleteApiV1ScenariosScenarioIdMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1ScenariosScenarioId400
      | DeleteApiV1ScenariosScenarioId401
      | DeleteApiV1ScenariosScenarioId403
      | DeleteApiV1ScenariosScenarioId404
      | DeleteApiV1ScenariosScenarioId500
    >,
    { scenarioId: DeleteApiV1ScenariosScenarioIdPathParams["scenarioId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ scenarioId }) => {
      return deleteApiV1ScenariosScenarioId({ scenarioId }, config);
    },
  });
}

/**
 * {@link /api/v1/scenarios/:scenarioId}
 */
export function useDeleteApiV1ScenariosScenarioId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteApiV1ScenariosScenarioIdMutationResponse,
      ResponseErrorConfig<
        | DeleteApiV1ScenariosScenarioId400
        | DeleteApiV1ScenariosScenarioId401
        | DeleteApiV1ScenariosScenarioId403
        | DeleteApiV1ScenariosScenarioId404
        | DeleteApiV1ScenariosScenarioId500
      >,
      { scenarioId: DeleteApiV1ScenariosScenarioIdPathParams["scenarioId"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteApiV1ScenariosScenarioIdMutationKey();

  const baseOptions = deleteApiV1ScenariosScenarioIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteApiV1ScenariosScenarioIdMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1ScenariosScenarioId400
      | DeleteApiV1ScenariosScenarioId401
      | DeleteApiV1ScenariosScenarioId403
      | DeleteApiV1ScenariosScenarioId404
      | DeleteApiV1ScenariosScenarioId500
    >,
    { scenarioId: DeleteApiV1ScenariosScenarioIdPathParams["scenarioId"] },
    TContext
  >;

  return useMutation<
    DeleteApiV1ScenariosScenarioIdMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1ScenariosScenarioId400
      | DeleteApiV1ScenariosScenarioId401
      | DeleteApiV1ScenariosScenarioId403
      | DeleteApiV1ScenariosScenarioId404
      | DeleteApiV1ScenariosScenarioId500
    >,
    { scenarioId: DeleteApiV1ScenariosScenarioIdPathParams["scenarioId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteApiV1ScenariosScenarioIdMutationResponse,
    ResponseErrorConfig<
      | DeleteApiV1ScenariosScenarioId400
      | DeleteApiV1ScenariosScenarioId401
      | DeleteApiV1ScenariosScenarioId403
      | DeleteApiV1ScenariosScenarioId404
      | DeleteApiV1ScenariosScenarioId500
    >,
    { scenarioId: DeleteApiV1ScenariosScenarioIdPathParams["scenarioId"] },
    TContext
  >;
}
