/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { getApiV1ProfilesByProfileIdAttachments } from "../clients/get-api-v1-profiles-by-profile-id-attachments.ts";
import type {
  GetApiV1ProfilesByProfileIdAttachments400,
  GetApiV1ProfilesByProfileIdAttachments401,
  GetApiV1ProfilesByProfileIdAttachments402,
  GetApiV1ProfilesByProfileIdAttachments403,
  GetApiV1ProfilesByProfileIdAttachments404,
  GetApiV1ProfilesByProfileIdAttachments500,
  GetApiV1ProfilesByProfileIdAttachmentsPathParams,
  GetApiV1ProfilesByProfileIdAttachmentsQueryResponse,
} from "../models/get-api-v1-profiles-by-profile-id-attachments.ts";

export const getApiV1ProfilesByProfileIdAttachmentsQueryKey = ({
  profileId,
}: {
  profileId: GetApiV1ProfilesByProfileIdAttachmentsPathParams["profileId"];
}) =>
  [
    {
      url: "/api/v1/profiles/:profileId/attachments",
      params: { profileId: profileId },
    },
  ] as const;

export type GetApiV1ProfilesByProfileIdAttachmentsQueryKey = ReturnType<
  typeof getApiV1ProfilesByProfileIdAttachmentsQueryKey
>;

export function getApiV1ProfilesByProfileIdAttachmentsQueryOptions(
  {
    profileId,
  }: {
    profileId: GetApiV1ProfilesByProfileIdAttachmentsPathParams["profileId"];
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1ProfilesByProfileIdAttachmentsQueryKey({
    profileId,
  });
  return queryOptions<
    GetApiV1ProfilesByProfileIdAttachmentsQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ProfilesByProfileIdAttachments400
      | GetApiV1ProfilesByProfileIdAttachments401
      | GetApiV1ProfilesByProfileIdAttachments402
      | GetApiV1ProfilesByProfileIdAttachments403
      | GetApiV1ProfilesByProfileIdAttachments404
      | GetApiV1ProfilesByProfileIdAttachments500
    >,
    GetApiV1ProfilesByProfileIdAttachmentsQueryResponse,
    typeof queryKey
  >({
    enabled: !!profileId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ProfilesByProfileIdAttachments(
        { profileId: profileId },
        { ...config, signal: config.signal ?? signal },
      );
    },
  });
}

/**
 * {@link /api/v1/profiles/:profileId/attachments}
 */
export function useGetApiV1ProfilesByProfileIdAttachments<
  TData = GetApiV1ProfilesByProfileIdAttachmentsQueryResponse,
  TQueryData = GetApiV1ProfilesByProfileIdAttachmentsQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ProfilesByProfileIdAttachmentsQueryKey,
>(
  {
    profileId,
  }: {
    profileId: GetApiV1ProfilesByProfileIdAttachmentsPathParams["profileId"];
  },
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ProfilesByProfileIdAttachmentsQueryResponse,
        ResponseErrorConfig<
          | GetApiV1ProfilesByProfileIdAttachments400
          | GetApiV1ProfilesByProfileIdAttachments401
          | GetApiV1ProfilesByProfileIdAttachments402
          | GetApiV1ProfilesByProfileIdAttachments403
          | GetApiV1ProfilesByProfileIdAttachments404
          | GetApiV1ProfilesByProfileIdAttachments500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1ProfilesByProfileIdAttachmentsQueryKey({ profileId });

  const query = useQuery(
    {
      ...getApiV1ProfilesByProfileIdAttachmentsQueryOptions(
        { profileId },
        config,
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetApiV1ProfilesByProfileIdAttachments400
      | GetApiV1ProfilesByProfileIdAttachments401
      | GetApiV1ProfilesByProfileIdAttachments402
      | GetApiV1ProfilesByProfileIdAttachments403
      | GetApiV1ProfilesByProfileIdAttachments404
      | GetApiV1ProfilesByProfileIdAttachments500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
