/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";

import { getApiV1ReferralCodesMy } from "../clients/get-api-v1-referral-codes-my.ts";
import type {
  GetApiV1ReferralCodesMy400,
  GetApiV1ReferralCodesMy401,
  GetApiV1ReferralCodesMy403,
  GetApiV1ReferralCodesMy404,
  GetApiV1ReferralCodesMy500,
  GetApiV1ReferralCodesMyQueryResponse,
} from "../models/get-api-v1-referral-codes-my.ts";

export const getApiV1ReferralCodesMyQueryKey = () =>
  [{ url: "/api/v1/referral/codes/my" }] as const;

export type GetApiV1ReferralCodesMyQueryKey = ReturnType<
  typeof getApiV1ReferralCodesMyQueryKey
>;

export function getApiV1ReferralCodesMyQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1ReferralCodesMyQueryKey();
  return queryOptions<
    GetApiV1ReferralCodesMyQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ReferralCodesMy400
      | GetApiV1ReferralCodesMy401
      | GetApiV1ReferralCodesMy403
      | GetApiV1ReferralCodesMy404
      | GetApiV1ReferralCodesMy500
    >,
    GetApiV1ReferralCodesMyQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ReferralCodesMy({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * {@link /api/v1/referral/codes/my}
 */
export function useGetApiV1ReferralCodesMy<
  TData = GetApiV1ReferralCodesMyQueryResponse,
  TQueryData = GetApiV1ReferralCodesMyQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ReferralCodesMyQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ReferralCodesMyQueryResponse,
        ResponseErrorConfig<
          | GetApiV1ReferralCodesMy400
          | GetApiV1ReferralCodesMy401
          | GetApiV1ReferralCodesMy403
          | GetApiV1ReferralCodesMy404
          | GetApiV1ReferralCodesMy500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1ReferralCodesMyQueryKey();

  const query = useQuery(
    {
      ...getApiV1ReferralCodesMyQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetApiV1ReferralCodesMy400
      | GetApiV1ReferralCodesMy401
      | GetApiV1ReferralCodesMy403
      | GetApiV1ReferralCodesMy404
      | GetApiV1ReferralCodesMy500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
