/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import { getApiV1IdeasListsIdeasListId } from "../clients/get-api-v1-ideas-lists-ideas-list-id.ts";
import type {
  GetApiV1IdeasListsIdeasListId400,
  GetApiV1IdeasListsIdeasListId401,
  GetApiV1IdeasListsIdeasListId403,
  GetApiV1IdeasListsIdeasListId404,
  GetApiV1IdeasListsIdeasListId500,
  GetApiV1IdeasListsIdeasListIdPathParams,
  GetApiV1IdeasListsIdeasListIdQueryParams,
  GetApiV1IdeasListsIdeasListIdQueryResponse,
} from "../models/get-api-v1-ideas-lists-ideas-list-id.ts";

export const getApiV1IdeasListsIdeasListIdQueryKey = (
  {
    ideasListId,
  }: { ideasListId: GetApiV1IdeasListsIdeasListIdPathParams["ideasListId"] },
  params: GetApiV1IdeasListsIdeasListIdQueryParams = {},
) =>
  [
    {
      url: "/api/v1/ideas-lists/:ideasListId",
      params: { ideasListId: ideasListId },
    },
    ...(params ? [params] : []),
  ] as const;

export type GetApiV1IdeasListsIdeasListIdQueryKey = ReturnType<
  typeof getApiV1IdeasListsIdeasListIdQueryKey
>;

export function getApiV1IdeasListsIdeasListIdQueryOptions(
  {
    ideasListId,
    params,
  }: {
    ideasListId: GetApiV1IdeasListsIdeasListIdPathParams["ideasListId"];
    params?: GetApiV1IdeasListsIdeasListIdQueryParams;
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1IdeasListsIdeasListIdQueryKey(
    { ideasListId },
    params,
  );
  return queryOptions<
    GetApiV1IdeasListsIdeasListIdQueryResponse,
    ResponseErrorConfig<
      | GetApiV1IdeasListsIdeasListId400
      | GetApiV1IdeasListsIdeasListId401
      | GetApiV1IdeasListsIdeasListId403
      | GetApiV1IdeasListsIdeasListId404
      | GetApiV1IdeasListsIdeasListId500
    >,
    GetApiV1IdeasListsIdeasListIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!ideasListId,
    queryKey,
    queryFn: async ({ signal }) => {
      if (!config.signal) {
        config.signal = signal;
      }
      return getApiV1IdeasListsIdeasListId({ ideasListId, params }, config);
    },
  });
}

/**
 * {@link /api/v1/ideas-lists/:ideasListId}
 */
export function useGetApiV1IdeasListsIdeasListId<
  TData = GetApiV1IdeasListsIdeasListIdQueryResponse,
  TQueryData = GetApiV1IdeasListsIdeasListIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1IdeasListsIdeasListIdQueryKey,
>(
  {
    ideasListId,
    params,
  }: {
    ideasListId: GetApiV1IdeasListsIdeasListIdPathParams["ideasListId"];
    params?: GetApiV1IdeasListsIdeasListIdQueryParams;
  },
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1IdeasListsIdeasListIdQueryResponse,
        ResponseErrorConfig<
          | GetApiV1IdeasListsIdeasListId400
          | GetApiV1IdeasListsIdeasListId401
          | GetApiV1IdeasListsIdeasListId403
          | GetApiV1IdeasListsIdeasListId404
          | GetApiV1IdeasListsIdeasListId500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getApiV1IdeasListsIdeasListIdQueryKey({ ideasListId }, params);

  const query = useQuery(
    {
      ...getApiV1IdeasListsIdeasListIdQueryOptions(
        { ideasListId, params },
        config,
      ),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetApiV1IdeasListsIdeasListId400
      | GetApiV1IdeasListsIdeasListId401
      | GetApiV1IdeasListsIdeasListId403
      | GetApiV1IdeasListsIdeasListId404
      | GetApiV1IdeasListsIdeasListId500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
