/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { getApiV1ProfilesChannelsJobsMy } from "../clients/get-api-v1-profiles-channels-jobs-my.ts";
import type {
  GetApiV1ProfilesChannelsJobsMy400,
  GetApiV1ProfilesChannelsJobsMy401,
  GetApiV1ProfilesChannelsJobsMy402,
  GetApiV1ProfilesChannelsJobsMy403,
  GetApiV1ProfilesChannelsJobsMy404,
  GetApiV1ProfilesChannelsJobsMy500,
  GetApiV1ProfilesChannelsJobsMyQueryResponse,
} from "../models/get-api-v1-profiles-channels-jobs-my.ts";

export const getApiV1ProfilesChannelsJobsMyQueryKey = () =>
  [{ url: "/api/v1/profiles/channels/jobs/my" }] as const;

export type GetApiV1ProfilesChannelsJobsMyQueryKey = ReturnType<
  typeof getApiV1ProfilesChannelsJobsMyQueryKey
>;

export function getApiV1ProfilesChannelsJobsMyQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1ProfilesChannelsJobsMyQueryKey();
  return queryOptions<
    GetApiV1ProfilesChannelsJobsMyQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ProfilesChannelsJobsMy400
      | GetApiV1ProfilesChannelsJobsMy401
      | GetApiV1ProfilesChannelsJobsMy402
      | GetApiV1ProfilesChannelsJobsMy403
      | GetApiV1ProfilesChannelsJobsMy404
      | GetApiV1ProfilesChannelsJobsMy500
    >,
    GetApiV1ProfilesChannelsJobsMyQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ProfilesChannelsJobsMy({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * {@link /api/v1/profiles/channels/jobs/my}
 */
export function useGetApiV1ProfilesChannelsJobsMy<
  TData = GetApiV1ProfilesChannelsJobsMyQueryResponse,
  TQueryData = GetApiV1ProfilesChannelsJobsMyQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ProfilesChannelsJobsMyQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ProfilesChannelsJobsMyQueryResponse,
        ResponseErrorConfig<
          | GetApiV1ProfilesChannelsJobsMy400
          | GetApiV1ProfilesChannelsJobsMy401
          | GetApiV1ProfilesChannelsJobsMy402
          | GetApiV1ProfilesChannelsJobsMy403
          | GetApiV1ProfilesChannelsJobsMy404
          | GetApiV1ProfilesChannelsJobsMy500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1ProfilesChannelsJobsMyQueryKey();

  const query = useQuery(
    {
      ...getApiV1ProfilesChannelsJobsMyQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetApiV1ProfilesChannelsJobsMy400
      | GetApiV1ProfilesChannelsJobsMy401
      | GetApiV1ProfilesChannelsJobsMy402
      | GetApiV1ProfilesChannelsJobsMy403
      | GetApiV1ProfilesChannelsJobsMy404
      | GetApiV1ProfilesChannelsJobsMy500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
