/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";

import { getApiV1ScenariosByScenarioIdVersions } from "../clients/get-api-v1-scenarios-by-scenario-id-versions.ts";
import type {
  GetApiV1ScenariosByScenarioIdVersions400,
  GetApiV1ScenariosByScenarioIdVersions401,
  GetApiV1ScenariosByScenarioIdVersions403,
  GetApiV1ScenariosByScenarioIdVersions404,
  GetApiV1ScenariosByScenarioIdVersions500,
  GetApiV1ScenariosByScenarioIdVersionsPathParams,
  GetApiV1ScenariosByScenarioIdVersionsQueryResponse,
} from "../models/get-api-v1-scenarios-by-scenario-id-versions.ts";

export const getApiV1ScenariosByScenarioIdVersionsQueryKey = ({
  scenarioId,
}: {
  scenarioId: GetApiV1ScenariosByScenarioIdVersionsPathParams["scenarioId"];
}) =>
  [
    {
      url: "/api/v1/scenarios/:scenarioId/versions",
      params: { scenarioId: scenarioId },
    },
  ] as const;

export type GetApiV1ScenariosByScenarioIdVersionsQueryKey = ReturnType<
  typeof getApiV1ScenariosByScenarioIdVersionsQueryKey
>;

export function getApiV1ScenariosByScenarioIdVersionsQueryOptions(
  {
    scenarioId,
  }: {
    scenarioId: GetApiV1ScenariosByScenarioIdVersionsPathParams["scenarioId"];
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1ScenariosByScenarioIdVersionsQueryKey({
    scenarioId,
  });
  return queryOptions<
    GetApiV1ScenariosByScenarioIdVersionsQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ScenariosByScenarioIdVersions400
      | GetApiV1ScenariosByScenarioIdVersions401
      | GetApiV1ScenariosByScenarioIdVersions403
      | GetApiV1ScenariosByScenarioIdVersions404
      | GetApiV1ScenariosByScenarioIdVersions500
    >,
    GetApiV1ScenariosByScenarioIdVersionsQueryResponse,
    typeof queryKey
  >({
    enabled: !!scenarioId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ScenariosByScenarioIdVersions(
        { scenarioId: scenarioId },
        { ...config, signal: config.signal ?? signal },
      );
    },
  });
}

/**
 * {@link /api/v1/scenarios/:scenarioId/versions}
 */
export function useGetApiV1ScenariosByScenarioIdVersions<
  TData = GetApiV1ScenariosByScenarioIdVersionsQueryResponse,
  TQueryData = GetApiV1ScenariosByScenarioIdVersionsQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ScenariosByScenarioIdVersionsQueryKey,
>(
  {
    scenarioId,
  }: {
    scenarioId: GetApiV1ScenariosByScenarioIdVersionsPathParams["scenarioId"];
  },
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ScenariosByScenarioIdVersionsQueryResponse,
        ResponseErrorConfig<
          | GetApiV1ScenariosByScenarioIdVersions400
          | GetApiV1ScenariosByScenarioIdVersions401
          | GetApiV1ScenariosByScenarioIdVersions403
          | GetApiV1ScenariosByScenarioIdVersions404
          | GetApiV1ScenariosByScenarioIdVersions500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1ScenariosByScenarioIdVersionsQueryKey({ scenarioId });

  const query = useQuery(
    {
      ...getApiV1ScenariosByScenarioIdVersionsQueryOptions(
        { scenarioId },
        config,
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetApiV1ScenariosByScenarioIdVersions400
      | GetApiV1ScenariosByScenarioIdVersions401
      | GetApiV1ScenariosByScenarioIdVersions403
      | GetApiV1ScenariosByScenarioIdVersions404
      | GetApiV1ScenariosByScenarioIdVersions500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
