/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { getApiV1ScenariosVersionsByVersionId } from "../clients/get-api-v1-scenarios-versions-by-version-id.ts";
import type {
  GetApiV1ScenariosVersionsByVersionId400,
  GetApiV1ScenariosVersionsByVersionId401,
  GetApiV1ScenariosVersionsByVersionId403,
  GetApiV1ScenariosVersionsByVersionId404,
  GetApiV1ScenariosVersionsByVersionId500,
  GetApiV1ScenariosVersionsByVersionIdPathParams,
  GetApiV1ScenariosVersionsByVersionIdQueryResponse,
} from "../models/get-api-v1-scenarios-versions-by-version-id.ts";

export const getApiV1ScenariosVersionsByVersionIdQueryKey = ({
  versionId,
}: {
  versionId: GetApiV1ScenariosVersionsByVersionIdPathParams["versionId"];
}) =>
  [
    {
      url: "/api/v1/scenarios/versions/:versionId",
      params: { versionId: versionId },
    },
  ] as const;

export type GetApiV1ScenariosVersionsByVersionIdQueryKey = ReturnType<
  typeof getApiV1ScenariosVersionsByVersionIdQueryKey
>;

export function getApiV1ScenariosVersionsByVersionIdQueryOptions(
  {
    versionId,
  }: { versionId: GetApiV1ScenariosVersionsByVersionIdPathParams["versionId"] },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1ScenariosVersionsByVersionIdQueryKey({ versionId });
  return queryOptions<
    GetApiV1ScenariosVersionsByVersionIdQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ScenariosVersionsByVersionId400
      | GetApiV1ScenariosVersionsByVersionId401
      | GetApiV1ScenariosVersionsByVersionId403
      | GetApiV1ScenariosVersionsByVersionId404
      | GetApiV1ScenariosVersionsByVersionId500
    >,
    GetApiV1ScenariosVersionsByVersionIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!versionId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ScenariosVersionsByVersionId(
        { versionId: versionId },
        { ...config, signal: config.signal ?? signal },
      );
    },
  });
}

/**
 * {@link /api/v1/scenarios/versions/:versionId}
 */
export function useGetApiV1ScenariosVersionsByVersionId<
  TData = GetApiV1ScenariosVersionsByVersionIdQueryResponse,
  TQueryData = GetApiV1ScenariosVersionsByVersionIdQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ScenariosVersionsByVersionIdQueryKey,
>(
  {
    versionId,
  }: { versionId: GetApiV1ScenariosVersionsByVersionIdPathParams["versionId"] },
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ScenariosVersionsByVersionIdQueryResponse,
        ResponseErrorConfig<
          | GetApiV1ScenariosVersionsByVersionId400
          | GetApiV1ScenariosVersionsByVersionId401
          | GetApiV1ScenariosVersionsByVersionId403
          | GetApiV1ScenariosVersionsByVersionId404
          | GetApiV1ScenariosVersionsByVersionId500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1ScenariosVersionsByVersionIdQueryKey({ versionId });

  const query = useQuery(
    {
      ...getApiV1ScenariosVersionsByVersionIdQueryOptions(
        { versionId },
        config,
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetApiV1ScenariosVersionsByVersionId400
      | GetApiV1ScenariosVersionsByVersionId401
      | GetApiV1ScenariosVersionsByVersionId403
      | GetApiV1ScenariosVersionsByVersionId404
      | GetApiV1ScenariosVersionsByVersionId500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
