/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { getApiV1ProductionStatuses } from "../clients/get-api-v1-production-statuses.ts";
import type {
  GetApiV1ProductionStatuses400,
  GetApiV1ProductionStatuses401,
  GetApiV1ProductionStatuses402,
  GetApiV1ProductionStatuses403,
  GetApiV1ProductionStatuses404,
  GetApiV1ProductionStatuses500,
  GetApiV1ProductionStatusesQueryParams,
  GetApiV1ProductionStatusesQueryResponse,
} from "../models/get-api-v1-production-statuses.ts";

export const getApiV1ProductionStatusesQueryKey = (
  params: GetApiV1ProductionStatusesQueryParams,
) =>
  [
    { url: "/api/v1/production-statuses" },
    ...(params ? [params] : []),
  ] as const;

export type GetApiV1ProductionStatusesQueryKey = ReturnType<
  typeof getApiV1ProductionStatusesQueryKey
>;

export function getApiV1ProductionStatusesQueryOptions(
  { params }: { params: GetApiV1ProductionStatusesQueryParams },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1ProductionStatusesQueryKey(params);
  return queryOptions<
    GetApiV1ProductionStatusesQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ProductionStatuses400
      | GetApiV1ProductionStatuses401
      | GetApiV1ProductionStatuses402
      | GetApiV1ProductionStatuses403
      | GetApiV1ProductionStatuses404
      | GetApiV1ProductionStatuses500
    >,
    GetApiV1ProductionStatusesQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ProductionStatuses(
        { params: params },
        { ...config, signal: config.signal ?? signal },
      );
    },
  });
}

/**
 * {@link /api/v1/production-statuses}
 */
export function useGetApiV1ProductionStatuses<
  TData = GetApiV1ProductionStatusesQueryResponse,
  TQueryData = GetApiV1ProductionStatusesQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ProductionStatusesQueryKey,
>(
  { params }: { params: GetApiV1ProductionStatusesQueryParams },
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ProductionStatusesQueryResponse,
        ResponseErrorConfig<
          | GetApiV1ProductionStatuses400
          | GetApiV1ProductionStatuses401
          | GetApiV1ProductionStatuses402
          | GetApiV1ProductionStatuses403
          | GetApiV1ProductionStatuses404
          | GetApiV1ProductionStatuses500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1ProductionStatusesQueryKey(params);

  const query = useQuery(
    {
      ...getApiV1ProductionStatusesQueryOptions({ params }, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetApiV1ProductionStatuses400
      | GetApiV1ProductionStatuses401
      | GetApiV1ProductionStatuses402
      | GetApiV1ProductionStatuses403
      | GetApiV1ProductionStatuses404
      | GetApiV1ProductionStatuses500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
