/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { getApiV1ProductFeatures } from "../clients/get-api-v1-product-features.ts";
import type {
  GetApiV1ProductFeatures400,
  GetApiV1ProductFeatures401,
  GetApiV1ProductFeatures402,
  GetApiV1ProductFeatures403,
  GetApiV1ProductFeatures404,
  GetApiV1ProductFeatures500,
  GetApiV1ProductFeaturesQueryResponse,
} from "../models/get-api-v1-product-features.ts";

export const getApiV1ProductFeaturesQueryKey = () =>
  [{ url: "/api/v1/product-features" }] as const;

export type GetApiV1ProductFeaturesQueryKey = ReturnType<
  typeof getApiV1ProductFeaturesQueryKey
>;

export function getApiV1ProductFeaturesQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1ProductFeaturesQueryKey();
  return queryOptions<
    GetApiV1ProductFeaturesQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ProductFeatures400
      | GetApiV1ProductFeatures401
      | GetApiV1ProductFeatures402
      | GetApiV1ProductFeatures403
      | GetApiV1ProductFeatures404
      | GetApiV1ProductFeatures500
    >,
    GetApiV1ProductFeaturesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ProductFeatures({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * {@link /api/v1/product-features}
 */
export function useGetApiV1ProductFeatures<
  TData = GetApiV1ProductFeaturesQueryResponse,
  TQueryData = GetApiV1ProductFeaturesQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ProductFeaturesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ProductFeaturesQueryResponse,
        ResponseErrorConfig<
          | GetApiV1ProductFeatures400
          | GetApiV1ProductFeatures401
          | GetApiV1ProductFeatures402
          | GetApiV1ProductFeatures403
          | GetApiV1ProductFeatures404
          | GetApiV1ProductFeatures500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getApiV1ProductFeaturesQueryKey();

  const query = useQuery(
    {
      ...getApiV1ProductFeaturesQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetApiV1ProductFeatures400
      | GetApiV1ProductFeatures401
      | GetApiV1ProductFeatures402
      | GetApiV1ProductFeatures403
      | GetApiV1ProductFeatures404
      | GetApiV1ProductFeatures500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
