/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { getApiV1ProfilesByProfileIdChannelVideos } from "../clients/get-api-v1-profiles-by-profile-id-channel-videos.ts";
import type {
  GetApiV1ProfilesByProfileIdChannelVideos400,
  GetApiV1ProfilesByProfileIdChannelVideos401,
  GetApiV1ProfilesByProfileIdChannelVideos402,
  GetApiV1ProfilesByProfileIdChannelVideos403,
  GetApiV1ProfilesByProfileIdChannelVideos404,
  GetApiV1ProfilesByProfileIdChannelVideos500,
  GetApiV1ProfilesByProfileIdChannelVideosPathParams,
  GetApiV1ProfilesByProfileIdChannelVideosQueryResponse,
} from "../models/get-api-v1-profiles-by-profile-id-channel-videos.ts";

export const getApiV1ProfilesByProfileIdChannelVideosQueryKey = ({
  profileId,
}: {
  profileId: GetApiV1ProfilesByProfileIdChannelVideosPathParams["profileId"];
}) =>
  [
    {
      url: "/api/v1/profiles/:profileId/channel-videos",
      params: { profileId: profileId },
    },
  ] as const;

export type GetApiV1ProfilesByProfileIdChannelVideosQueryKey = ReturnType<
  typeof getApiV1ProfilesByProfileIdChannelVideosQueryKey
>;

export function getApiV1ProfilesByProfileIdChannelVideosQueryOptions(
  {
    profileId,
  }: {
    profileId: GetApiV1ProfilesByProfileIdChannelVideosPathParams["profileId"];
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1ProfilesByProfileIdChannelVideosQueryKey({
    profileId,
  });
  return queryOptions<
    GetApiV1ProfilesByProfileIdChannelVideosQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ProfilesByProfileIdChannelVideos400
      | GetApiV1ProfilesByProfileIdChannelVideos401
      | GetApiV1ProfilesByProfileIdChannelVideos402
      | GetApiV1ProfilesByProfileIdChannelVideos403
      | GetApiV1ProfilesByProfileIdChannelVideos404
      | GetApiV1ProfilesByProfileIdChannelVideos500
    >,
    GetApiV1ProfilesByProfileIdChannelVideosQueryResponse,
    typeof queryKey
  >({
    enabled: !!profileId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ProfilesByProfileIdChannelVideos(
        { profileId: profileId },
        { ...config, signal: config.signal ?? signal },
      );
    },
  });
}

/**
 * {@link /api/v1/profiles/:profileId/channel-videos}
 */
export function useGetApiV1ProfilesByProfileIdChannelVideos<
  TData = GetApiV1ProfilesByProfileIdChannelVideosQueryResponse,
  TQueryData = GetApiV1ProfilesByProfileIdChannelVideosQueryResponse,
  TQueryKey extends QueryKey = GetApiV1ProfilesByProfileIdChannelVideosQueryKey,
>(
  {
    profileId,
  }: {
    profileId: GetApiV1ProfilesByProfileIdChannelVideosPathParams["profileId"];
  },
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ProfilesByProfileIdChannelVideosQueryResponse,
        ResponseErrorConfig<
          | GetApiV1ProfilesByProfileIdChannelVideos400
          | GetApiV1ProfilesByProfileIdChannelVideos401
          | GetApiV1ProfilesByProfileIdChannelVideos402
          | GetApiV1ProfilesByProfileIdChannelVideos403
          | GetApiV1ProfilesByProfileIdChannelVideos404
          | GetApiV1ProfilesByProfileIdChannelVideos500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1ProfilesByProfileIdChannelVideosQueryKey({ profileId });

  const query = useQuery(
    {
      ...getApiV1ProfilesByProfileIdChannelVideosQueryOptions(
        { profileId },
        config,
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetApiV1ProfilesByProfileIdChannelVideos400
      | GetApiV1ProfilesByProfileIdChannelVideos401
      | GetApiV1ProfilesByProfileIdChannelVideos402
      | GetApiV1ProfilesByProfileIdChannelVideos403
      | GetApiV1ProfilesByProfileIdChannelVideos404
      | GetApiV1ProfilesByProfileIdChannelVideos500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
