/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";

import { getApiV1ScenariosVersionsByVersionIdExport } from "../clients/get-api-v1-scenarios-versions-by-version-id-export.ts";
import type {
  GetApiV1ScenariosVersionsByVersionIdExport400,
  GetApiV1ScenariosVersionsByVersionIdExport401,
  GetApiV1ScenariosVersionsByVersionIdExport403,
  GetApiV1ScenariosVersionsByVersionIdExport404,
  GetApiV1ScenariosVersionsByVersionIdExport500,
  GetApiV1ScenariosVersionsByVersionIdExportPathParams,
  GetApiV1ScenariosVersionsByVersionIdExportQueryParams,
  GetApiV1ScenariosVersionsByVersionIdExportQueryResponse,
} from "../models/get-api-v1-scenarios-versions-by-version-id-export.ts";

export const getApiV1ScenariosVersionsByVersionIdExportQueryKey = (
  {
    versionId,
  }: {
    versionId: GetApiV1ScenariosVersionsByVersionIdExportPathParams["versionId"];
  },
  params: GetApiV1ScenariosVersionsByVersionIdExportQueryParams,
) =>
  [
    {
      url: "/api/v1/scenarios/versions/:versionId/export",
      params: { versionId: versionId },
    },
    ...(params ? [params] : []),
  ] as const;

export type GetApiV1ScenariosVersionsByVersionIdExportQueryKey = ReturnType<
  typeof getApiV1ScenariosVersionsByVersionIdExportQueryKey
>;

export function getApiV1ScenariosVersionsByVersionIdExportQueryOptions(
  {
    versionId,
    params,
  }: {
    versionId: GetApiV1ScenariosVersionsByVersionIdExportPathParams["versionId"];
    params: GetApiV1ScenariosVersionsByVersionIdExportQueryParams;
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1ScenariosVersionsByVersionIdExportQueryKey(
    { versionId },
    params,
  );
  return queryOptions<
    GetApiV1ScenariosVersionsByVersionIdExportQueryResponse,
    ResponseErrorConfig<
      | GetApiV1ScenariosVersionsByVersionIdExport400
      | GetApiV1ScenariosVersionsByVersionIdExport401
      | GetApiV1ScenariosVersionsByVersionIdExport403
      | GetApiV1ScenariosVersionsByVersionIdExport404
      | GetApiV1ScenariosVersionsByVersionIdExport500
    >,
    GetApiV1ScenariosVersionsByVersionIdExportQueryResponse,
    typeof queryKey
  >({
    enabled: !!(versionId && params),
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1ScenariosVersionsByVersionIdExport(
        { versionId: versionId, params: params },
        { ...config, signal: config.signal ?? signal },
      );
    },
  });
}

/**
 * {@link /api/v1/scenarios/versions/:versionId/export}
 */
export function useGetApiV1ScenariosVersionsByVersionIdExport<
  TData = GetApiV1ScenariosVersionsByVersionIdExportQueryResponse,
  TQueryData = GetApiV1ScenariosVersionsByVersionIdExportQueryResponse,
  TQueryKey extends QueryKey =
    GetApiV1ScenariosVersionsByVersionIdExportQueryKey,
>(
  {
    versionId,
    params,
  }: {
    versionId: GetApiV1ScenariosVersionsByVersionIdExportPathParams["versionId"];
    params: GetApiV1ScenariosVersionsByVersionIdExportQueryParams;
  },
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1ScenariosVersionsByVersionIdExportQueryResponse,
        ResponseErrorConfig<
          | GetApiV1ScenariosVersionsByVersionIdExport400
          | GetApiV1ScenariosVersionsByVersionIdExport401
          | GetApiV1ScenariosVersionsByVersionIdExport403
          | GetApiV1ScenariosVersionsByVersionIdExport404
          | GetApiV1ScenariosVersionsByVersionIdExport500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1ScenariosVersionsByVersionIdExportQueryKey({ versionId }, params);

  const query = useQuery(
    {
      ...getApiV1ScenariosVersionsByVersionIdExportQueryOptions(
        { versionId, params },
        config,
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetApiV1ScenariosVersionsByVersionIdExport400
      | GetApiV1ScenariosVersionsByVersionIdExport401
      | GetApiV1ScenariosVersionsByVersionIdExport403
      | GetApiV1ScenariosVersionsByVersionIdExport404
      | GetApiV1ScenariosVersionsByVersionIdExport500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
