/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  QueryKey,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";

import { getApiV1IdeasListsByIdeasListIdExport } from "../clients/get-api-v1-ideas-lists-by-ideas-list-id-export.ts";
import type {
  GetApiV1IdeasListsByIdeasListIdExport400,
  GetApiV1IdeasListsByIdeasListIdExport401,
  GetApiV1IdeasListsByIdeasListIdExport403,
  GetApiV1IdeasListsByIdeasListIdExport404,
  GetApiV1IdeasListsByIdeasListIdExport500,
  GetApiV1IdeasListsByIdeasListIdExportPathParams,
  GetApiV1IdeasListsByIdeasListIdExportQueryParams,
  GetApiV1IdeasListsByIdeasListIdExportQueryResponse,
} from "../models/get-api-v1-ideas-lists-by-ideas-list-id-export.ts";

export const getApiV1IdeasListsByIdeasListIdExportQueryKey = (
  {
    ideasListId,
  }: {
    ideasListId: GetApiV1IdeasListsByIdeasListIdExportPathParams["ideasListId"];
  },
  params: GetApiV1IdeasListsByIdeasListIdExportQueryParams,
) =>
  [
    {
      url: "/api/v1/ideas-lists/:ideasListId/export",
      params: { ideasListId: ideasListId },
    },
    ...(params ? [params] : []),
  ] as const;

export type GetApiV1IdeasListsByIdeasListIdExportQueryKey = ReturnType<
  typeof getApiV1IdeasListsByIdeasListIdExportQueryKey
>;

export function getApiV1IdeasListsByIdeasListIdExportQueryOptions(
  {
    ideasListId,
    params,
  }: {
    ideasListId: GetApiV1IdeasListsByIdeasListIdExportPathParams["ideasListId"];
    params: GetApiV1IdeasListsByIdeasListIdExportQueryParams;
  },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getApiV1IdeasListsByIdeasListIdExportQueryKey(
    { ideasListId },
    params,
  );
  return queryOptions<
    GetApiV1IdeasListsByIdeasListIdExportQueryResponse,
    ResponseErrorConfig<
      | GetApiV1IdeasListsByIdeasListIdExport400
      | GetApiV1IdeasListsByIdeasListIdExport401
      | GetApiV1IdeasListsByIdeasListIdExport403
      | GetApiV1IdeasListsByIdeasListIdExport404
      | GetApiV1IdeasListsByIdeasListIdExport500
    >,
    GetApiV1IdeasListsByIdeasListIdExportQueryResponse,
    typeof queryKey
  >({
    enabled: !!(ideasListId && params),
    queryKey,
    queryFn: async ({ signal }) => {
      return getApiV1IdeasListsByIdeasListIdExport(
        { ideasListId: ideasListId, params: params },
        { ...config, signal: config.signal ?? signal },
      );
    },
  });
}

/**
 * {@link /api/v1/ideas-lists/:ideasListId/export}
 */
export function useGetApiV1IdeasListsByIdeasListIdExport<
  TData = GetApiV1IdeasListsByIdeasListIdExportQueryResponse,
  TQueryData = GetApiV1IdeasListsByIdeasListIdExportQueryResponse,
  TQueryKey extends QueryKey = GetApiV1IdeasListsByIdeasListIdExportQueryKey,
>(
  {
    ideasListId,
    params,
  }: {
    ideasListId: GetApiV1IdeasListsByIdeasListIdExportPathParams["ideasListId"];
    params: GetApiV1IdeasListsByIdeasListIdExportQueryParams;
  },
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetApiV1IdeasListsByIdeasListIdExportQueryResponse,
        ResponseErrorConfig<
          | GetApiV1IdeasListsByIdeasListIdExport400
          | GetApiV1IdeasListsByIdeasListIdExport401
          | GetApiV1IdeasListsByIdeasListIdExport403
          | GetApiV1IdeasListsByIdeasListIdExport404
          | GetApiV1IdeasListsByIdeasListIdExport500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getApiV1IdeasListsByIdeasListIdExportQueryKey({ ideasListId }, params);

  const query = useQuery(
    {
      ...getApiV1IdeasListsByIdeasListIdExportQueryOptions(
        { ideasListId, params },
        config,
      ),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetApiV1IdeasListsByIdeasListIdExport400
      | GetApiV1IdeasListsByIdeasListIdExport401
      | GetApiV1IdeasListsByIdeasListIdExport403
      | GetApiV1IdeasListsByIdeasListIdExport404
      | GetApiV1IdeasListsByIdeasListIdExport500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
