/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";

import { patchApiV1IdeasListsIdeasListId } from "../clients/patch-api-v1-ideas-lists-ideas-list-id.ts";
import type {
  PatchApiV1IdeasListsIdeasListId400,
  PatchApiV1IdeasListsIdeasListId401,
  PatchApiV1IdeasListsIdeasListId403,
  PatchApiV1IdeasListsIdeasListId404,
  PatchApiV1IdeasListsIdeasListId500,
  PatchApiV1IdeasListsIdeasListIdMutationRequest,
  PatchApiV1IdeasListsIdeasListIdMutationResponse,
  PatchApiV1IdeasListsIdeasListIdPathParams,
} from "../models/patch-api-v1-ideas-lists-ideas-list-id.ts";

export const patchApiV1IdeasListsIdeasListIdMutationKey = () =>
  [{ url: "/api/v1/ideas-lists/:ideasListId" }] as const;

export type PatchApiV1IdeasListsIdeasListIdMutationKey = ReturnType<
  typeof patchApiV1IdeasListsIdeasListIdMutationKey
>;

export function patchApiV1IdeasListsIdeasListIdMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PatchApiV1IdeasListsIdeasListIdMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = patchApiV1IdeasListsIdeasListIdMutationKey();
  return mutationOptions<
    PatchApiV1IdeasListsIdeasListIdMutationResponse,
    ResponseErrorConfig<
      | PatchApiV1IdeasListsIdeasListId400
      | PatchApiV1IdeasListsIdeasListId401
      | PatchApiV1IdeasListsIdeasListId403
      | PatchApiV1IdeasListsIdeasListId404
      | PatchApiV1IdeasListsIdeasListId500
    >,
    {
      ideasListId: PatchApiV1IdeasListsIdeasListIdPathParams["ideasListId"];
      data?: PatchApiV1IdeasListsIdeasListIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ ideasListId, data }) => {
      return patchApiV1IdeasListsIdeasListId({ ideasListId, data }, config);
    },
  });
}

/**
 * {@link /api/v1/ideas-lists/:ideasListId}
 */
export function usePatchApiV1IdeasListsIdeasListId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchApiV1IdeasListsIdeasListIdMutationResponse,
      ResponseErrorConfig<
        | PatchApiV1IdeasListsIdeasListId400
        | PatchApiV1IdeasListsIdeasListId401
        | PatchApiV1IdeasListsIdeasListId403
        | PatchApiV1IdeasListsIdeasListId404
        | PatchApiV1IdeasListsIdeasListId500
      >,
      {
        ideasListId: PatchApiV1IdeasListsIdeasListIdPathParams["ideasListId"];
        data?: PatchApiV1IdeasListsIdeasListIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PatchApiV1IdeasListsIdeasListIdMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchApiV1IdeasListsIdeasListIdMutationKey();

  const baseOptions = patchApiV1IdeasListsIdeasListIdMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchApiV1IdeasListsIdeasListIdMutationResponse,
    ResponseErrorConfig<
      | PatchApiV1IdeasListsIdeasListId400
      | PatchApiV1IdeasListsIdeasListId401
      | PatchApiV1IdeasListsIdeasListId403
      | PatchApiV1IdeasListsIdeasListId404
      | PatchApiV1IdeasListsIdeasListId500
    >,
    {
      ideasListId: PatchApiV1IdeasListsIdeasListIdPathParams["ideasListId"];
      data?: PatchApiV1IdeasListsIdeasListIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchApiV1IdeasListsIdeasListIdMutationResponse,
    ResponseErrorConfig<
      | PatchApiV1IdeasListsIdeasListId400
      | PatchApiV1IdeasListsIdeasListId401
      | PatchApiV1IdeasListsIdeasListId403
      | PatchApiV1IdeasListsIdeasListId404
      | PatchApiV1IdeasListsIdeasListId500
    >,
    {
      ideasListId: PatchApiV1IdeasListsIdeasListIdPathParams["ideasListId"];
      data?: PatchApiV1IdeasListsIdeasListIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchApiV1IdeasListsIdeasListIdMutationResponse,
    ResponseErrorConfig<
      | PatchApiV1IdeasListsIdeasListId400
      | PatchApiV1IdeasListsIdeasListId401
      | PatchApiV1IdeasListsIdeasListId403
      | PatchApiV1IdeasListsIdeasListId404
      | PatchApiV1IdeasListsIdeasListId500
    >,
    {
      ideasListId: PatchApiV1IdeasListsIdeasListIdPathParams["ideasListId"];
      data?: PatchApiV1IdeasListsIdeasListIdMutationRequest;
    },
    TContext
  >;
}
