/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import { patchApiV1ScenariosScenarioIdCurrentVersion } from "../clients/patch-api-v1-scenarios-scenario-id-current-version.ts";
import type {
  PatchApiV1ScenariosScenarioIdCurrentVersion400,
  PatchApiV1ScenariosScenarioIdCurrentVersion401,
  PatchApiV1ScenariosScenarioIdCurrentVersion403,
  PatchApiV1ScenariosScenarioIdCurrentVersion404,
  PatchApiV1ScenariosScenarioIdCurrentVersion500,
  PatchApiV1ScenariosScenarioIdCurrentVersionMutationRequest,
  PatchApiV1ScenariosScenarioIdCurrentVersionMutationResponse,
  PatchApiV1ScenariosScenarioIdCurrentVersionPathParams,
} from "../models/patch-api-v1-scenarios-scenario-id-current-version.ts";

export const patchApiV1ScenariosScenarioIdCurrentVersionMutationKey = () =>
  [{ url: "/api/v1/scenarios/:scenarioId/current-version" }] as const;

export type PatchApiV1ScenariosScenarioIdCurrentVersionMutationKey = ReturnType<
  typeof patchApiV1ScenariosScenarioIdCurrentVersionMutationKey
>;

export function patchApiV1ScenariosScenarioIdCurrentVersionMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PatchApiV1ScenariosScenarioIdCurrentVersionMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = patchApiV1ScenariosScenarioIdCurrentVersionMutationKey();
  return mutationOptions<
    PatchApiV1ScenariosScenarioIdCurrentVersionMutationResponse,
    ResponseErrorConfig<
      | PatchApiV1ScenariosScenarioIdCurrentVersion400
      | PatchApiV1ScenariosScenarioIdCurrentVersion401
      | PatchApiV1ScenariosScenarioIdCurrentVersion403
      | PatchApiV1ScenariosScenarioIdCurrentVersion404
      | PatchApiV1ScenariosScenarioIdCurrentVersion500
    >,
    {
      scenarioId: PatchApiV1ScenariosScenarioIdCurrentVersionPathParams["scenarioId"];
      data: PatchApiV1ScenariosScenarioIdCurrentVersionMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ scenarioId, data }) => {
      return patchApiV1ScenariosScenarioIdCurrentVersion(
        { scenarioId, data },
        config,
      );
    },
  });
}

/**
 * {@link /api/v1/scenarios/:scenarioId/current-version}
 */
export function usePatchApiV1ScenariosScenarioIdCurrentVersion<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchApiV1ScenariosScenarioIdCurrentVersionMutationResponse,
      ResponseErrorConfig<
        | PatchApiV1ScenariosScenarioIdCurrentVersion400
        | PatchApiV1ScenariosScenarioIdCurrentVersion401
        | PatchApiV1ScenariosScenarioIdCurrentVersion403
        | PatchApiV1ScenariosScenarioIdCurrentVersion404
        | PatchApiV1ScenariosScenarioIdCurrentVersion500
      >,
      {
        scenarioId: PatchApiV1ScenariosScenarioIdCurrentVersionPathParams["scenarioId"];
        data: PatchApiV1ScenariosScenarioIdCurrentVersionMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PatchApiV1ScenariosScenarioIdCurrentVersionMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    patchApiV1ScenariosScenarioIdCurrentVersionMutationKey();

  const baseOptions =
    patchApiV1ScenariosScenarioIdCurrentVersionMutationOptions(
      config,
    ) as UseMutationOptions<
      PatchApiV1ScenariosScenarioIdCurrentVersionMutationResponse,
      ResponseErrorConfig<
        | PatchApiV1ScenariosScenarioIdCurrentVersion400
        | PatchApiV1ScenariosScenarioIdCurrentVersion401
        | PatchApiV1ScenariosScenarioIdCurrentVersion403
        | PatchApiV1ScenariosScenarioIdCurrentVersion404
        | PatchApiV1ScenariosScenarioIdCurrentVersion500
      >,
      {
        scenarioId: PatchApiV1ScenariosScenarioIdCurrentVersionPathParams["scenarioId"];
        data: PatchApiV1ScenariosScenarioIdCurrentVersionMutationRequest;
      },
      TContext
    >;

  return useMutation<
    PatchApiV1ScenariosScenarioIdCurrentVersionMutationResponse,
    ResponseErrorConfig<
      | PatchApiV1ScenariosScenarioIdCurrentVersion400
      | PatchApiV1ScenariosScenarioIdCurrentVersion401
      | PatchApiV1ScenariosScenarioIdCurrentVersion403
      | PatchApiV1ScenariosScenarioIdCurrentVersion404
      | PatchApiV1ScenariosScenarioIdCurrentVersion500
    >,
    {
      scenarioId: PatchApiV1ScenariosScenarioIdCurrentVersionPathParams["scenarioId"];
      data: PatchApiV1ScenariosScenarioIdCurrentVersionMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchApiV1ScenariosScenarioIdCurrentVersionMutationResponse,
    ResponseErrorConfig<
      | PatchApiV1ScenariosScenarioIdCurrentVersion400
      | PatchApiV1ScenariosScenarioIdCurrentVersion401
      | PatchApiV1ScenariosScenarioIdCurrentVersion403
      | PatchApiV1ScenariosScenarioIdCurrentVersion404
      | PatchApiV1ScenariosScenarioIdCurrentVersion500
    >,
    {
      scenarioId: PatchApiV1ScenariosScenarioIdCurrentVersionPathParams["scenarioId"];
      data: PatchApiV1ScenariosScenarioIdCurrentVersionMutationRequest;
    },
    TContext
  >;
}
