/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { postApiV1IdeasListsByIdeasListIdIdeas } from "../clients/post-api-v1-ideas-lists-by-ideas-list-id-ideas.ts";
import type {
  PostApiV1IdeasListsByIdeasListIdIdeas400,
  PostApiV1IdeasListsByIdeasListIdIdeas401,
  PostApiV1IdeasListsByIdeasListIdIdeas403,
  PostApiV1IdeasListsByIdeasListIdIdeas404,
  PostApiV1IdeasListsByIdeasListIdIdeas500,
  PostApiV1IdeasListsByIdeasListIdIdeasMutationRequest,
  PostApiV1IdeasListsByIdeasListIdIdeasMutationResponse,
  PostApiV1IdeasListsByIdeasListIdIdeasPathParams,
} from "../models/post-api-v1-ideas-lists-by-ideas-list-id-ideas.ts";

export const postApiV1IdeasListsByIdeasListIdIdeasMutationKey = () =>
  [{ url: "/api/v1/ideas-lists/:ideasListId/ideas" }] as const;

export type PostApiV1IdeasListsByIdeasListIdIdeasMutationKey = ReturnType<
  typeof postApiV1IdeasListsByIdeasListIdIdeasMutationKey
>;

export function postApiV1IdeasListsByIdeasListIdIdeasMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PostApiV1IdeasListsByIdeasListIdIdeasMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = postApiV1IdeasListsByIdeasListIdIdeasMutationKey();
  return mutationOptions<
    PostApiV1IdeasListsByIdeasListIdIdeasMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsByIdeasListIdIdeas400
      | PostApiV1IdeasListsByIdeasListIdIdeas401
      | PostApiV1IdeasListsByIdeasListIdIdeas403
      | PostApiV1IdeasListsByIdeasListIdIdeas404
      | PostApiV1IdeasListsByIdeasListIdIdeas500
    >,
    {
      ideasListId: PostApiV1IdeasListsByIdeasListIdIdeasPathParams["ideasListId"];
      data: PostApiV1IdeasListsByIdeasListIdIdeasMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ ideasListId, data }) => {
      return postApiV1IdeasListsByIdeasListIdIdeas(
        { ideasListId, data },
        config,
      );
    },
  });
}

/**
 * {@link /api/v1/ideas-lists/:ideasListId/ideas}
 */
export function usePostApiV1IdeasListsByIdeasListIdIdeas<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1IdeasListsByIdeasListIdIdeasMutationResponse,
      ResponseErrorConfig<
        | PostApiV1IdeasListsByIdeasListIdIdeas400
        | PostApiV1IdeasListsByIdeasListIdIdeas401
        | PostApiV1IdeasListsByIdeasListIdIdeas403
        | PostApiV1IdeasListsByIdeasListIdIdeas404
        | PostApiV1IdeasListsByIdeasListIdIdeas500
      >,
      {
        ideasListId: PostApiV1IdeasListsByIdeasListIdIdeasPathParams["ideasListId"];
        data: PostApiV1IdeasListsByIdeasListIdIdeasMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostApiV1IdeasListsByIdeasListIdIdeasMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    postApiV1IdeasListsByIdeasListIdIdeasMutationKey();

  const baseOptions = postApiV1IdeasListsByIdeasListIdIdeasMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiV1IdeasListsByIdeasListIdIdeasMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsByIdeasListIdIdeas400
      | PostApiV1IdeasListsByIdeasListIdIdeas401
      | PostApiV1IdeasListsByIdeasListIdIdeas403
      | PostApiV1IdeasListsByIdeasListIdIdeas404
      | PostApiV1IdeasListsByIdeasListIdIdeas500
    >,
    {
      ideasListId: PostApiV1IdeasListsByIdeasListIdIdeasPathParams["ideasListId"];
      data: PostApiV1IdeasListsByIdeasListIdIdeasMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostApiV1IdeasListsByIdeasListIdIdeasMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsByIdeasListIdIdeas400
      | PostApiV1IdeasListsByIdeasListIdIdeas401
      | PostApiV1IdeasListsByIdeasListIdIdeas403
      | PostApiV1IdeasListsByIdeasListIdIdeas404
      | PostApiV1IdeasListsByIdeasListIdIdeas500
    >,
    {
      ideasListId: PostApiV1IdeasListsByIdeasListIdIdeasPathParams["ideasListId"];
      data: PostApiV1IdeasListsByIdeasListIdIdeasMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiV1IdeasListsByIdeasListIdIdeasMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsByIdeasListIdIdeas400
      | PostApiV1IdeasListsByIdeasListIdIdeas401
      | PostApiV1IdeasListsByIdeasListIdIdeas403
      | PostApiV1IdeasListsByIdeasListIdIdeas404
      | PostApiV1IdeasListsByIdeasListIdIdeas500
    >,
    {
      ideasListId: PostApiV1IdeasListsByIdeasListIdIdeasPathParams["ideasListId"];
      data: PostApiV1IdeasListsByIdeasListIdIdeasMutationRequest;
    },
    TContext
  >;
}
