/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/utils/client.ts";
import fetch from "@/lib/api/utils/client.ts";

import { postApiV1IdeasListsIdeasListIdMoreIdeas } from "../clients/post-api-v1-ideas-lists-ideas-list-id-more-ideas.ts";
import type {
  PostApiV1IdeasListsIdeasListIdMoreIdeas400,
  PostApiV1IdeasListsIdeasListIdMoreIdeas401,
  PostApiV1IdeasListsIdeasListIdMoreIdeas403,
  PostApiV1IdeasListsIdeasListIdMoreIdeas404,
  PostApiV1IdeasListsIdeasListIdMoreIdeas500,
  PostApiV1IdeasListsIdeasListIdMoreIdeasMutationRequest,
  PostApiV1IdeasListsIdeasListIdMoreIdeasMutationResponse,
  PostApiV1IdeasListsIdeasListIdMoreIdeasPathParams,
} from "../models/post-api-v1-ideas-lists-ideas-list-id-more-ideas.ts";

export const postApiV1IdeasListsIdeasListIdMoreIdeasMutationKey = () =>
  [{ url: "/api/v1/ideas-lists/:ideasListId/more-ideas" }] as const;

export type PostApiV1IdeasListsIdeasListIdMoreIdeasMutationKey = ReturnType<
  typeof postApiV1IdeasListsIdeasListIdMoreIdeasMutationKey
>;

export function postApiV1IdeasListsIdeasListIdMoreIdeasMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PostApiV1IdeasListsIdeasListIdMoreIdeasMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = postApiV1IdeasListsIdeasListIdMoreIdeasMutationKey();
  return mutationOptions<
    PostApiV1IdeasListsIdeasListIdMoreIdeasMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsIdeasListIdMoreIdeas400
      | PostApiV1IdeasListsIdeasListIdMoreIdeas401
      | PostApiV1IdeasListsIdeasListIdMoreIdeas403
      | PostApiV1IdeasListsIdeasListIdMoreIdeas404
      | PostApiV1IdeasListsIdeasListIdMoreIdeas500
    >,
    {
      ideasListId: PostApiV1IdeasListsIdeasListIdMoreIdeasPathParams["ideasListId"];
      data?: PostApiV1IdeasListsIdeasListIdMoreIdeasMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ ideasListId, data }) => {
      return postApiV1IdeasListsIdeasListIdMoreIdeas(
        { ideasListId, data },
        config,
      );
    },
  });
}

/**
 * {@link /api/v1/ideas-lists/:ideasListId/more-ideas}
 */
export function usePostApiV1IdeasListsIdeasListIdMoreIdeas<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1IdeasListsIdeasListIdMoreIdeasMutationResponse,
      ResponseErrorConfig<
        | PostApiV1IdeasListsIdeasListIdMoreIdeas400
        | PostApiV1IdeasListsIdeasListIdMoreIdeas401
        | PostApiV1IdeasListsIdeasListIdMoreIdeas403
        | PostApiV1IdeasListsIdeasListIdMoreIdeas404
        | PostApiV1IdeasListsIdeasListIdMoreIdeas500
      >,
      {
        ideasListId: PostApiV1IdeasListsIdeasListIdMoreIdeasPathParams["ideasListId"];
        data?: PostApiV1IdeasListsIdeasListIdMoreIdeasMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostApiV1IdeasListsIdeasListIdMoreIdeasMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    postApiV1IdeasListsIdeasListIdMoreIdeasMutationKey();

  const baseOptions = postApiV1IdeasListsIdeasListIdMoreIdeasMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiV1IdeasListsIdeasListIdMoreIdeasMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsIdeasListIdMoreIdeas400
      | PostApiV1IdeasListsIdeasListIdMoreIdeas401
      | PostApiV1IdeasListsIdeasListIdMoreIdeas403
      | PostApiV1IdeasListsIdeasListIdMoreIdeas404
      | PostApiV1IdeasListsIdeasListIdMoreIdeas500
    >,
    {
      ideasListId: PostApiV1IdeasListsIdeasListIdMoreIdeasPathParams["ideasListId"];
      data?: PostApiV1IdeasListsIdeasListIdMoreIdeasMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostApiV1IdeasListsIdeasListIdMoreIdeasMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsIdeasListIdMoreIdeas400
      | PostApiV1IdeasListsIdeasListIdMoreIdeas401
      | PostApiV1IdeasListsIdeasListIdMoreIdeas403
      | PostApiV1IdeasListsIdeasListIdMoreIdeas404
      | PostApiV1IdeasListsIdeasListIdMoreIdeas500
    >,
    {
      ideasListId: PostApiV1IdeasListsIdeasListIdMoreIdeasPathParams["ideasListId"];
      data?: PostApiV1IdeasListsIdeasListIdMoreIdeasMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiV1IdeasListsIdeasListIdMoreIdeasMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsIdeasListIdMoreIdeas400
      | PostApiV1IdeasListsIdeasListIdMoreIdeas401
      | PostApiV1IdeasListsIdeasListIdMoreIdeas403
      | PostApiV1IdeasListsIdeasListIdMoreIdeas404
      | PostApiV1IdeasListsIdeasListIdMoreIdeas500
    >,
    {
      ideasListId: PostApiV1IdeasListsIdeasListIdMoreIdeasPathParams["ideasListId"];
      data?: PostApiV1IdeasListsIdeasListIdMoreIdeasMutationRequest;
    },
    TContext
  >;
}
