/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { postApiV1BillingSubscriptionsCharge } from "../clients/post-api-v1-billing-subscriptions-charge.ts";
import type {
  PostApiV1BillingSubscriptionsCharge400,
  PostApiV1BillingSubscriptionsCharge401,
  PostApiV1BillingSubscriptionsCharge402,
  PostApiV1BillingSubscriptionsCharge403,
  PostApiV1BillingSubscriptionsCharge404,
  PostApiV1BillingSubscriptionsCharge500,
  PostApiV1BillingSubscriptionsChargeMutationResponse,
} from "../models/post-api-v1-billing-subscriptions-charge.ts";

export const postApiV1BillingSubscriptionsChargeMutationKey = () =>
  [{ url: "/api/v1/billing/subscriptions-charge" }] as const;

export type PostApiV1BillingSubscriptionsChargeMutationKey = ReturnType<
  typeof postApiV1BillingSubscriptionsChargeMutationKey
>;

export function postApiV1BillingSubscriptionsChargeMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = postApiV1BillingSubscriptionsChargeMutationKey();
  return mutationOptions<
    PostApiV1BillingSubscriptionsChargeMutationResponse,
    ResponseErrorConfig<
      | PostApiV1BillingSubscriptionsCharge400
      | PostApiV1BillingSubscriptionsCharge401
      | PostApiV1BillingSubscriptionsCharge402
      | PostApiV1BillingSubscriptionsCharge403
      | PostApiV1BillingSubscriptionsCharge404
      | PostApiV1BillingSubscriptionsCharge500
    >,
    void,
    TContext
  >({
    mutationKey,
    mutationFn: async () => {
      return postApiV1BillingSubscriptionsCharge(config);
    },
  });
}

/**
 * {@link /api/v1/billing/subscriptions-charge}
 */
export function usePostApiV1BillingSubscriptionsCharge<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1BillingSubscriptionsChargeMutationResponse,
      ResponseErrorConfig<
        | PostApiV1BillingSubscriptionsCharge400
        | PostApiV1BillingSubscriptionsCharge401
        | PostApiV1BillingSubscriptionsCharge402
        | PostApiV1BillingSubscriptionsCharge403
        | PostApiV1BillingSubscriptionsCharge404
        | PostApiV1BillingSubscriptionsCharge500
      >,
      void,
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    postApiV1BillingSubscriptionsChargeMutationKey();

  const baseOptions = postApiV1BillingSubscriptionsChargeMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiV1BillingSubscriptionsChargeMutationResponse,
    ResponseErrorConfig<
      | PostApiV1BillingSubscriptionsCharge400
      | PostApiV1BillingSubscriptionsCharge401
      | PostApiV1BillingSubscriptionsCharge402
      | PostApiV1BillingSubscriptionsCharge403
      | PostApiV1BillingSubscriptionsCharge404
      | PostApiV1BillingSubscriptionsCharge500
    >,
    void,
    TContext
  >;

  return useMutation<
    PostApiV1BillingSubscriptionsChargeMutationResponse,
    ResponseErrorConfig<
      | PostApiV1BillingSubscriptionsCharge400
      | PostApiV1BillingSubscriptionsCharge401
      | PostApiV1BillingSubscriptionsCharge402
      | PostApiV1BillingSubscriptionsCharge403
      | PostApiV1BillingSubscriptionsCharge404
      | PostApiV1BillingSubscriptionsCharge500
    >,
    void,
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiV1BillingSubscriptionsChargeMutationResponse,
    ResponseErrorConfig<
      | PostApiV1BillingSubscriptionsCharge400
      | PostApiV1BillingSubscriptionsCharge401
      | PostApiV1BillingSubscriptionsCharge402
      | PostApiV1BillingSubscriptionsCharge403
      | PostApiV1BillingSubscriptionsCharge404
      | PostApiV1BillingSubscriptionsCharge500
    >,
    void,
    TContext
  >;
}
