/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { postApiV1IdeasListsByIdeasListIdExport } from "../clients/post-api-v1-ideas-lists-by-ideas-list-id-export.ts";
import type {
  PostApiV1IdeasListsByIdeasListIdExport400,
  PostApiV1IdeasListsByIdeasListIdExport401,
  PostApiV1IdeasListsByIdeasListIdExport403,
  PostApiV1IdeasListsByIdeasListIdExport404,
  PostApiV1IdeasListsByIdeasListIdExport500,
  PostApiV1IdeasListsByIdeasListIdExportMutationRequest,
  PostApiV1IdeasListsByIdeasListIdExportMutationResponse,
  PostApiV1IdeasListsByIdeasListIdExportPathParams,
} from "../models/post-api-v1-ideas-lists-by-ideas-list-id-export.ts";

export const postApiV1IdeasListsByIdeasListIdExportMutationKey = () =>
  [{ url: "/api/v1/ideas-lists/:ideasListId/export" }] as const;

export type PostApiV1IdeasListsByIdeasListIdExportMutationKey = ReturnType<
  typeof postApiV1IdeasListsByIdeasListIdExportMutationKey
>;

export function postApiV1IdeasListsByIdeasListIdExportMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PostApiV1IdeasListsByIdeasListIdExportMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = postApiV1IdeasListsByIdeasListIdExportMutationKey();
  return mutationOptions<
    PostApiV1IdeasListsByIdeasListIdExportMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsByIdeasListIdExport400
      | PostApiV1IdeasListsByIdeasListIdExport401
      | PostApiV1IdeasListsByIdeasListIdExport403
      | PostApiV1IdeasListsByIdeasListIdExport404
      | PostApiV1IdeasListsByIdeasListIdExport500
    >,
    {
      ideasListId: PostApiV1IdeasListsByIdeasListIdExportPathParams["ideasListId"];
      data: PostApiV1IdeasListsByIdeasListIdExportMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ ideasListId, data }) => {
      return postApiV1IdeasListsByIdeasListIdExport(
        { ideasListId, data },
        config,
      );
    },
  });
}

/**
 * {@link /api/v1/ideas-lists/:ideasListId/export}
 */
export function usePostApiV1IdeasListsByIdeasListIdExport<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1IdeasListsByIdeasListIdExportMutationResponse,
      ResponseErrorConfig<
        | PostApiV1IdeasListsByIdeasListIdExport400
        | PostApiV1IdeasListsByIdeasListIdExport401
        | PostApiV1IdeasListsByIdeasListIdExport403
        | PostApiV1IdeasListsByIdeasListIdExport404
        | PostApiV1IdeasListsByIdeasListIdExport500
      >,
      {
        ideasListId: PostApiV1IdeasListsByIdeasListIdExportPathParams["ideasListId"];
        data: PostApiV1IdeasListsByIdeasListIdExportMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostApiV1IdeasListsByIdeasListIdExportMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    postApiV1IdeasListsByIdeasListIdExportMutationKey();

  const baseOptions = postApiV1IdeasListsByIdeasListIdExportMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiV1IdeasListsByIdeasListIdExportMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsByIdeasListIdExport400
      | PostApiV1IdeasListsByIdeasListIdExport401
      | PostApiV1IdeasListsByIdeasListIdExport403
      | PostApiV1IdeasListsByIdeasListIdExport404
      | PostApiV1IdeasListsByIdeasListIdExport500
    >,
    {
      ideasListId: PostApiV1IdeasListsByIdeasListIdExportPathParams["ideasListId"];
      data: PostApiV1IdeasListsByIdeasListIdExportMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostApiV1IdeasListsByIdeasListIdExportMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsByIdeasListIdExport400
      | PostApiV1IdeasListsByIdeasListIdExport401
      | PostApiV1IdeasListsByIdeasListIdExport403
      | PostApiV1IdeasListsByIdeasListIdExport404
      | PostApiV1IdeasListsByIdeasListIdExport500
    >,
    {
      ideasListId: PostApiV1IdeasListsByIdeasListIdExportPathParams["ideasListId"];
      data: PostApiV1IdeasListsByIdeasListIdExportMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiV1IdeasListsByIdeasListIdExportMutationResponse,
    ResponseErrorConfig<
      | PostApiV1IdeasListsByIdeasListIdExport400
      | PostApiV1IdeasListsByIdeasListIdExport401
      | PostApiV1IdeasListsByIdeasListIdExport403
      | PostApiV1IdeasListsByIdeasListIdExport404
      | PostApiV1IdeasListsByIdeasListIdExport500
    >,
    {
      ideasListId: PostApiV1IdeasListsByIdeasListIdExportPathParams["ideasListId"];
      data: PostApiV1IdeasListsByIdeasListIdExportMutationRequest;
    },
    TContext
  >;
}
