/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@/lib/api/client";

import { postApiV1ScenariosScenesBySceneIdPreview } from "../clients/post-api-v1-scenarios-scenes-by-scene-id-preview.ts";
import type {
  PostApiV1ScenariosScenesBySceneIdPreview400,
  PostApiV1ScenariosScenesBySceneIdPreview401,
  PostApiV1ScenariosScenesBySceneIdPreview402,
  PostApiV1ScenariosScenesBySceneIdPreview403,
  PostApiV1ScenariosScenesBySceneIdPreview404,
  PostApiV1ScenariosScenesBySceneIdPreview500,
  PostApiV1ScenariosScenesBySceneIdPreviewMutationResponse,
  PostApiV1ScenariosScenesBySceneIdPreviewPathParams,
} from "../models/post-api-v1-scenarios-scenes-by-scene-id-preview.ts";

export const postApiV1ScenariosScenesBySceneIdPreviewMutationKey = () =>
  [{ url: "/api/v1/scenarios/scenes/:sceneId/preview" }] as const;

export type PostApiV1ScenariosScenesBySceneIdPreviewMutationKey = ReturnType<
  typeof postApiV1ScenariosScenesBySceneIdPreviewMutationKey
>;

export function postApiV1ScenariosScenesBySceneIdPreviewMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = postApiV1ScenariosScenesBySceneIdPreviewMutationKey();
  return mutationOptions<
    PostApiV1ScenariosScenesBySceneIdPreviewMutationResponse,
    ResponseErrorConfig<
      | PostApiV1ScenariosScenesBySceneIdPreview400
      | PostApiV1ScenariosScenesBySceneIdPreview401
      | PostApiV1ScenariosScenesBySceneIdPreview402
      | PostApiV1ScenariosScenesBySceneIdPreview403
      | PostApiV1ScenariosScenesBySceneIdPreview404
      | PostApiV1ScenariosScenesBySceneIdPreview500
    >,
    { sceneId: PostApiV1ScenariosScenesBySceneIdPreviewPathParams["sceneId"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ sceneId }) => {
      return postApiV1ScenariosScenesBySceneIdPreview({ sceneId }, config);
    },
  });
}

/**
 * {@link /api/v1/scenarios/scenes/:sceneId/preview}
 */
export function usePostApiV1ScenariosScenesBySceneIdPreview<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostApiV1ScenariosScenesBySceneIdPreviewMutationResponse,
      ResponseErrorConfig<
        | PostApiV1ScenariosScenesBySceneIdPreview400
        | PostApiV1ScenariosScenesBySceneIdPreview401
        | PostApiV1ScenariosScenesBySceneIdPreview402
        | PostApiV1ScenariosScenesBySceneIdPreview403
        | PostApiV1ScenariosScenesBySceneIdPreview404
        | PostApiV1ScenariosScenesBySceneIdPreview500
      >,
      {
        sceneId: PostApiV1ScenariosScenesBySceneIdPreviewPathParams["sceneId"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    postApiV1ScenariosScenesBySceneIdPreviewMutationKey();

  const baseOptions = postApiV1ScenariosScenesBySceneIdPreviewMutationOptions(
    config,
  ) as UseMutationOptions<
    PostApiV1ScenariosScenesBySceneIdPreviewMutationResponse,
    ResponseErrorConfig<
      | PostApiV1ScenariosScenesBySceneIdPreview400
      | PostApiV1ScenariosScenesBySceneIdPreview401
      | PostApiV1ScenariosScenesBySceneIdPreview402
      | PostApiV1ScenariosScenesBySceneIdPreview403
      | PostApiV1ScenariosScenesBySceneIdPreview404
      | PostApiV1ScenariosScenesBySceneIdPreview500
    >,
    { sceneId: PostApiV1ScenariosScenesBySceneIdPreviewPathParams["sceneId"] },
    TContext
  >;

  return useMutation<
    PostApiV1ScenariosScenesBySceneIdPreviewMutationResponse,
    ResponseErrorConfig<
      | PostApiV1ScenariosScenesBySceneIdPreview400
      | PostApiV1ScenariosScenesBySceneIdPreview401
      | PostApiV1ScenariosScenesBySceneIdPreview402
      | PostApiV1ScenariosScenesBySceneIdPreview403
      | PostApiV1ScenariosScenesBySceneIdPreview404
      | PostApiV1ScenariosScenesBySceneIdPreview500
    >,
    { sceneId: PostApiV1ScenariosScenesBySceneIdPreviewPathParams["sceneId"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostApiV1ScenariosScenesBySceneIdPreviewMutationResponse,
    ResponseErrorConfig<
      | PostApiV1ScenariosScenesBySceneIdPreview400
      | PostApiV1ScenariosScenesBySceneIdPreview401
      | PostApiV1ScenariosScenesBySceneIdPreview402
      | PostApiV1ScenariosScenesBySceneIdPreview403
      | PostApiV1ScenariosScenesBySceneIdPreview404
      | PostApiV1ScenariosScenesBySceneIdPreview500
    >,
    { sceneId: PostApiV1ScenariosScenesBySceneIdPreviewPathParams["sceneId"] },
    TContext
  >;
}
